lib/migrate/index.js
Next major release this should be changed to an assertions. Can't see a reason you'd basically have a migration be a noop.
=> Warn when a migration does not return a promise

index.html
Changed "its self" to "itself" under "Initializing the Library."
=> Small grammatical change in index.html ("its self" >> "itself")

lib/formatter.js, test/unit/query/builder.js
This updates `Formatter#checkRaw()` to pass the `parameter` flag to `outputQuery()` as `alwaysWrapped`.
Fixes #627.
=> Fix bare subqueries in insert statements.

index.html, lib/query/builder.js, test/unit/query/builder.js
union's wrap parameter was being ignored and misinterpreted when
building statements.  Maintain the spirit of the original implementation
(variable number of callbacks) consistent with other instances of
variadic-like behavior (select/columns), including handling list of
callbacks in array, while still processing the wrap parameter.
Updated documentation which was missing a reference to wrap, and
provided a unit test for wrapped unions.
=> Respect union wrap parameter as last argument

lib/migrate/index.js
The function `validateMigrationList()` should be given one parameter (an array of the promises returned by `Promise.all()`), rather than two arguments as was previously the case. 
This fixed an error I was having and then I was unable to reproduce it.
=> Fix migration bug where database is empty

.jshintrc, lib/dialects/mysql/schema/table.js, lib/dialects/sqlite3/schema/ddl.js, test/integration/schema/index.js, test/unit/schema/sqlite3.js
This turned more into a general refactor of the column name replacement code. Besides the problems I've mentioned previously, I realized/encountered a couple more to do with self-referencing foreign keys. A general search and replace on the strings is undesirable unless we can guarantee that nothing bad will happen, which is also I assume why the replacement strings were qualified with commas and stuff. The new method breaks the query into a few pieces and performs replacements only in appropriate places. It does NOT handle expressions in the query flow, since they can basically be just any SQL, but this shouldn't matter for where/how it's being used?
Cases tested: Do nothing if no match, replace column name in string only in the column definition, and not matching string in a foreign key …
=> Fix sqlite3 rename column

index.html, lib/query/builder.js, lib/query/compiler.js, lib/query/methods.js, test/unit/query/builder.js
whereNot, orWhereNot methods added to single and wrapped wheres. Related tests are also added.
Example:
var result = knex.whereNot(function() {
this.where('a', '=', 1).orWhereNot('b', '=', 3);
});
Produces:
... where not (a = 1 or not b = 3)
Note: I could not be sure how to update documentation. So I didn't add documentation to the repository. Below is documentation necessary:
whereNot.    whereNot(~mixed~)
Object Syntax:
knex('users').whereNot({
first_name: 'Test',
last_name:  'User'
}).select('id')
Outputs:
select "id" from "users" where not "first_name" = 'Test' and not "last_name" = 'User'
Key, Value:
knex('users').whereNot('id', 1)
Outputs:
select * from "users" where not "id" = '1'
Grouped Chain:
knex('users').whereNot(function() {
this.where('id', 1).whereNot('id', '>', 10) …
=> whereNot and orWhereNot added

lib/migrate/index.js
The query to get the highest batch aliases the field to a camel-case name (`select max(batch) as batchNo`). Since Redshift downcases table and column names, the result comes back as `batchno` instead of `batchNo`. Using a snake-cased name instead fixes this.
Closes #758
=> Don't use camelCase in aliased column names

lib/query/builder.js, test/unit/query/builder.js
This change allows to pass column as raw instead of having to pass the whole condition. This should be completely back compatible and allows the following syntax which is already allowed on `.whereIn` and `.whereBetween`:
```js
qb.where(knex.raw('"metadata"->\'width\''), operator, value)
```
I know that you can still achieve this by passing everything on the raw query but it was surprising to me that you couldn't do it this way. Feel free to close this if you think it's completely unnecessary.
regards
=> Allow raw columns in where clauses

lib/dialects/mysql2/index.js, test/index.js
I'm struggling with how to add unit tests for the dialect adapter so that I can test the changed behavior of acquireRawConnection.  I hope to push that back before too long.
=> Allow mysql2 to use a non-default port

lib/index.js, package.json
using webpack to create a static build doesn't actually work because webpack uses different methods to look up the modules or something I don't know it through an error when I tried to bundle it, this doesn't and we can add more files to explicitly ignore if it gets too big
=> fix to work in browserify

lib/seed/stub/coffee.stub, lib/seed/stub/js.stub
I just started started using the seed feature of knex, which is awesome!
I thought it might be nice to add a trailing comma to make it easier to
copy/paste new lines.
Just a minor tweak.
=> Adds trailing commas to seed stubs

index.html
Fix migration connection example; change `username` to `user`:
```
Knex:Error Pool2 - error: Error allocating resources: password authentication failed for user "x"
```
=> Fix migration username example

src/dialects/oracle/stream.js
The new usage => for function introduced an error in streaming for oracle.
=> Fix oracle stream - regression

index.html, lib/query/builder.js, src/query/builder.js, test/unit/query/builder.js
Recently moved from Bookshelf to writing raw `knex` queries and loving the experience. One thing that's bugging me is that there doesn't seem to be a great way to extract commonly used domain-specific query patterns and reuse them as functions.
This spike adds `.compose(fn)` method to the query builder to achieve this. The method takes in a callback function, whose `this` context is bound to the current query builder. From syntax point of view it works similarly with `.whereWrapped(fn)`, but additionally allows the function to add arbitrary operations to the query. See example below for details.
Just testing waters here, are you interested in this type of new functionality? If yes, I can contribute tests and documentation. Naming and semantics of the method can be changed if you see fit. …
=> Improve query composability and support for utility functions

lib/bin/cli.js, lib/migrate/stub/knexfile-ls.stub
We upgraded the version of knex we were using, and noticed that the migration system received a big overhaul since the last time we looked.  Unfortunately for us, it lost LiveScript support which our migrations were using, so this pull request should add it back in.
=> add LiveScript support back in to knex migrations

lib/dialects/oracle/index.js
right now connection error on oracle in the terminal looks like this:
```
TypeError: the target of promisifyAll must be an object or a function
```
=> fixed connection error handling for oracle dialect

index.html
Had to go digging through the source code to find out how my numeric columns were getting their defaults.  I added a line to the float and decimal columns types' documentation to make it clear.  This is in line with other defaults that are specified in the docs.
=> Clarify documentation for defaults for precision and scale

lib/migrate/stub/coffee.stub, lib/migrate/stub/js.stub, lib/migrate/stub/ls.stub
For 1) consistency and 2) keeping people from doing the wrong thing (eg. refactoring the code and trying to assign an object to `exports`). Less footguns is better :)
=> Change `exports` to `module.exports` in migration stubs

CONTRIBUTING.md, package.json
- Add `npm run babel` command and run it on `npm test` (supersedes PR #1011 - Ensure /lib is up to date during CI tests)
- Fix `npm test` command not working on Windows due to Istanbul config issue (see https://github.com/gotwarlost/istanbul/issues/90)
- Update `CONTRIBUTING.md`
=> NPM test script improvements

index.html
Updated the defaultTo examples in the documentation to reflect the new `knex.fn.now()` function
Refrence #699
=> [doc] Update Examples of defaultTo in Docs  [closes #699]

lib/raw.js, src/raw.js, test/unit/query/builder.js
The query builder checks if the bindings are objects in the following form:
if (this.bindings && typeof this.bindings === 'object') {
This would result in an unexpected behavior if passed an object other than a plain object. For example, if passing a `Date` object, the workaround would be to pass the `Date` object in an array, but that's not very intuitive, given that the `where` function you can pass the `Date` object directly.
This patch uses lodash's `isPlainObject` to do the above check, now we can pass a Date object directly on a raw clause in the same fashion as in the `where` method.
=> Checking for plain object instead object on raw queries

index.html, src/dialects/postgres/schema/columncompiler.js, src/schema/tablebuilder.js, test/unit/schema/postgres.js
=> Jsonb type to schema.

lib/dialects/websql/transaction.js, lib/transaction.js, src/dialects/websql/transaction.js, src/transaction.js, test/integration/builder/transaction.js
As discussed with @tgriesser in #855 the query event is no longer triggered onto the main client when in a transaction. It was simply a miss during the transaction overhaul, according to tgriessers's comments.
Example code:
```
dbClient.on('query', function(obj) {
console.log('onQuery'); //Works in knex < 8.0.0, fails in >= 8.0.0
return obj;
});
dbClient.transaction(function(tr) {
return tr.raw('SELECT version()').then(tr.commit).catch(tr.rollback);
}).then(_.noop).catch(_.noop);
```
There may be better ways of fixing this, I don't know.
=> Query event in Transaction should be proxied to the main client

index.html, src/client.js, src/dialects/oracle/index.js, src/dialects/postgres/index.js, src/dialects/postgres/utils.js, src/dialects/sqlite3/index.js, src/query/string.js, test/unit/query/builder.js
Fixes #662 by adding new configuration option `replaceUndefinedWithDefault` which can be given to all other clients except `sqlite`which does not support `DEFAULT`. 
Change is backwards compatible, since default behavior is not changed, so it should be possible to add to 0.9.1.
=> Optionally use DEFAULT instead of NULL when translating undefined to SQL value.

src/seed/stub/js.stub
Comma removed after third sample entry inside the join statement. While the stub itself is meant to be altered before running, the extra comma suggests to the user improper syntax for a join statement. If the comma is left in by the user, knex seed:run will throw 'unexpected token )' error. 
return statement on js.stub was previously 
```
return Promise.join(
// Deletes ALL existing entries
knex('table_name').del(), 
// Inserts seed entries
knex('table_name').insert({id: 1, colName: 'rowValue'}),
knex('table_name').insert({id: 2, colName: 'rowValue2'}),
knex('table_name').insert({id: 3, colName: 'rowValue3'}),
);
```
is now
```
return Promise.join(
// Deletes ALL existing entries
knex('table_name').del(), 
// Inserts seed entries
knex('table_name').insert({id: 1, colName: 'rowValue'}), …
```
=> removed comma from seed js.stub

src/dialects/sqlite3/index.js
=> Allow disabling sqlite warning on non-supported DEFAULT keyword

index.html, src/formatter.js, src/query/string.js, src/raw.js, test/unit/query/builder.js
Fixes bug in #519 by adding more complete support for `\?` escape sequence
=> Support question mark escaping for knex rendered queries

lib/query/builder.js, src/query/builder.js, test/tape/query-builder.js
Adds a test for `QueryBuilder#clone`. Changes `clone()` behaviour to transfer the debug flag (`QueryBuilder#_debug`) to the cloned instance.
Fixes #1080
=> Include `_debug` property in `QueryBuilder#clone`.

README.md
Just one line. I kept it brief to match the concise style of the readme.
=> Add knex query lab link to readme.

lib/runner.js, src/runner.js
I tried using 'npm build' to generate the PR but a lot of things changed, possibly due to changes in webpack. It's a bit weird to check in both versions of the source -- perhaps a post-install hook to build from source or something like that would be more appropriate?
Tests are still too convoluted for me to have any idea how to go about testing this; just to generate the error to run this down I had to wrap native node.js modules: https://github.com/myndzi/pool2/issues/12#issuecomment-139792551
It's a simple enough fix, though, that I think it's okay to merge and probably release. This will hopefully take care of various random network errors producing error messages from knex that can be safely ignored.
=> Don't attempt to release resources that have been disposed of already

.jshintignore, .jshintrc, build/knex.js, lib/migrate/index.js, package.json, src/migrate/index.js, test/integration/migrate/index.js
* Adds locking when migrations are started
* forceFreeMigrationsLock function to allow removing the lock manually
=> Prevent multiple connections from running migrations at the same time

index.html, src/bin/cli.js
Per the docs for **CLI knexfile.js**, the following configuration should be supported:
> Basic configuration:
> 
```javascript
module.exports = {
client: 'pg',
connection: process.env.DATABASE_URL || {
user: 'me',
database: 'my_app'
}
};
```
Per the following conditional block in [`/src/bin/cli.js#L56-L59`](https://github.com/tgriesser/knex/blob/master/src/bin/cli.js#L56-L59) (introduced in #527) there is no check to make sure `config[environment]` exists.
```javascript
if (environment) {
console.log('Using environment:', chalk.magenta(environment));
config = config[environment];
}
```
**This results in an undefined config when using the basic configuration**.
This pull request includes:
- `config` assignment defaults to itself when `config[environment]` does not exist
- update to the …
=> Fix error with CLI trying to select environment config for "basic configuration"

index.html
These slipped in as part of #1156
=> Fix typos in foreign key docs

index.html
- There was a closing `</column>` instead of `</code>`
=> [Docs] Fixes #1148, closes errant <code> tag in docs

index.html, src/query/compiler.js, test/unit/query/builder.js
Clean version of pq #962 with documentation. Fixes issue #961.
=> Removes object keys with value undefined from being added to DB in update.

src/formatter.js, test/unit/query/builder.js
I've encountered what I think is a bug on the formatting of SQL statements. Take the following example:
```js
var knex = require('knex')(config);
console.log(knex.select('id as foo.bar').from('users').toSQL());
```
This would print
```
{ method: 'select',
options: {},
bindings: [],
sql: 'select "id" as "foo"."bar" from "users"' }
```
like trying to access a field in the alias but instead should be formatted as
```
{ method: 'select',
options: {},
bindings: [],
sql: 'select "id" as "foo.bar" from "users"' }
```
=> fixes bug when using dot in as identifier

index.html, src/util/make-knex.js, test/integration/builder/inserts.js
This was discussed in #757. Couldn't see Tim's code in that issue so not sure how he originally implemented this, but hopefully I'm not too far of.
Ideas for performance improvements is more than welcome. It still takes a bit to insert 5k+ rows.
In short it will create a transaction and insert all the rows within that transaction.
```javascript
knex.batchInsert(tableName, rows, chunkSize = 1)
```
=> knex.batchInsert

build/knex.js, src/migrate/index.js
There is an issue where if you are creating migrations table inside a schema, knex tries to create the table every time even though the table is already created. The real issue is that knex migrations do not handle custom schemas but this is a quick fix to handle those until knex rolls out better support for migrations in multiple schemas.
=> Prevent attempt to create migrations table again if it already exists

src/dialects/mysql2/index.js
You are missing a bunch of support options and one that is coming soon to make decimals numbers. I added them all though I am not sure why we filter them at all. We should just pass them along but didn't want to make a breaking change like that.
**_Had to remove charset as it is different then the Pool2 library's charset._**
=> Add all supported Mysql2 dialect options

index.html, src/raw.js, test/unit/query/builder.js
I explained this in #965 where the handling of bindings for `.raw` was changed in v0.8+ disallowing the use of for example:
```javascript
knex.raw('username = ?', 'Test');
//generates username = 'T' with 4 bindings ['T', 'e', 's', 't']
```
So in the spirit of not breaking applications upon upgrading knex version, this is my suggested solution. It doesn't make any sense to enforce Array bindings while the rest of the knex interface is very flexible, and it also allows for easier-to-read code.
```javascript
knex.raw('username = ?', 'Test');
//now generates username = 'Test'
```
I added a test case so that this does not break again.
Edit: A good argument to why this should be merged, I am going to quote http://knexjs.org/
>**Upgrading 0.7 -> 0.8**
>
>There should be no major changes breaking …
=> Make raw bindings backwards compatible

src/bin/cli.js
When run without local knex installation CLI currently fails with a nice error message in some cases and with TypeError with other cases (migrate:make, seed:make). This changes aligns the behavior to always show the expected error message.
=> Fix CLI failing with TypeError if knex installation missing

index.html, src/query/builder.js, src/query/compiler.js, src/runner.js, test/integration/builder/additional.js
A feature suggestion that adds timecontrol over queries to the querybuilder that is being run in an application, similarly to how you can now control the Timeout for acquiring a new conection in 0.10.
Probably not often that this would have a use case, but in complex queries where you have tons of joins and tons of data, this could prove useful. If not for anything else, it can be used for finding queries that are slowing down an app.
This is not a requested feature or anything that I am personally in need of, just something extra.
=> Add .timeout(ms) to QueryBuilder

src/helpers.js
We have a helper to log an error message to the console and exit the process. It looks like the only place we use this helper is when we try and fail to [initialize the driver](https://github.com/tgriesser/knex/blob/5a94bc9b178d399e23a80ff396a0fc7ec01ecc9b/src/client.js#L159).
Unfortunately, when we call `process.exit()` without an exit code, it [exits with a `0` exit code](https://nodejs.org/api/process.html#process_process_exit_code) -- which means success.
This is especially a problem when running tests in a CI environment, as it results in a false positive: tests not only do not pass, but they probably didn't even run.
=> Fix calling process.exit with "ok" exit code

index.html
The link for "whereNot" was directed to "where".
=> Fix small link bug

index.html
Added additional details specifying that the second argument for `table.enum(column, values)` should be an array of values.
=> Update to enum schema documentation

index.html
`returning()` docs did not explain the parameter structure passed to this API.
It accepts a single parameter which can be either a string or a list of strings and depending on which you send, the final query result is either a list of column values or a list of objects containing column values as properties.
=> Returning doc update

index.html
Fixes #918. `dropIndex` and `dropForeign` had already been added to docs post-issue creation.
=> Add dropUnique and dropPrimary to docs.

index.html
Allows for examples to be displayed for MSSQL dialect in the documentation.
=> Add MSSQL query examples to docs

src/transaction.js, test/tape/transactions.js
The original code for handling nested transactions did not work correctly when you had sibling nested transactions, i.e. two or more transactions all living inside the same parent transaction and latter ones getting started after their predecessor sibling completes (rolls back or commits). In such cases, knex would hang on any DB operation attempted using a non-initial sibling transaction.
Basic cause was in knex _accidentally_ waiting for that same transaction to complete before allowing someone else to access the transaction's database connection. :smiling_imp:
Basic bug fixed in d0836b8f880373836b153e922f401496e2914466.
Detailed tests added for handling sibling tested transactions in 675c684d3bd6b55ed63e4a6d3035754d2964cf8d. You can run those tests to reproduce the hang if you run them …
=> Fixed nested transactions

index.html, src/dialects/oracle/query/compiler.js, test/unit/query/builder.js
https://github.com/tgriesser/knex/issues/1249
=> Allow returning to be used with oracle update

src/schema/tablebuilder.js, test/integration/schema/index.js
Fixes #1220, https://github.com/tgriesser/knex/issues/1220, inTable(undefined) fails silently error by making sure it throws an error if the user passes an undefined table name.
=> Fixes inTable(undefined) silently fails bug from Issue #1220

src/raw.js, test/integration/builder/additional.js
It seems that when `.timeout` was added to query builder, it was not added to instances of `.raw`, that's my bad. This will add the same timeout functionality also for running `.raw` as non-bindings.
```javascript
knex.raw('SELECT something')
.timeout(1000)
.then(_.noop);
//Previously did not work. Now works as expected.
```
Also attempting to fix the timeout test in this PR as its previous implementation was very unreliable.
=> Add .timeout to raw, and attempt to fix the timeout test

index.html, src/transaction.js, test/integration/builder/transaction.js, test/tape/transactions.js
Originally if a transaction callback threw an error, `knex`'s & database's transaction tracking got out of sync:
- `knex` considered the transaction completed & rejected its transaction promise
- DB was not told to roll back its transaction so the used database connection got returned to the connection pool without its transaction actually getting rolled back
Effect would be random database deadlocks and/or operations failures later on due to application code running under a transaction when it does not expect to be, e.g. it can cause that transaction to start holding database locks and thus block other regular transactions, and all of it at random depending on the order in which connections get grabbed from the `knex` connection pool.
This changes the behaviour by treating such thrown …
=> Fix transaction callback throw handling

index.html, src/raw.js, test/tape/raw.js, test/unit/query/builder.js
Fixes #1228  . I'm unsure why the first condition of the regular expression was there, as it shouldn't matter at all?
It should now properly match named bindings, and will not require a space before the binding *(see related issue)*.
I also added a test for this based on examples in documentation.
See http://regexr.com/3cv16
------------------------
**TODO**
=> Update regex for named bindings

src/schema/tablebuilder.js, test/integration/schema/index.js
Seen quite a few issues caused by missing a callback function, and the stack generated isn't very specific. The documentation states a callback is to be supplied, and while it's easy to forget, this will at least ease up the confusion.
See example #1256
=> Add TypeError if missing callback in Schema .createTable/.table

index.html
The hash (#) was missing for two hyperlinks. This fixes that.
=> Fix a few hyperlinks in the changelog

index.html, src/schema/tablebuilder.js, test/unit/schema/postgres.js
This closes #547. I've added a third parameter to `timestamps` so it will be backwards compatible.
=> Add option to timestamps to be not null and default to the current timestamp

index.html, src/dialects/postgres/schema/tablecompiler.js, src/schema/tablebuilder.js, test/unit/schema/mysql.js, test/unit/schema/postgres.js
Allow postgres tables to inherit. http://www.postgresql.org/docs/9.1/static/ddl-inherit.html
=> Add inherits to postgres. Updated dialect-specific methods.

index.html, src/migrate/index.js, test/tape/index.js, test/tape/migrate.js
Summary of changes:
- ~~Fix some typos from migrate API docs~~ (someone else was faster)
- Add a mention about `disableTransactions` config option
- Add descriptions for each config option
- Remove mention of config option `database` (couldn't find out where that would be used, hope I got this right?)
- Add basic `tape` tests for the migrator
Proof-reading the config option descriptions is probably a good idea.
The changes to actual code are sort-of cosmetic, just thought to make it easier to find the config default values. Was thinking of asserting for valid values in `setConfig()`, but didn't want to start breaking apps which are potentially feeding in invalid/old config values.
=> Improve tests and docs for migrate API

package.json
I suggest adding coffeescript to test process if continued support is desired.
=> update liftoff dependency so that coffeescript knexfiles and configurations are supported again.

src/client.js, src/runner.js, test/integration/builder/additional.js
Discovered in #1305 the events were not being triggered on the query builder, only the client.
=> Ensure events are triggered on the builder as well as the client.

src/dialects/postgres/index.js
aliyun.com RDS service return a simplified version "PostgreSQL x.x.x", and function checkVersion failed to handle it
=> update index.js to work with aliyun rds

src/dialects/mssql/index.js, src/dialects/oracle/index.js, src/interface.js, src/query/builder.js, src/query/compiler.js, src/raw.js, test/integration/builder/selects.js, test/tape/raw.js, test/unit/query/builder.js
This was a doosey and a half.. The main issue was that `prepBindings` was not being called in the `QueryCompiler`.
Interestingly however, some `prepBindings` that weren't being called also resulted in invalid tests, specifically for postgres. Reason for this is that the `pg` module and knex's own `prepBindings` -> `prepareValue` converts `Numbers` to `Strings` prior to executing the query. I'm mentioning this so you know why I had to change a few tests.
I also had to do a hacky-fix to one of the tests that involved `undefined` values for sqlite3 to prevent the `TypeError` being thrown. Since it does not support `valueForUndefined`, the entire test crashed after applying `prepBindings`, which was to be expected.
cc @rhys-vdw @elhigu @chrisfrancis27
=> Fix valuesForUndefined actual query being executed. Fixes #1268

src/dialects/mysql/schema/tablecompiler.js, test/integration/schema/index.js
Currently this happens for mysql. Fixes #933
=> .renameColumn should not drop defaultValue or nullable state.

src/dialects/mysql/index.js, src/dialects/mysql2/index.js
Briefly noticed in #1198 there's a diff between how `mysql` and `mysql2` handle events, yet they're both almost identical. I can't find an `end` event in `mysql2`, but the `error` is there *(with the appropiate "fatal" flag)* so unless I'm missing something it should be listened to here as well.
https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L96
@elhigu @rhys-vdw Does this make sense to you?
=> Mysql2 should also listen to 'error' events.

index.html, src/client.js, src/dialects/maria/index.js, src/dialects/mssql/index.js, src/dialects/mysql/index.js, src/dialects/mysql2/index.js, src/dialects/oracle/index.js, src/dialects/postgres/index.js, src/dialects/sqlite3/index.js, src/dialects/websql/index.js, src/transaction.js
This should cover the proposal in #1198 .
This will add a default `ping` function to the default `pool` config issuing a `SELECT 1` query to ensure the connection is still alive. So
1. Run query
2. Kill connection
3. Run query
=== Should be resolved. Previously this was rejected with different errors based on the dialect in use.
@woopstar has however confirmed that this does not solve the mysql error in the issue, so this doesn't cover all cases yet. Will want to cover that case as well before merging this.
A timeout has been added to `rollback` to prevent knex from hanging when rollback is issued on a dead connection. There's no harm in silently ignoring this as the connection is dead and the transaction state cannot be recovered.
**TODO**
So far I've tested that this works when closing …
=> Default pool.ping fn, and silently ignore 'Rollback' errors on a dead connection

src/dialects/mssql/schema/tablecompiler.js, test/integration/schema/index.js
This PR fixes the `mssql` driver's `createTableIfNotExists()` function, which previously (due to an inverted condition) would never actually create the table.
It also gets the integration tests *mostly* working; there's one last error I haven't resolved yet:
```
1) Integration Tests mssql | mssql Schema createTable rejects setting foreign key where tableName is not typeof === string:
TypeError: Cannot read property 'sql' of undefined
at TableCompiler.alterTableForCreate (lib/schema/tablecompiler.js:9:10850)
at TableCompiler.create (lib/schema/tablecompiler.js:9:2125)
at TableCompiler.toSQL (lib/schema/tablecompiler.js:9:1456)
at TableBuilder.toSQL (lib/schema/tablebuilder.js:9:1630)
at SchemaCompiler.createTable (lib/schema/compiler.js:9:2304)
at SchemaCompiler.toSQL …
```
=> Mssql fixes

src/util/parse-connection.js, test/tape/parse-connection.js
Use connection.server instead of connection.host when connecting to MSSQL
=> Correct connection URL parsing for MSSQL

src/migrate/index.js
Fixes error introduced in 1d27fb8. `template` fails if passed a `null` second argument.
Fixes #1385
=> Prevent crash on `migrate:make`

src/seed/index.js
- `template` no longer accepts 3 arguments. Fixed by removing `null`
=> Prevent crash on `seed:make`

index.html, src/util/batchInsert.js, src/util/make-knex.js, test/integration/builder/inserts.js
Two things were requested for `batchInsert`:
I've added these two things to the current implementation.
I also decided to rewrite the whole procedure and move it out to a seperate file. I feel that it's very likely this function will eventually be ripped out of the knex repository into a seperate module at some point. Like a utility library of sorts. *(We've talked about this before)*
Not entirely satisfied with how complex-looking this simple thing became, and may have missed something. Please have a look  @rhys-vdw @elhigu !
=> BatchInsert remake proposal. Fixes #1391

src/client.js, src/dialects/mssql/index.js, src/dialects/mssql/query/compiler.js, src/dialects/oracle/index.js, src/dialects/oracle/query/compiler.js, src/dialects/postgres/utils.js, src/dialects/sqlite3/index.js, src/dialects/sqlite3/query/compiler.js, src/query/compiler.js, test/integration/builder/inserts.js, test/unit/query/builder.js
Drivers cannot take knex.raw replacement values as positional replacement values, so they must be evaluated already in query compile time to sql string which is passed to driver.
=> Evaluated multi insert default for undefined already in query compiler

index.html, src/query/compiler.js, src/query/joinclause.js, test/unit/query/builder.js
fix https://github.com/tgriesser/knex/issues/690
make this possible:
```
.leftOuterJoin('accounts', function () {
this
.on('users.id', 'account.user_id')
.andOn(function () {
this.on('users.state', '=', 'NULL');
this.orOn('users.state', 'accounts.state');
});
});
```
=> Allow joins to nest conditional statements

package.json, scripts/build.sh, scripts/webpack.config.js, src/util/make-knex.js
Means that it's impossible to have `Knex#VERSION` and the version in `package.json` out of sync. This is one less thing to do for release.
This required the addition of `json-loader` for webpack. I've also added webpack to `devDependencies` rather than installing it manually during the `build` script.
=> Read `version` from `package.json`

src/client.js, src/dialects/mssql/transaction.js, src/dialects/oracle/transaction.js, src/runner.js, src/transaction.js
See #1382 for a more in-depth description of the bug.
This PR aborts the request to pool2 for a connection when knex times out due to `acquireConnectionTimeout`.  The purpose of this PR is to fix the issue without introducing a breaking change.  I think in the future `acquireConnectionTimeout` should be implemented using pool2's `requestTimeout`, or knex should simply set a default for `requestTimeout` (pool2 sets it to `Infinity`).  When that happens, this PR can probably be reverted.
This is my first time working on the knex codebase.  One thing I was unsure of was how the dialects' implementations relate to the base client implementation.  The client's implementation of `acquireConnection()` now returns an object containing a promise, while the dialect/transactional versions of the …
=> Abort request for connection from pool upon knex timeout

src/dialects/postgres/utils.js
When user provides a knex select statement with an undefined options in where clause it is not properly handled an give an ambiguous error message telling `Unhandled rejection TypeError: Cannot read property 'toString' of undefined.` This PR will helpful to users at it will tell them the exact problem.
=> Proper error message for undefined where options

src/util/batchInsert.js, test/integration/builder/inserts.js
Updates `batchInsert` so that it will use the existing transaction which calls it.
```js
// Existing method for using a transaction with batchInsert
knex.batchInsert(data).transacting(trx);
// New method
trx.batchInsert(data);
```
Implements a change discussed in #1354
=> Use calling transaction with batchInsert

src/transaction.js, test/integration/builder/inserts.js
I had no idea that transacting client didn't inherit root client completely, but is actually constructed from it. Related issue https://github.com/tgriesser/knex/issues/1423
=> Pass valueForUndefined also to transacting client. Fixes #1423

src/index.js, test/tape/knex.js
Solve #1424
To oppose @rhys-vdw [note in #1424](https://github.com/tgriesser/knex/issues/1424#issuecomment-220247608).
I stand to my suggested solution. Client API is really much knex version dependent. If some version of knex would change the API, the plugin-client would stop working any way. So there is no point supporting any other soft verification.
Two tests added.
- One for currently present feature
- One for the new feature
As well PR #1427 merging with this PR would be welcomed.
=> Allow using custom Client/Dialect

index.html, src/dialects/mssql/schema/tablecompiler.js, src/dialects/mysql/schema/tablecompiler.js, src/dialects/oracle/schema/tablecompiler.js, src/dialects/postgres/schema/tablecompiler.js, test/integration/schema/index.js, test/unit/schema/mssql.js, test/unit/schema/mysql.js, test/unit/schema/oracle.js, test/unit/schema/postgres.js
Fixes #1430 
SQLite lacks support for most of this. But for the sake of documentation and consistency, I'm favoring the majority over the minority in this case.
=> Ensure .primary() and .dropPrimary() are the same across all dialects.

src/index.js, src/util/make-knex.js, test/tape/knex.js
Previously only exposed on knex instance or read/parsed straight from `package.json`.
I suggest it would be more valuable than having it on knex instance. Its an improvement PR. So current API will remain the same.
=> Expose Knex version also on the constructor

index.html, src/client.js, src/dialects/mysql/index.js, src/query/builder.js, src/query/compiler.js, src/raw.js, src/runner.js, test/integration/builder/additional.js
Taking a stab at addressing #707 
Adds an optional `options` argument to `.timeout()`.
For MySQL, a `KILL threadId` query will get sent. For all other dialects an error will be thrown immediately from the `.timeout()` call.
While writing tests, I discovered some potentially worrying behavior (comment also added in the test). After a timeout, `knex` releases the connection back to the pool, but the connection may not be usable because the original slow query is still being performed. A subsequent query will acquire the connection (still in-use) and hang until the first query finishes.
=> `.timeout(ms, {cancel: true})` to cancel query after timeout (only implemented for MySQL)

src/transaction.js
This would fix Warning: a promise was created in a handler but not returned from it
Issue: #1388
=> Fixes "a promise was created but was not returned" warning

index.html
When looking for MSSQL support it wasn't immediately clear that it was available within Knex. I was happy to find issue #240 but thought it should be listed as a supported database library in the docs.
=> Add mssql to the list of supported database libraries

src/dialects/oracle/index.js
"SELECT 1" results in the error: ORA-00923: FROM keyword not found where expected
The correct syntax should be "SELECT 1 FROM DUAL".
=> Fix invalid SQL in Oracle dialect ping function

src/util/parse-connection.js, test/tape/parse-connection.js
Earlier today I found that Knex was not parsing a `user` from the following `DATABASE_URL`:
```
mysql://travis@127.0.0.1:3306/yodel_test
```
This was because the URL was missing a password. Because `pg-connection-string` is being used for Postgres connections, this already worked for Postgres URLs. If you want a laugh, feel free to look at my [commits](https://github.com/SpireTeam/yodel/commit/ae4491df4057268e0fbb3343b95e870f09b0a136) [from](https://github.com/SpireTeam/yodel/commit/191ac2687cb9379846b9e58ea1dd98bb45dfaa21) [earlier](https://github.com/SpireTeam/yodel/commit/d9df00d50537b9cf40e9b6879aa4fd2bb9aaa890) [today](https://github.com/SpireTeam/yodel/commit/71827c4064d766106c494bbe8399fc3ec187b723) where I clearly had no idea how I'd broken all our Travis tests by starting to use …
=> Adding support for specifying a DATABASE_URL without a password

index.html
Assuming this was just a typo.
=> Docs: Set "foreign" method name to lowercase

src/query/string.js, test/unit/query/builder.js
It seems like a typo.
Fixes #1520.
=> Fix incorrect escaping in SqlString.escape

src/dialects/mssql/query/compiler.js, test/integration/builder/additional.js
columnInfo() for MSSQL has the default schema (dbo) hard coded.  It should take the database and schema as parameters like the Postgres version does.
=> MSSQL columnInfo() had hard coded schema name

src/helpers.js
Hi There,
Currently using bookshelf in a project. Upon update to knex v0.11.7, noticed that an update was failing with error "Undefined binding(s) detected when compiling RAW query: ...". 
I understand that any data field with value undefined will cause this type of error. 
I looked into my code and found that as part of my query, no data to be bound was "undefined". Digging deeper I found that input values of type "Uint8Array" were failing the deep inspection test on data to be bound in `helpers.js`:
```
export function containsUndefined(mixed) {
let argContainsUndefined = false;
if(mixed && isFunction(mixed.toSQL)) {
//Any QueryBuilder or Raw will automatically be validated during compile.
return argContainsUndefined;
}
if(isArray(mixed)) {
for(let i = 0; i < mixed.length; i++) { …
```
=> Uint8Array data (e.g. Postgres "bytea" type) erroneously considered "undefined" by recent 0.11.7 update.

docs/assets/style.css
Dear Sirs,
Currently, especially in [some](http://knexjs.org/#Builder-main) [places](http://knexjs.org/#Schema) the header and code seem to be too close to each other. I have taken the liberty to add some padding between them.
=> Added padding to avoid header sticking to the example usage.

src/dialects/oracledb/index.js
fixes #1573 
*Question:*
I'm not sure where I can add tests for this... There are tests for the `connectionParser` but my fix is in the oracledb dialect directly.  Should I add a new test file that instantiates this client and tests the parsing? Maybe mocking the actual oracledb package? Seems a little complicated, but let me know what you guys think...
Side note, I've tested this locally and it works, while maintaining backwards compatibility.
ping @rhys-vdw @elhigu because I see you guys were involved in the oracledb merge :-)
=> fix: allow oracledb connectString (issue #1573)

src/dialects/websql/index.js
Fixes an error introduced by the changes of this commit https://github.com/tgriesser/knex/commit/3d9327a2f4b37ddf7975680eacabc36f318f3fc7,
when the dialect is `websql`.
=> Fix #1638 - Websql - Unhandled rejection TypeError: Cannot read property 'timeout' of undefined

.travis.yml, README.md
as title and commit says :)
This highlight some outdated dependancies:
so far, incompatible changes spotted:
- upgrade to babel 6. (non easy)
- bluebird (test failing when upgrading)
=> Add some CI badge to README (npm version, dep status)

package.json, src/dialects/oracledb/index.js
Use of 'new Buffer' has been deprecated in node v6. This swaps the only
deprecated buffer creation in knex with a safe new way of doing allocation. It uses the
safe-buffer module to stay backwards compatible with node < v4. For the full story see [here](https://github.com/AlexTes/buffer-deprecation)
I'd also be totally open to switching out the safe-buffer shim with a ponyfill.
The deprecated method of buffer creation concerns the oracle dialect. I tried to run the tests but failed to do so. If someone who can run the `DB='oracle' npm test` command would try it I'd be very grateful.
To be clear, this doesn't fix #1763. That issue is with knex' dependencies still. In particular node-postgres. However now that `new Buffer(size)` has also been deprecated this should be merged.
=> Use new safe buffer allocation to conform with deprecation of `new Buffer(size)`

src/formatter.js, src/query/compiler.js, test/unit/query/builder.js
allow to write something like this
```js
let subselect = knex.first('column').from('table2 as t2')
.where(knex.raw('t2.ref_id = t1.id'))
.orderBy('t2.created_at', 'desc').as('column');
let query = knex('table1 as t1')
.first('t1.*', subselect)
.where({'t1.id': id, 't1.removed_at': null});
```
without necessity to do `knex.select().limit().as('alias')`
=> allow to use `first` method as aliased select

package.json, src/query/compiler.js, src/raw.js, test/integration/builder/inserts.js
node-uuid has been depreciated, so switch dependencies to uuid.
=> use uuid not node-uuid

src/dialects/mssql/index.js, test/integration/datatype/bigint.js
Essentially, this is a fix for #1604 (also, relates to https://github.com/patriksimek/node-mssql/issues/341).
When using Knex with MSSQL dialect, float values get truncated and, as a result, integer values get saved in decimal fields. This pull request fixes this invalid behaviour.
Feel free to comment or to suggest better solution 😉
=> Fix erroneous float to integer conversion of decimal fields in MSSQL

bin/cli.js, src/migrate/index.js, src/migrate/stub/knexfile-ts.stub, src/migrate/stub/ts.stub, src/seed/index.js, src/seed/stub/ts.stub
This will allow using `knex` in a TypeScript project. These commands will now work:
```bash
$ knex init -x ts
$ knex migrate:make migration_name
$ knex seed:make seed_name
```
`knex` will now generate and automatically pick up `knexfile.ts`, `migration_name.ts`, `seed_name.ts`, assuming [`ts-node`](https://github.com/TypeStrong/ts-node) is available to execute from within the project.
If you like this, I'll also update the docs to indicate that this option is now available.
=> Support knexfile, migration and seeds in TypeScript

src/dialects/mssql/query/compiler.js, test/unit/query/builder.js
The update query for SQL Server requires `from` when doing a join. The join must also be after the `set`. See [here](http://stackoverflow.com/questions/982919/sql-update-query-using-joins).
=> Mssql update query generates invalid syntax

src/client.js, src/dialects/oracle/schema/columncompiler.js, src/dialects/sqlite3/schema/columncompiler.js, src/schema/columncompiler.js, test/tape/knex.js, test/tape/query-builder.js, test/tape/raw.js
The option is documented as required, but it's currently not being validated. This leads to strange side effects such as ones describe in #1628.
I also took the liberty of adding `modifiers` to the base columpcompiler as it currently does not have this property, but it should.
=> Ensure that 'client' is provided in knex config object

src/dialects/postgres/query/compiler.js, src/query/builder.js, src/query/compiler.js, src/util/make-knex.js, test/unit/query/builder.js
Hello, we're requiring the ability to use the `ONLY` keyword  in PostgreSQL and I have done a crude implementation of it in this PR.
Please discuss and provide any comments that would enable this or other PR to be merged that implements the same functionality.
Thank you!
=> ONLY keyword support for PostgreSQL

src/dialects/websql/transaction.js, src/interface.js, src/transaction.js, test/integration/builder/additional.js
This is #1894 only I created a branch that wasn't my master (that won't be changing) to submit it with.
=> More promise functions

src/raw.js, test/unit/query/builder.js
I have had lots of trouble using named bindings when writing raw queries in the past but recently I found that most of my trouble occurs if I am casting. This PR expands the regex used for searching for identifies and values and adds a little bit of logic around it.
This may be a naive approach but I'm open to critique.
```sql
SELECT foo::TEXT 
FROM <table>
WHERE bar = :bar;
```
Currently, this will yield an error complaining about undefined bindings. What's happening behind the scenes is `::TEXT` is being picked up as a named binding but of course it is missing from the given bindings object.
```sql
SELECT :foo::TEXT 
FROM <table>;
```
Currently, this will result in `:foo:` being thought of as an identifier instead of a value being given and casted.
After some digging I found that this …
=> Allow casting when using named bindings.

src/query/builder.js, src/query/methods.js, test/unit/query/builder.js
Copy of #1907, this pull request has my account attached to the commits...
=> added clearSelect and clearWhere to query builder

src/dialects/postgres/index.js, src/runner.js
Without calling `close()`, the `queryStream` will continue to execute a
query meaning there was no way to halt a long running query due to an
unrecoverable downstream error. I ran into this issue while streaming
IDs from a very large table as part of an ETL process. An error would
occur downstream in the transformation or loading step and I needed to
cancel the long-running extract stream, but there was no way to do so
and I'd eventually run out of connections in the pool.
This commit also handles the case when the non-callback version of
stream API was used and an exception was thrown. The issue was that the
promise was not reachable and therefore there was no way to add a
rejection handler. This resulted in an unavoidable `Unhandled Promise
Rejection` error.
=> Properly close PG query stream on error

src/dialects/maria/transaction.js, src/dialects/mysql/transaction.js, src/dialects/mysql2/transaction.js, src/dialects/oracle/transaction.js, src/dialects/oracledb/transaction.js, src/util/batchInsert.js, test/integration/builder/inserts.js, test/integration/builder/transaction.js
I really don't like the code duplication between the base `Transaction.query` implementation and the ones for `mysql`, `mysql2`, and `maria`. For the sake of "keeping dialects separate", I left it as is. Perhaps a better idea just to listen on the `query-error` event and give the `helpers.warn` a call there instead?
=> Bugfixes on batchInsert and transactions for mysql/maria

src/transaction.js, test/integration/builder/transaction.js
Fixes #1052 and fixed + disabled test case of #1970.
=> Fixed transaction promise mutation issue

src/dialects/postgres/index.js, test/unit/schema/postgres.js
Rebased and cleaned up #1959 to see if it passes now.
=> Allow passing version of connected db in configuration file 

src/dialects/postgres/index.js, test/unit/query/builder.js
Found this bug when I added support for writing `moment` instances (which in turn I did to fix timezone issues I had when writing `DATE` types).
```javascript
const moment = require('moment')
moment.fn.toPostgres = function () {
return this.format()
}
```
=> fix: escapeObject parameter order for Postgres dialect.

src/dialects/mysql2/index.js
The whitelist was masking `authSwitchHandler`, and the docs indicate no such filtering should exist:
> The connection options are passed directly to the appropriate database client to create the connection, and may be either an object, or a connection string
=> remove configOptions connection settings filter for mysql2

src/dialects/sqlite3/schema/columncompiler.js, test/integration/builder/additional.js, test/integration/schema/index.js, test/unit/schema/sqlite3.js
Adds support for enum columns in SQLite using a check constraint. Based on the current PostgreSQL implementation. If I missed anything please let me know.
=> Add support for enum columns to SQlite3 dialect

src/dialects/mysql/schema/columncompiler.js, test/integration/schema/index.js, test/unit/schema/mysql.js
Fixed issue, #1946
Should first and after attributes are placed after comment attribute.
=> fixed table alter attributes order. (first, after)

src/client.js
fix incorrect parameter name in Client:runner() method
=> fix incorrect parameter name

src/dialects/mssql/query/compiler.js, test/unit/query/builder.js
#1758
Note that I also fixed a couple of unit tests that were passing even though they should have failed
=> Fix mssql binding ordering for queries that combine a limit with select raw or update

src/dialects/sqlite3/index.js, test/integration/builder/additional.js, test/integration/builder/aggregate.js, test/integration/builder/deletes.js, test/integration/builder/inserts.js, test/integration/builder/joins.js, test/integration/builder/selects.js, test/integration/builder/updates.js, test/integration/schema/index.js, test/unit/query/builder.js, test/unit/schema/sqlite3.js
Addressing https://github.com/tgriesser/knex/issues/1048 and https://github.com/tgriesser/knex/issues/1567
=> Field identifiers were not quoted properly in Sqlite3 dialect

src/util/batchInsert.js
When passing a falsy value to transacting a new transaction is created but `autoTransaction` is set to false so the transaction is never committed or rolled back.
This is a problem because this means `batchInsert` works different then `insert` here.
So passing `null` into `transacting` works for `insert`
```js
knex.insert(rows)
.into('TableName')
.transacting(null)
```
but it doesn't for `batchInsert`
```js
knex.batchInsert('TableName', rows, chunkSize)
.transacting(null)
```
=> Fix falsly setting autoTransaction

src/dialects/mysql/schema/compiler.js, test/integration/schema/index.js
Hi, on MySQL dialect, the method **hasTable** uses the following query to verify if a table exists:
```sql
SHOW TABLES LIKE ?
```
This, could represent an issue if no parameter is defined ([check this issue](https://github.com/tgriesser/knex/issues/2065)).
I've changed the way to verify the existence of the table, as @elhigu said in the same issue, the best way to accomplish this is checking [MySQL's Information Schema](https://dev.mysql.com/doc/refman/5.7/en/tables-table.html)
I've also added a new test passing an empty parameter on **hasTable** returning *false*.
With this PR, you can close the issue https://github.com/tgriesser/knex/issues/2065.
Edited: The PR has not passed successfully the tests. This is not related with my changes, attached you can find a screenshot of the approved …
=> Change the way that MySQL verifies if a table exists (hasTable)

test/unit/query/builder.js
Add unit test for cross-join as there was no one currently.
In the first test-case I test composition of two cross-joins.
In the second test-case I test cross-join with ```on``` statement.
I found out that cross-join with ```on``` is only valid for MySQL
and sqlite3 so the test includes only these (it is weird to use
cross-join with ```on``` anyhow).
=> Add unit test for cross-join

test/unit/schema/postgres.js
There are already unit tests for renaming column but only for oracle.
I figured out that unit testing sqlite, mssql and mysql can not be
done nicely using only ```toSQL``` method but is implemented
in ```test/integration/builder/additional.js```. However test for
postgresql can be done similarly to oracle using no dirty checks
so maybe it can be added.
=> Add unit test for renaming column in postgresql

src/dialects/postgres/schema/tablecompiler.js, test/unit/schema/postgres.js
Ran into an issue where indices created using `withSchema` could not be dropped correctly since dropping couldn't take the schema into account.
Note that the name can optionally be schema qualified according to the documentation: https://www.postgresql.org/docs/9.6/static/sql-dropindex.html
=> Use the schema when dropping indices in Postgres.

test/integration/schema/index.js
Should have been part of the original PR:
https://github.com/tgriesser/knex/pull/2087
=> integration test for sqlite3, referencing non-existent column in the query

test/unit/schema/mysql.js, test/unit/schema/oracle.js, test/unit/schema/oracledb.js, test/unit/schema/postgres.js
I created tests to add table comment. These are for postgresql, mysql and oracle as it seems to me that ```.comment()``` function is not supported for sqlite.
I test setting the comment and setting it back to empty string. I assume that many users will expect that ```.comment(null)``` or simply ```.comment()``` will work the same as ```.comment('')``` I also made tests for these cases. However ```.comment(null)``` and ```.comment()``` does not work that way in mysql so these tests are only for postgresql and oracle.
=> Add unit tests for table comment

test/unit/query/builder.js
Add unit test for ```fullOuterJoin```. No unitTest for MySQL and sqlite3 because they do not support it. Btw I found out that there is also ```outerJoin``` function which however will not work for any dialect. The issue is that it translates to ```OUTER JOIN ON ...``` which is not supported anywhere but ```FULL JOIN ON``` is supported in mssql, postgres and oracle so that is probably a bug.
=> Add fullOuterJoin unit test

src/dialects/sqlite3/schema/ddl.js, src/dialects/sqlite3/schema/tablecompiler.js
* Bugfix for issue #1979 
* The problem was that dropColumn method in sqlite3
Compiler was using only first argument it got from
apply
* Reworked to use 'arguments' instead
=> Fix drop of multiple columns in sqlite3

src/dialects/postgres/index.js
Previously `{searchPath: 'TEST'}` would result in `test` rather than `TEST`.
Fixes #1751
=> searchPath should be case-sensitive

src/query/compiler.js, test/integration/builder/updates.js
Consistent updates where a new field value depends on an another field that gets updated in the same query are impossible across different databases unless the original update order is maintained.
The problem is with MySQL not following the SQL spec as described here: https://dev.mysql.com/doc/refman/5.7/en/ansi-diff-update.html. This causes the value used for calculating another value sometimes already be updated and sometimes not, depending on which database is used and what the names of the fields are if the statements are sorted alphabetically.
This PR removes sorting of statements when building an UPDATE query. A possible future issue is that the key order of an object is not defined in the spec while all known JS engines keep non-integer-like keys in insertion order so this should …
=> Remove sorting of statements from update queries (#2169)

src/transaction.js
Transactions store their unique id on the `txid` property, not `id`.
=> Fix debug output typo

src/formatter.js, test/unit/query/builder.js
=> Adding NOT ILIKE for postgres

package.json, src/client.js, src/dialects/maria/index.js, src/dialects/mssql/index.js, src/dialects/mysql/index.js, src/dialects/mysql2/index.js, src/dialects/oracle/index.js, src/dialects/oracledb/index.js, src/dialects/postgres/index.js, src/dialects/sqlite3/index.js, src/runner.js, test/docker/index.js, test/docker/reconnect.js, test/integration/suite.js, test/knexfile.js
Building on @wubzz work from #2128
=> upgrade generic-pool to 3.1.7

src/client.js, src/dialects/mssql/index.js, src/dialects/mysql/index.js, src/dialects/postgres/index.js, src/dialects/sqlite3/index.js, test/unit/query/builder.js
First part of https://github.com/tgriesser/knex/issues/2084 and https://github.com/tgriesser/knex/issues/929 feature, which allows to write custom identifier wrapper methods. 
So effectively you can describe function how each identifier name are treated, like for example id replacement in `knex.raw('??', ['MyTable.myCol'])` will behave. This is pretty nice feature for ORMs which would like to allow for example different naming scheme for database tables/columns and on javascript side.
Documentation PR is here https://github.com/knex/documentation/pull/51
=> Configuration option to allow override/hook to identifier wrapping code

src/formatter.js, test/unit/query/builder.js
Actually this is slightly breaking change, since now original format how operator was written is not preserved anymore. for example `iLiKe` transforms to `ilike`.
mainly added support for `.where('col', '?', something)`
=> Updated oprator list and allow operator transformation for e.g. escaping ?

scripts/docker-for-test.sh, src/client.js, src/dialects/mssql/index.js, src/dialects/oracle/index.js, src/dialects/oracledb/index.js, src/dialects/postgres/index.js, src/query/compiler.js, test/docker/index.js, test/unit/query/builder.js
There has been a problem that knex hasn't been able to be used as a just query builder, except with SQL where all values are interpolated to one string, which has been passed as a string to driver.
This PR adds a way to get toSQL() result also in native SQL dialects format, where bindings are given separately and SQL string with dialects replacements are provided separately. 
For example with postgresql dialalect query would be like:
```js
{
sql: `select * from "table" where id = $1`,
bindings: [1]
}
```
Feature is implemented to the result of `toSQL()`as a getter function to prevent memory overhead of storing SQL strings and bindings always in two different format.
Here is also one related issue, where this was first requested https://github.com/tgriesser/knex/issues/1286
=> Build native sql for a dialect without to string

.gitignore, src/dialects/oracle/schema/columncompiler.js, src/dialects/postgres/schema/columncompiler.js, src/schema/columncompiler.js, test/integration/schema/index.js
Addresses #2210 
**Changes**
+ I first had to remove the explicit check in the `getModifiers` function that excluded auto-increment columns.
+ I then abstracted the default column name logic for increments columns to a separate function on the prototype of the generic column compiler. I did this because if a user specified a comment on an increments column with no explicit name, the dialect level `comment` method could not figure out the default column name. It is implemented with a lookup map for `defaults`. In the future, if new defaults are added, developers can add a new default key.
+ Finally, I added a specific assertion in a test case to ensure comments are applied to increments columns in the future
**Notes**
+ I added a `.vscode/` exclusion to the `.gitignore`. Visual Studio Code …
=> Fix comments not being applied to increments columns

src/runner.js, test/integration/builder/selects.js
If stream() is used without a handler, make sure to emit connection errors on the stream itself.
This might fix #948, but I've only verified the patch when using Postgres.
=> Fix connection error propagation when streaming

src/client.js, src/runner.js, test/integration/builder/additional.js
Implement hook for allowing to add post processing hook to modify query results (for example to implement snake_case -> camelCase conversion for returned column names) Implements second part for https://github.com/tgriesser/knex/issues/2084
Docs https://github.com/knex/documentation/pull/58
=> Post processing hook for query result

src/dialects/mssql/query/compiler.js, src/query/builder.js, src/query/compiler.js, test/unit/query/builder.js
The aggregate methods include `count`, `min`, `max`, `sum`, `avg`, `countDistinct`, `sumDistinct`, and `avgDistinct`, all of which can now receive raw expressions, e.g.
```js
knex('users').count(knex.raw("data->'active'"));
```
There seems to be some demand for this  (https://github.com/tgriesser/knex/issues/238, https://github.com/tgriesser/knex/issues/1606, https://github.com/tgriesser/knex/issues/935), and I think it's cleaner than the alternative of
```js
knex('users').select(knex.raw("count(data->'active')"));
```
=> Allow raw expressions in query builder aggregate methods

src/formatter.js, test/unit/query/builder.js
Attending to @fengb's proposal on issue #1034, this PR adds support for this notation:
```javascript
knex.select({title, description, createdTime: 'created_time'}).from('tasks')
```
Which compiles as:
```sql
select `title`, `description`, `created_time` as `createdTime` from `tasks`
```
=> Implemented select syntax: select({ alias: 'column' })

src/migrate/index.js
=> Migration Errors - Display filename of of failed migration

package.json
The old version does not load the new coffee interpreter.
=> Update interpret version

src/dialects/sqlite3/query/compiler.js, test/integration/builder/additional.js
Fixes #2184. Not escaping the table name could lead to errors with some table names (group, for example)
=> Fix: Escape table name in SQLite columnInfo call

package.json
The v8flags dependency got updated so that it follows the OS cache location conventions. See [the PR](https://github.com/js-cli/js-v8flags/pull/38) for more information.
=> Update v8flags to version 3.0.0

src/formatter.js, src/query/builder.js, src/query/compiler.js, test/unit/query/builder.js
https://github.com/tgriesser/knex/issues/2263
=> Allow update queries in with statements. Fixes #2263.

src/migrate/index.js
=> Call to knex.migrate.currentVersion causes an error #2111

package.json, src/dialects/mssql/schema/tablecompiler.js, src/dialects/oracle/schema/tablecompiler.js, src/dialects/postgres/schema/tablecompiler.js, src/schema/tablebuilder.js, test/unit/schema/mssql.js, test/unit/schema/mysql.js, test/unit/schema/oracle.js, test/unit/schema/oracledb.js, test/unit/schema/postgres.js
According to discussion in #2101 
When setting table comment to be empty, knex will throw error on non string args
* add unit tests for all dialects
* removed retyping to empty string
All the unit tests are the same. Do you handle this type of redundancy somehow or is it ok with unit tests? Theoretically it might be used as integration test, but I do not think this will be right because these comment tests test only single unit of functionality.
=> Throw error on non-string table comment

src/client.js, test/tape/index.js, test/tape/invalid-db-setup.js
Fixes https://github.com/tgriesser/knex/issues/2325
Problem was that pools create callback must never reject or pool tries to get the resource until acquireConnectionTimeout is triggered.
Sadly generic-pool doesn't allow to change that functionality so I had to write small workaround for it.
=> Fixed passing connection errors directly to the query

src/dialects/sqlite3/query/compiler.js, test/integration/builder/additional.js
As discussed in https://github.com/tgriesser/knex/issues/2312#issuecomment-346549966, here the first commit as a  quick fix restoring previous functionality. A full fix for the other observed issues will follow later.
=> Quick-fix for truncate() on sqlite3 dialect

src/dialects/oracle/schema/columncompiler.js, src/dialects/postgres/schema/columncompiler.js, src/schema/columncompiler.js, test/unit/schema/mssql.js, test/unit/schema/mysql.js, test/unit/schema/oracle.js, test/unit/schema/oracledb.js, test/unit/schema/postgres.js, test/unit/schema/sqlite3.js
The `decimal` type in postgres has the functionality, that when there is no precision and scale defined, you can store values of any precision and scale in the column. (`DECIMAL` and `NUMERIC` are identical)
> Specifying:
>
>     NUMERIC
>
> without any precision or scale creates a column in which numeric values of any precision and scale can be stored, up to the implementation limit on precision. A column of this kind will not coerce input values to any particular scale, whereas numeric columns with a declared scale will coerce input values to that scale. (The SQL standard requires a default scale of 0, i.e., coercion to integer precision. We find this a bit useless. If you're concerned about portability, always specify the precision and scale explicitly.)
Right now knex passes the …
=> Added decimal variable precision / scale support

src/dialects/oracledb/index.js
Incorrectly set UV_THREADPOOL_SIZE when passed from system variables. It's recognized as string (windows).
=> Incorrectly set UV_THREADPOOL_SIZE

src/migrate/index.js
only log the migration name when it is not falsy
=> fixes #2373

src/dialects/mssql/query/compiler.js
When using OUTPUT with updates and a join in MSSQL the OUTPUT needs to come before
the joins.
https://stackoverflow.com/questions/4170389/inner-join-within-update-output-in-one-t-sql-query
=> Fixed a bug when using .returning (OUTPUT) in an update query with joins in MSSQL

src/client.js, src/dialects/mssql/query/compiler.js, src/dialects/mysql/query/compiler.js, src/dialects/oracle/query/compiler.js, src/dialects/postgres/index.js, src/dialects/postgres/query/compiler.js, src/dialects/sqlite3/query/compiler.js, test/integration/builder/additional.js
Hi,
currently `columnInfo` doesn't respect the `wrapIdentifier` function if one is provided in the configuration. This PR fixes that.
fixes #2402
=> Use wrapIdentifier in columnInfo. fixes #2402

bin/cli.js
See issue #2351.
Sorry, I haven't found tests for the `bin/cli.js` file.
[Reference to a stack exchange question, that is somewhat related ☺](https://unix.stackexchange.com/questions/405783/why-does-man-print-gimme-gimme-gimme-at-0030).
=> 2351 CLI sets exit-code 1 if the command supplied was not parseable

package.json, src/client.js, src/dialects/maria/index.js, src/dialects/mssql/index.js, src/dialects/mysql/index.js, src/dialects/mysql2/index.js, src/runner.js, test/docker/reconnect.js, test/integration/suite.js, test/tape/invalid-db-setup.js, test/tape/pool.js
Hi,
This experimental PR replaces the current pool `generic-pool` with [`Tarn`](https://github.com/vincit/tarn.js). There has been a bunch of discussion about this change in the following issues: https://github.com/tgriesser/knex/issues/2339 https://github.com/tgriesser/knex/pull/1702
At this point the pull request is here mainly so that some brave soul, who is having problems with the current pool, could test this out to see if it solves their problems.
Also fixes https://github.com/tgriesser/knex/issues/2442
=> Use tarn as pool

src/helpers.js
=> containsUndefined should only validate plain objects. Fixes #1898

package.json
This is primarly for environments where `rm` is not available, such as Windows without Git Bash.
`rimraf` is already a devDependecy so there is no extra cost in that department.
=> Changed rm to rimraf in 'npm run dev'

.babelconfig.js, .babelrc, package.json
>🙌 Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
Replaced `babel-preset-es2015` with `babel-preset-env` (https://babeljs.io/env/)
I also changed so that running `npm run dev` targets latest node so that debugging code in `lib` during development is easier as not everything gets transpiled, such as classes etc.
=> Changed babel preset and use latest node as target when running dev

src/interface.js, test/integration/builder/transaction.js
Hi, description below. Tests included.
Please advice any further modification you consider
Fixes https://github.com/tgriesser/knex/issues/2079
Those values indicates that the developer probably made a mistake.
=> Checks for an empty, undefined or null object on transacting

src/query/builder.js, test/unit/query/builder.js
Fixes #2061
This throws error in for example
```javascript
knex(table)
.update({column: value})
.first();
```
But does not throw for
```javascript
knex(table)
.first()
.update({column: value});
```
Since the latter correctly generates an update query.
=> Added error if chaining update/insert/etc with first()

src/query/builder.js, src/query/methods.js, test/unit/query/builder.js
this adds the `clearOrder` method
is it normal that atm the order clause is reused like in this example ? 
i ran into this for some obscure reason in a sqlite environnement. the order clause was getting a field from another database... 
```js
const textData = await knex
.select()
.from("myTable")
.where({
etat: "TOP"
})
.orderBy("date", "desc")
.first()
.catch(console.log);
```
=> add clearOrder method fix #2360

src/dialects/oracledb/query/compiler.js, test/unit/query/builder.js
Returning clause for oracledb client does not support custom wrapper, this PR add a support for that by calling `this.formatter.wrap`
- utilize `this.formatter.wrap` for every columnName in returningClause
=> GH-2550 Add support to wrap returning column

src/dialects/mysql/schema/columncompiler.js, test/unit/schema/mysql.js
This changes the `timestamp()` and `timestamps()` schema building methods to output columns that have millisecond precision on MySQL versions 5.6 and newer.
This feature is not enabled by default for now and requires passing a `version: '5.6'` option when initializing the client to enable. The version number should be your actual MySQL server version, although as long as it is 5.6 or greater the feature will be enabled. The version number can be in the form `5.6` or `5.6.10`.
Fixes #2524.
Associated documentation update: https://github.com/knex/documentation/pull/99
=>  Create timestamp columns with millisecond precision on MySQL 5.6 and newer

src/migrate/index.js
In reference to #2534, the single line change has been run with tests against `DB='mysql' npm test`.
```
total:     84
passing:   84
duration:  1.6s
```
[testIssue2534.txt](https://github.com/tgriesser/knex/files/1907638/testIssue2534.txt)
=> Primary Key for Migration Lock Table

src/interface.js, src/query/builder.js, src/raw.js, src/schema/builder.js, src/util/save-async-stack.js, test/integration/builder/additional.js, test/unit/interface.js, test/unit/util/save-async-stack.js
slightly nasty way of getting better error stacks when using async/await.
Toggles on by setting a new config parameter called: `asyncStackTraces` to true
=> fix for #2500

src/client.js
Tarn's `destroy()` method doesn't return a bluebird promise, which means knex's `destroy()` method currently does not return a bluebird promise.  With this change, it should again :)
=> Ensure knex.destroy() returns a bluebird promise

src/util/parse-connection.js, test/tape/parse-connection.js
Postgres supports 2 uri connection protocols:
> The URI scheme designator can be either postgresql:// or postgres://.
https://www.postgresql.org/docs/current/static/libpq-connect.html#id-1.7.3.8.3.6
=> Support postgresql connection uri protocol

src/dialects/postgres/schema/columncompiler.js, src/schema/columncompiler.js, src/schema/compiler.js, src/schema/helpers.js, src/schema/tablecompiler.js, test/integration/schema/index.js, test/unit/schema/postgres.js
This is my initial pass at implementing native enum support for **Postgres only.** 
I am looking for feedback on the implementation and whether or not this is the _best_ way to solve this.
I followed the advice of [this comment](https://github.com/tgriesser/knex/issues/394#issuecomment-315528899) and added the following argument to the `enu` method:
```js
{
nativeEnum: boolean,
enumName: string
}
```
If `nativeEnum` is truthy, I use the `enumName` to generate the appropriate `type`. I am not sure if having two fields is entirely necessary (I could check `enumName` alone and use that) but I am not sure of the behavior for other RDBMS's.
Reference https://www.postgresql.org/docs/current/static/sql-createtype.html
Documentation: https://github.com/knex/documentation/pull/117
Closes #394
=> Add support for native enums on Postgres

src/dialects/postgres/index.js, test/integration/builder/additional.js
This PR fixes the issue #2630 for postgres
=> fixes 2630

src/transaction.js
but rather reject with original error. Fixes #2582
=> Timeout errors shouldn't silently ignore the passed errors

package.json, scripts/stress-test/docker-compose.yml, scripts/stress-test/knex-stress-test.js, src/dialects/mssql/index.js
Since mssql driver has not been maintained, locked driver version and monkey patched it to fix couple of problems of leaking connections / hanging and crashing when connections are closed unexpectedly.
We should eventually change mssql dialect to use directly tedious driver.
I did run this stress test script overnight and it didn't crash and memory consumption didn't grow either (it was stable between 150MB - 400MB)
=> Fix mssql driver crashing

package.json
This is a minor quibble, but I noticed that `npm docs knex` was opening the github repo instead of the knex documentation.
This adds the homepage field to package.json so that `npm docs` will automatically open the knex docs in a browser. This will also add the site URL to https://www.npmjs.com/package/knex.
=> add homepage field to package.json

src/dialects/maria/index.js, src/dialects/mysql/index.js, src/dialects/oracle/index.js, src/dialects/postgres/index.js, src/runner.js, test/integration/builder/selects.js
It should fix #2109 and a case when there is an error running the query.
=> Make the stream catch errors in the query

.travis.yml, package.json, scripts/stress-test/knex-stress-test.js, scripts/wait-for-mssql-server.js, src/dialects/mssql/index.js, src/dialects/mssql/query/compiler.js, src/dialects/mssql/schema/columncompiler.js, src/dialects/mssql/schema/tablecompiler.js, src/dialects/mssql/transaction.js, src/migrate/index.js, test/integration/builder/additional.js, test/integration/builder/aggregate.js, test/integration/builder/deletes.js, test/integration/builder/inserts.js, test/integration/builder/joins.js, test/integration/builder/selects.js, test/integration/builder/transaction.js, test/integration/builder/updates.js, test/integration/migrate/index.js, test/integration/migrate/test/20131019235306_migration_2.js, test/integration/migrate/test_with_invalid/20131019235306_migration_2.js, test/integration/schema/index.js, test/tape/crossdb-compatibility.js, test/tape/index.js, test/tape/invalid-db-setup.js, test/unit/query/builder.js, test/unit/schema/mssql.js
* Fix unique constraint to work the same way with other dialects
* Fix float type to be float instead of decimal
* Fix passing poolsettings to mssql internal pool
* Prevent rolling back transaction with undefined
Also fixed various tests where postres dialect hadn't actually been tested at all.
=> Various fixes to mssql dialect

src/dialects/mssql/schema/compiler.js, test/integration/schema/index.js, test/unit/schema/mssql.js
- implement schema support in tablecompiler
- add unit tests for hasTable, hasColumn and renameTable
Fixes the mssql part of #2591
=> Implement missing schema support for mssql dialect

src/query/builder.js, test/unit/query/builder.js
Relates to #2607.
Previously the joinbuilder would preemptively append the main builder's schema name from `.withSchema` to a subquery, which is invalid sql syntax. This change simply does not pass the schemaname to the `JoinClause` when subject is a `Builder`.
=> Fix join using builder withSchema.

src/dialects/mssql/schema/columncompiler.js, test/integration/schema/index.js, test/unit/schema/mssql.js
Datetime2 is now the recommended column type for new date work: https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-2017
=> Use Datetime2 for MSSQL datetime + timestamp types

src/dialects/mssql/schema/columncompiler.js, test/unit/schema/mssql.js
The SQL Server supports the following date / time data types:
date (Transact-SQL)
datetime (Transact-SQL)
datetime2 (Transact-SQL)
datetimeoffset (Transact-SQL)
smalldatetime (Transact-SQL)
time (Transact-SQL)
In my opinion, timestamp can be represented by (datetime, datetime2, datetimeoffset and smalldatetime).
Regarding the docs and integration tests, I want to wait for the reply about the incompatibility between dialects on the parameter for timestamp function on schema builder.
=> Allow timestamp with timezone on mssql databases

package.json, src/migrate/Migrator.js, src/migrate/migration-list-resolver.js, src/migrate/sources/fs-migrations.js, test/integration/migrate/index.js, test/integration/migrate/memory-migrations.js, test/tape/migrate.js, test/unit/migrate/migration-list-resolver.js
This would allow a webpack migration source which is compatible with bundling. As an example:
``` typescript
const migrationConfig = config || {
directory: path.resolve(__dirname, 'migrations'),
migrationSource: new WebpackMigrationSource(require.context('./migrations', false)),
}
class WebpackMigrationSource {
constructor(private migrationContext: __WebpackModuleApi.RequireContext) {}
/**
* Gets the migration names
* @returns Promise<string[]>
*/
getMigrations() {
return Promise.resolve(this.migrationContext.keys())
}
getMigration(name: string) {
return this.migrationContext(name)
}
}
```
I can now use webpack and bundle my database migration project.
=> Introduced abstraction for getting migrations

.editorconfig, src/migrate/MigrationGenerator.js, src/migrate/Migrator.js
This actually builds on top of my other PR, but didn't want to do this refactor in that PR.
Seeing as Migrator is no longer tied to the filesystem, I thought I would pull the make() function and all supporting helpers into it's own class. Will make it easier to ensure no fs related dependencies sneak back into Migrator.
This is just an idea, happy for it to be closed if you folks don't think it's a good idea :) It's just the last commit which is new in addition to the last PR - https://github.com/tgriesser/knex/pull/2786/commits/76ebc1e458b726f8ec9a67194cd1f0d8fb7fd757
=> Separate migration generator

src/dialects/sqlite3/schema/columncompiler.js, test/unit/schema/sqlite3.js
=> Add json type support for SQLite

src/migrate/stub/ts.stub
add typings on typescript migration stub
=> Typescript migration stub 

CHANGELOG.md, src/dialects/postgres/query/compiler.js, src/query/builder.js, test/integration/builder/selects.js, test/unit/query/builder.js
This implements optional table names to select locks that get applied in `SELECT … FOR UPDATE` and `SELECT … FOR SHARE` queries for PostgreSQL dialect. See #2834 for details and rationale.
=> Allow table names with forUpdate/forShare (tgriesser/knex#2834)

src/query/builder.js, src/query/compiler.js, test/unit/query/builder.js
Relates to #269 
Changes include:
- Chainable `.increment`, `.decrement`, `.update` in the same build-chain
- Can call `.increment` / `.decrement` on same column multiple times
- Uses reduce for final query value
- Object syntax for `.increment` / `.decrement`
- ~Generates queries with `"column" + ?` only~ Reverted!
- Added `.clearCounters()` to clear previous `.increment` / `.decrement` calls in a build chain
- If `.increment` / `.decrement` is called for a column that has already been specified in `.update` then value specified in `.update` will take presedence.
See tests for examples.
May have missed something or completely misinterpreted the issue, in which case please let me know.
=> Allow chaining of increment, decrement, and update

src/client.js, test/unit/knex.js
A couple of things - 
- The test relies on the `oracle` module not being in devDependencies. It will fail if it is ever added.
- I added the test to `test/unit/knex.js`, but I don't think the tests in this file are being run. I can't see the output for any of the tests in this file.
=> Throw instead of process.exit when client module missing

types/knex.d.ts
This is a followup to #2835 that became necessary with the merge of #2845. It adjust the typing of `forUpdate()` and `forShare()` to support the new call variants with table names.
It makes it possible to call `forUpdate()` and `forShare()` in either of the following three ways:
- `forUpdate()`
- `forUpdate('lorem', 'ipsum')`
- `forUpdate(['lorem', 'ipsum'])`
=> Adjust typing for forUpdate()/forShare() variant with table names

test/integration/builder/selects.js
Looks like original issue was only with Maria dialect which we no longer support. This adds test from https://github.com/tgriesser/knex/pull/1308/ to make sure that other dialects don't have same problem.
fixes #1276
=> Add test for retrieving null dates

src/query/builder.js, src/query/compiler.js, src/query/methods.js, test/unit/query/builder.js
Closes  #1755, an alternative to #2218
I needed `WITH RECURSIVE` in a project recently so I monkey patched this in and it works great 👌, figured I'd help out the upstream.
I noticed the other PR tried to handle the `UNION ALL` automatically for the recursive section, but in my case I actually wanted just a `UNION`. I think simply having this method add the `RECURSIVE` keyword is the way to go since it's trivial to do the `.union(...)` or `.unionAll(...)` or whatever one needs in the query section of the `.withRecursive()` method.
Future improvements might include a `raw` version, but I think getting this added in its simplest form is an easy win.
=> Add withRecursive()

src/query/builder.js, test/unit/query/builder.js, types/knex.d.ts
=> support multiple columns in `.orderBy()`

src/dialects/postgres/schema/columncompiler.js, test/integration/schema/index.js, test/unit/schema/postgres.js
I was super happy to see knex supporting native enums in postgres, but when I had an enum that I used repeatedly across different columns in different tables, I was running into errors as the `enum` method created the type enum for you each time. The type would already exist so it would error. I only wanted to create the type once, afterwards I just wanted to use that enum.
Could we add a flag in the options param to not run the sql that creates the type enum?
The first time you run it you could do
```
table.enu('current_mood', ['sad', 'ok', 'happy'], { useNative: true, enumName: 'mood' })
```
And then the other times you can run
```
table.enu('mood', ['sad', 'ok', 'happy'], { useNative: true, enumName: 'mood', existingType: true })
```
=> Add option of existingType to .enum method to support repeated use of enums

src/dialects/mysql/schema/tablecompiler.js, test/unit/schema/mysql.js
I followed the [MySQL Reference](https://dev.mysql.com/doc/refman/8.0/en/create-index.html).
```sql
CREATE [UNIQUE | FULLTEXT | SPATIAL] INDEX index_name
[index_type]
ON tbl_name (key_part,...)
[index_option]
[algorithm_option | lock_option] ...
key_part: {col_name [(length)] | (expr)} [ASC | DESC]
index_option:
KEY_BLOCK_SIZE [=] value
| index_type
| WITH PARSER parser_name
| COMMENT 'string'
| {VISIBLE | INVISIBLE}
index_type:
USING {BTREE | HASH}
algorithm_option:
ALGORITHM [=] {DEFAULT | INPLACE | COPY}
lock_option:
LOCK [=] {DEFAULT | NONE | SHARED | EXCLUSIVE}
```
No changes are required in `types/knex.d.ts`.
I'm not sure if I need to write tests for this, I could not find where the MySQL schema tests are written.
Steps to reproduce:
1. Add my fork as dependency in package.json: …
=> Added option to pass indexType for MySQL dialect

src/migrate/Migrator.js, src/migrate/table-creator.js, src/util/make-knex.js, test/integration/builder/additional.js, test/unit/knex.js, test/unit/migrate/Migrator.js, test/unit/migrate/migrations/blank_migration.js, test/unit/schema/postgres.js
fixes #2644
Also fixes .withUserParams() method to work correctly with .queryBuilder()
=> Do not postprocess internal queries in Migrator

src/dialects/oracledb/query/compiler.js, test/integration/builder/unions.js, test/integration/migrate/index.js
Fixes for GH-2915
- fixes union failing tests
- increment() and decrement() empty query issue
=>  GH-2915 Oracledb tests are failing

src/dialects/redshift/schema/columnbuilder.js, src/ref.js
'use strict' and import/export are not meant to be together.
=> remove useless 'use strict'

UPGRADING.md, src/dialects/mysql/schema/columncompiler.js, src/dialects/postgres/schema/columncompiler.js, test/unit/schema/mysql.js, test/unit/schema/postgres.js
fixes #2916 
Also I've noticed that PG also supports precision, and there was no good reason not to add it :)
=> Align signature for PG datetime and timestamp methods with docs

knex.js, package.json, test/unit/knex.js
fixes #2942 
This makes behavior consistent with Knex before 0.16.x
=> Do not reset prior Promise overrides on knex import

package.json
This fixes #2948 by including `@types/bluebird` as dependency of Knex.
We must use `dependencies` rather than `devDependencies` so that `@types/bluebird` gets installed when `knex` is added as regular dependency of another project, and not just when developing Knex itself—since the type definitions are exported as-is.
=> Include @types/bluebird as dependency

src/migrate/Migrator.js, test/integration/migrate/index.js, types/knex.d.ts
Extra parameter allows all migrations to be rolled back.
Addresses https://github.com/tgriesser/knex/issues/2844
=> Implemented extra boolean param for rollback()

src/migrate/Migrator.js
Upgrading from `^0.15.2` -> `^0.16.3` caused the `"loadExtensions"` option to no longer be respected. I think this is the cause, I'm not particularly familiar with the codebase.
=> Respect "loadExtensions" configuration

bin/cli.js, test/jake-util/helpers/migration-test-helper.js, test/jake-util/seeds-knexfile.js, test/jake-util/seeds/first.js, test/jake-util/seeds/second.js, test/jake/jakelib/migrate-test.js, test/jake/jakelib/seed-test.js
The following CLI commands get a `--verbose` option, which is used to determine whether to output the resulting log from the command action:
- `migrate:latest`
- `migrate:rollback`
- `seed:run`
=> Add verbose option to CLI commands

types/knex.d.ts
This PR resolves Issue https://github.com/tgriesser/knex/issues/2970
It adds a typescript definition in the types file to expose the toNative functionality available in Knex
https://knexjs.org/#Interfaces-toSQL
=> Issue 2970: Add toNative() definition in typescript

types/knex.d.ts
In Knex version 0.16.2,
we are using Knex.js with Typescript + callback style code.
As I upgrade Knex version 0.15.0 -> 0.16.2, now it cannot be compiled typescript files anymore because of no type definition for `.asCallback()`.
Therefore, I added `.asCallback()` type definition in `ChainableInterface`
=> Typescript type definition for `.asCallback()`

types/knex.d.ts
Add `constraintName` optional argument to `TableBuilder.primary()` TypeScript definition.
Currently, if you give the second argument, TS will tell that `primary()` expects only 1 argument, when in fact it supports the second optional argument to define the constraint name into the database.
=> Add "constraintName" arg to TS definition

types/knex.d.ts
add a schemaName value to MigratorConfig.
=> schemaName is missing in MigratorConfig typings

src/migrate/sources/fs-migrations.js
`fs` does not exist in the browser, causing errors such as: 
```javascript
Uncaught TypeError: expecting a function but got [object Undefined]
at Function.t.promisify (bluebird.js:4020)
at Object.<anonymous> (fs-migrations.js:18)
at Object.<anonymous> (fs-migrations.js:83)
at n (bootstrap:19)
at Object.<anonymous> (Migrator.js:21)
at n (bootstrap:19)
at Object.<anonymous> (make-knex.js:10)
at n (bootstrap:19)
at Object.<anonymous> (transaction.js:14)
at n (bootstrap:19)
at Object.<anonymous> (client.js:18)
at n (bootstrap:19)
at Object.<anonymous> (knex.js:10)
at n (bootstrap:19)
at Object.<anonymous> (index.js:8)
at n (bootstrap:19)
```
Currently this blocks examples in docs and also viewing full changelog.
=> Fix fs-migrations breaking docs

src/dialects/mysql/query/compiler.js, test/unit/query/builder.js
In SQLite3, users can be warned that `.returning()` has no effect.
https://github.com/tgriesser/knex/blob/master/src/dialects/sqlite3/query/compiler.js#L18
For consistency, how about MySQL users to be warned as well?
=> mysql warn `.returning()` does not have any effect.

src/query/builder.js, src/query/methods.js, test/integration/builder/unions.js, test/unit/query/builder.js, types/knex.d.ts
Addresses #2064
I needed `INTERSECT` for one of my projects so I used the existing `UNION` as a model, since they are extremely similar. Thanks for the great library!
=> add intersect()

types/knex.d.ts
Reimplemented from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29946
Looks like this was lost when the typings were transferred to the repo.
=> Update enum arguments to reflect latest signature

types/knex.d.ts
Size parameter work when we pass it. But it's not in definition.
=> Add size parameter to integer method

src/migrate/stub/ts.stub, src/seed/stub/ts.stub
Small refactor to the TS stubs, so they will use arrow functions and es6 import / export.
=> Make TS stubs modern

test/unit/query/builder.js
According to https://github.com/tgriesser/knex/pull/2908,
clearing offset is valid case for Knex.js, but there's no test for it.
=> add test that clearing offset

package.json, src/migrate/migration-list-resolver.js, test/unit/migrate/migration-list-resolver.js
As described in issue #2998, it seems that what we've found as a symptom (TypeScript migrations not working) is caused by the underlying `#listAllAndCompleted` function which doesn't properly relay the `config.loadExtensions` to `#listAll`.
With the little change in that PR things seem back to normal and the tests all pass as before.
Note: as this problem wasn't caught by the automated tests, eventually, the test suites should be augmented.
=> Fix for #2998 - Migrator & TypeScript

types/knex.d.ts
Hopefully I got it right this time!
Allowing Knex() to accept string type as it does accept string configuration parameter: https://github.com/tgriesser/knex/blob/master/src/knex.js#L12
=> Include 'string' as accepted Knex constructor type definition

src/migrate/Migrator.js, src/transaction.js, src/util/make-knex.js, test/unit/knex.js, test/unit/migrate/Migrator.js
=> Fix transaction support for migrations

src/formatter.js, test/unit/knex.js
=> Fix queryContext not being passed to raw queries

src/query/builder.js, test/unit/query/builder.js, types/knex.d.ts
Consolidates the logic used by union() and unionAll(), allowing the two to be used interchangeably (which is the current behavior claimed by the docs).
This allows `.unionAll()` to be called on multiple subqueries (rather than having to repeatedly call `.unionAll()` for each one).
Additionally, this adds test-coverage for the undocumented `wrap` argument on `.unionAll()` (which  is already documented for `.union()`).
---
This was the only allowable call-signature (apart from a second undocumented `wrap` parameter):
```js
qb.unionAll(subQuery);
```
If I wanted to write the `.unionAll()` equivalent of `qb.union([sq1, sq2])`, I would have needed to write something like:
```js
[s1, sq2].reduce((qb, sq) => qb.unionAll(sq), qb);
```
Any valid call to `.union()` should now work with …
=> make unionAll()'s call signature match union()

types/knex.d.ts
=> Add boolean as a column name in join

bin/cli.js
Hi there,
A really small PR to add error details when using cli, instead of only having a stack trace, which makes it really hard to know where the issue is when seeding (e.g. `error: null value in column "date" violates not-null constraint`).
LMKWYT,
Cheers.
=> Add error detail log to cli.js

types/knex.d.ts
I'm still relatively new to TypeScript but these types seem to be missing compared to the docs ❤️
=> add missing types to MigratorConfig

bin/cli.js, test/jake/jakelib/migrate-test.js
This pull request adds support for rolling back all completed migrations to the CLI.
This would, in part, address the feature requests in the following issues: https://github.com/tgriesser/knex/issues/783 and https://github.com/tgriesser/knex/issues/2907
I've labeled this still a work in progress because I'm having difficulty getting the test to work the way I want. Perhaps that's me just not understanding how the testing is set up but here's what I'm trying to accomplish:
1. Create migration 001
1. Run `migration:latest`
1. Create migration 002
1. Run `migration:latest`
1. Create migration 003
1. Run the cli for `migrate:rollback --all` to ensure that migrations 002 and 001 were run in that order and it did not run 003.
The problem is that it only runs the first migration (i.e. migration …
=> WIP: Feature/add rollback all to cli

types/index.d.ts, types/test.ts
Changes in https://github.com/tgriesser/knex/pull/3168 introduces  backward incompatibility causing some other type definitions on DefinitivelyTyped to break when used with latest Knex. 
This PR (tested with all the external type definitions in DefinitivelyTyped having knex as dependency) addresses them by: 
- Adding defaults for parameters of all exposed types which are now generic
- Allowing query builders to be used as select arguments (to accomodate as usage).
=> Fix backward-incompatibility in type definitions

types/index.d.ts, types/test.ts
=> [WIP] Resolve type incompatibilities wrt. current usage patterns

types/index.d.ts, types/test.ts
- **Fix:** update, insert, delete didn't support deferring of result resolution unlike select.
So `knex.insert(...).into<User>('users')` would fall back to any
- **Fix:** Incorrect handling of cases when deferred selection keys get cleared later eg. multiple returning invocations, clearSelect.
- **Fix:** first resolves to array member rather than array.
- **Add:** explanations for the intent behind some of the non-trivial type applications.
=> Resolve more issues around generic typings

types/index.d.ts, types/test.ts, types/tsconfig.json, types/tslint.json
- Joins would result in previous result type to not be propagated through the fluent chain in non-inferrable scenarios. This fixes https://github.com/tgriesser/knex/pull/3168#issuecomment-493671389. 
- Removed unnecessary generics from with* functions and added tests.
- Fixed incompatibility with `esModuleInterop: true`. Bluebird typings use `export =` and thus we need to be import through `import =` to be compatible to both modes. This fixes https://github.com/tgriesser/knex/pull/3168#issuecomment-493661498 and https://github.com/tgriesser/knex/issues/3210
=> Fix issues with typings of joins and some conflicts with Bluebird

types/index.d.ts
Ref: https://github.com/tgriesser/knex/pull/3036#issuecomment-493751631
=> Expose some utility types

bin/cli.js, bin/utils/cli-config-utils.js, bin/utils/constants.js, test/jake/jakelib/migrate-test.js
I am using Knex to migrate several projects from MongoDB to PostgreSQL. Since these projects already have a means of storing connection configuration, the `knexfile` is redundant. Instead, I can read my existing configuration and generate the appropriate Knex migration command dynamically. 
However, because my projects share the same PostgreSQL database, I need to namespace their migration histories so that they don't conflict. In order to do that, I need to be able to specify the `tableName` configuration option via the command line, which this PR introduces support for.
=> Allow users to specify the migrations "tableName" parameter via the CLI.

src/dialects/sqlite3/formatter.js, src/dialects/sqlite3/index.js, test/integration/builder/selects.js, test/unit/query/builder.js
=> Support multi-column whereIn in sqlite through values clause

types/index.d.ts, types/test.ts
- Add types for Seed API
- Add Knex#initialize (Closes #3192)
- Mark Knex interface as EventEmitter (because it does support the full EventEmitter API) 
- Provide more control over TResult for insert/update for cases where the return type of some intermediate mutating functions was left unused.
- Relax constraints on raw queries and add tests for mixed bindings
=> Fix some more cases of missing typings

types/index.d.ts, types/test.ts
=> Update Knex.Config types to include log

types/index.d.ts, types/test.ts
- Make count generic, especially useful when being used with an alias object argument
- In case of alias object, partially infer the return type from the input.
Addresses: https://github.com/tgriesser/knex/issues/3229#issuecomment-497866524
=> Improve count typings

src/seed/Seeder.js, test/unit/seed/seeder.js, test/unit/seed/test/1-first.js, test/unit/seed/test/2-second.js
Problem: When the nth seed `throw`s an error, all subsequent seeds add an error message on top of original message which makes it less clear which seed the error originated from.
Solution: Nest promises and `catch` error inside the nested seed promise.
Before:
```
Error: Error while executing ".../knex/seeds/9-titres-activites.js" seed: Error while executing ".../knex/seeds/8-metas-activites.js" seed: Error while e
xecuting ".../knex/seeds/7-titres.js" seed: insert into "titres_points" ("contour", "coordonnees", "description", "groupe", "id", "nom", "point"
at Object.current.then.then.catch.originalError (.../node_modules/knex/lib/seed/Seeder.js:166:23)
Error: Error while executing ".../knex/seeds/8-metas-activites.js" seed: Error while executing ".../knex/seeds/7-titres.js" seed: insert …
```
=> Fix error message bubbling up on seed error

types/index.d.ts, types/result.d.ts, types/test.ts, types/tslint.json
Fixes: https://github.com/tgriesser/knex/issues/3247
=> Address concerns around count typings

scripts/build.js, src/client.js, src/dialects/mssql/transaction.js, src/dialects/mysql/schema/tablecompiler.js, src/dialects/oracle/transaction.js, src/dialects/oracledb/transaction.js, src/migrate/Migrator.js, src/transaction.js, types/index.d.ts
Still waiting on oracle docker 🙄 but think this is ok...
Should resolve #3253
=> Remove Bluebird.try

UPGRADING.md, package.json, src/dialects/mysql/schema/tablecompiler.js, src/knex.js, src/migrate/Migrator.js, src/migrate/stub/coffee.stub, src/migrate/stub/eg.stub, src/migrate/stub/js.stub, src/seed/Seeder.js, src/seed/stub/coffee.stub, src/seed/stub/eg.stub, src/seed/stub/js.stub, src/seed/stub/ls.stub, src/util/make-knex.js, types/index.d.ts, types/test.ts
Remove bluebird promises from typings. Do not pass promise to migrations and seeds. Remove knex.Promise.
=> Bluebird removal: part I

types/index.d.ts, types/result.d.ts, types/test.ts, types/tslint.json
Ref: https://github.com/tgriesser/knex/pull/3249#issuecomment-499250764
=> Backport typings related changes to 0.17

bin/utils/cli-config-utils.js, package.json, src/migrate/MigrationGenerator.js, test/cli/migrate-make.spec.js, test/index.js
=> Try to resolve knexfile.ts when knexfile.js does not exist

package.json, types/index.d.ts
(not sure how to test with my setup)
=> Fix typescript issue described by #3116

src/client.js, src/dialects/mssql/transaction.js, src/dialects/mysql/transaction.js, src/dialects/mysql2/transaction.js, src/dialects/oracle/transaction.js, src/dialects/postgres/index.js, src/interface.js, src/migrate/Migrator.js, src/runner.js, src/transaction.js, test/integration/logger.js
fixes #3255
Alternative solution: implement a version of .tap in a Promise wrapper around the native Promise (or a providable A+ compliant library) instead of Bluebird.js was done with [src/promise.js](https://github.com/tgriesser/knex/blob/3846b7182ce0eba7a43237cc8e498e5391d33102/src/promise.js) previously.
I opted to always return the resolved promise value even in cases where it was not used in case it might be extended later in the promise chain.
=> refactor: replace usage of Bluebird Promise.tap with native Promise.then

src/dialects/mysql/schema/tablecompiler.js, src/dialects/sqlite3/schema/ddl.js, src/migrate/migrate-stub.js, src/runner.js, src/seed/Seeder.js, src/seed/seed-stub.js, test/integration/builder/additional.js
=> Remove Bluebird.method and one instance of .bind

types/index.d.ts
Is this excluded intentionally? For my projects, I share this type between knexfile and service level.
=> Adds stub type definition

types/index.d.ts
I created `PostgreSqlTableBuilder` and `PostgreSqlAlterTableBuilder` interfaces, similar to the existing MySQL counterparts `MySqlTableBuilder` and `MySqlAlterTableBuilder`. 
They include the currently missing [inherits()](https://knexjs.org/#Schema-inherits) method.
=> Add pgsql specific table builder method typings

types/index.d.ts
Looks like there was a missing type for `config.seeds.stub` used here: https://github.com/tgriesser/knex/blob/master/src/seed/Seeder.js#L102.
=> adds stub to seeds type

src/transaction.js, test/unit/knex.js, types/index.d.ts
Exposed both on callback and non-callback versions for consistency, even though it isn't very useful for callback ones (you always had access to promise for them).
=> Expose executionPromise for transactors

src/dialects/oracle/index.js, src/dialects/oracledb/index.js, src/migrate/Migrator.js, src/migrate/migration-list-resolver.js, src/query/methods.js, src/runner.js, src/schema/tablecompiler.js, src/seed/Seeder.js, src/transaction.js, src/util/make-knex.js
The find & replace of ES module import syntax to cjs `require`s in #3227 modified some comments.
=> Fix comments that were modified by a find & replace

bin/cli.js, test/cli/version.spec.js, test/index.js
Currently, `--version/-V` output looks broken (empty output):
```sh
knex --version
Knex CLI version: 
Local Knex version: 
```
#3311
=> CLI: Fix empty --version output

src/dialects/mssql/schema/columncompiler.js, src/dialects/mysql/schema/columncompiler.js, src/schema/columncompiler.js, test/integration/schema/index.js, test/unit/schema/postgres.js, test/unit/schema/redshift.js
This PR addresses following issues: 
1. SQL Server allows default values for BLOB/nvarchar but knex ignores defaults for these types. This PR removes that behavior.
2. Setting default value of JSON(B) fields don't work and results in invalid syntax for pretty much all dialects (unless knex.raw is explicitly used).
=> Fix issues around specifying default values for columns

src/transaction.js
An attempt to fix third reported issue from #3309.
Basically, if there is `initRejectFn` it means a transaction is used without a container, it means that `_promise` is not exposed, it means that if `_promise` is rejected there will be an unhandled rejection, it means that we should not reject that promise.
`initRejectFn` will do fine by itself. If an error happens before a transactor resolved (some problem with a connection) then it will reject `initPromise` which is returned for `knex.transaction()` so it is exposed and handled easily. If an error happens after a transactor resolved, it means that `initPromise` is already resolved (with said transactor) and calling `initRejectFn` will do nothing, but it is ok since only way to get here is from `executionPromise` rejection and it is …
=> Fix remove duplicate transaction rejection

src/transaction.js, src/util/make-knex.js, test/integration/builder/transaction.js, test/unit/knex.js
So it seems like #3319 was a mistake and having a duplicate is needed because original execution promise does have `catch` [attached](https://github.com/tgriesser/knex/blob/4cde0fcb84071989811cfe1c17d001f1230a7b29/src/transaction.js#L106) so it will never produce unhandled rejections. So if you do not attach `catch` to `executionPromise` nobody will tell you that your transaction queries are failing (except this [debug statement](https://github.com/tgriesser/knex/blob/4cde0fcb84071989811cfe1c17d001f1230a7b29/src/transaction.js#L172)).
Solution: promise duplication but only for standalone transactions.
=> Fix return duplicate transaction promise for standalone transactions

package.json
Fixes: https://github.com/knex/documentation/issues/212
=> Fix mssql import not being ignored due to change in browser field in package.json

bin/cli.js, src/seed/Seeder.js, test/integration/seed/index.js, test/jake/jakelib/seed-test.js
This features allows to run a specific seed file.
It adds an additional cli property `--specific=filename.js` which points to some seed file in the seed directory.
usage: `npx knex seed:run --specific=seed-filename.js`
=> feat: Run specific seed file (closes #801)

bin/cli.js, test/cli/cli-test-utils.js, test/cli/migrate-make.spec.js, test/jake-util/knexfile-stubs/knexfile.js, test/jake-util/knexfile-stubs/table.stub
=> fix: Respect the knexfile stub option while generating a migration

lib/dialects/mssql/query/compiler.js, lib/query/builder.js, lib/query/compiler.js, test/integration/builder/aggregate.js
- Allows an options object to specify alias (as suggested in https://github.com/tgriesser/knex/issues/3315#issuecomment-507439215) (Closes #3315)
- Allows multiple aliases when using object syntax (Closes #2871)
=> Minor enhancements around aliasing of aggregates

types/index.d.ts
I am working on a typescript project with an oracle database using SID and we currently have it configured with a custom connectString. We were hoping to move to knex and ran into a typescript issue. Here is the resolution we used to get it working.
=> Update configuration typings to allow for oracle db connectionstring

lib/transaction.js, test/unit/knex.js, types/index.d.ts
Adds .isCompleted() to a transactor, which just calls the underlying .isCompleted() from the transaction. I needed it because in my application, I pass a transaction around as part of a request and as a safeguard, I am rolling back the transaction. However, sometimes the transaction is already complete. This just harmlessly exposes whether I am allowed to commit/rollback or not.
=> Add .isCompleted() to transaction

test/integration/builder/selects.js
This fixes one of the tests from #2961 that got broken recently, and throws a very minor refactoring of the skipLocked tests to make them a little bit cleaner.
I had to re-write most of the test to use try/catch to have it resolve properly (otherwise the catch handler wouldn't fully handle the error when using await), but after doing so, it also seems the test is easier to read this way.
I also made the involved tests clear the related rows before starting, as I was getting test failures after running them multiple times because they were designed with only a single run in mind (oops).
=> Fix broken noWait test

lib/dialects/mysql/transaction.js, lib/dialects/mysql2/transaction.js, test/tape/transactions.js
Making `mysql` and `mysql2` dialects use the same `sql` check as the base transaction class.
=> fix: make transaction rejection consistent across dialects

types/index.d.ts
Augment the `defaultTo` method's type to allow `null` which is required when setting a column's default to be `null` with TypeScript's strict mode enabled.
=> #3405 Allow `ColumnBuilder.defaultTo()` to be `null`

package.json
- Upgrade pg-connection-string to 2.1.0
Fixes #852
=> Add SSL/TLS support for Postgres connection string

lib/dialects/postgres/schema/columncompiler.js, test/integration/schema/index.js, test/unit/schema/postgres.js
```javascript
knex
.schemaBuilder()
.withSchema('test')
.table('users', function(table) {
table
.enu('foo', ['bar', 'baz'], {
useNative: true,
enumName: 'foo_bar',
})
})
.toSQL();
```
```sql
-- ...
create type "foo_bar" as enum ('bar', 'baz');
alter table "test"."users" add column "foo" "foo_bar";
-- ...
```
Schema builder doesn't take into account `withSchema` expression and always creates a type in `public` schema.
- `options.schema = '<schema name>'` - use specified schema name;
- `options.schema = true` -  use schema from `withSchema` expression (for backward compatibility if needed);
```javascript
knex
.schemaBuilder()
.withSchema('test')
.table('users', function(table) {
table
.enu('foo', ['bar', 'baz'], {
useNative: true,
enumName: 'foo_bar',
schema: 'test_2',
})
})
.toSQL();
``` …
=> Fix native enum with specified schema (#3307)

lib/dialects/postgres/schema/columncompiler.js, test/unit/schema/postgres.js
There is no way to define schema manually, the schema name from withSchema will be always prepended to enumName.
```javascript
knex
.schemaBuilder()
.withSchema('test')
.table('users', function(table) {
table
.enu('foo', ['bar', 'baz'], {
useNative: true,
enumName: 'type_schema.foo_bar',
})
})
.toSQL();
```
```sql
-- ...
create type "test"."type_schema"."foo_bar" as enum ('bar', 'baz');
alter table "test"."users" add column "foo" "test"."type_schema"."foo_bar";
-- ...
```
If enumName includes a dot, then don't prepend the schema name from withSchema to enumName.
```javascript
knex
.schemaBuilder()
.withSchema('test')
.table('users', function(table) {
table
.enu('foo', ['bar', 'baz'], {
useNative: true,
existingType: true,
enumName: 'type_schema.foo_bar'
})
})
.toSQL();
```
```sql
-- ... …
```
=> add ability to manually define schema for enu with useNative (#3307)

types/index.d.ts
This is addition to https://github.com/tgriesser/knex/pull/3413
=> TypeScript definition: include schemaName in EnumOptions

lib/migrate/Migrator.js, test/integration/migrate/index.js
Since _isLocked is only called just before _lockMigrations, it is redundant
and we can accomplish the same  thing by checking the rowCount returned
by the update (verified by testing with postgres, mysql, sqlite, and
mssql).
The benefit of this change is improving compatbility with CockroachDB,
which does not support FOR UPDATE.
Updates #2002
=> migrate: Refactor _lockMigrations to avoid forUpdate

lib/helpers.js, lib/query/compiler.js, lib/raw.js, test/unit/query/builder.js
=> feat: add undefined columns to undefined binding(s) error

lib/transaction.js, test/integration/builder/transaction.js
Fix for https://github.com/tgriesser/knex/issues/2213 where @joepie91 already did the bulk of the work and investigation. I needed this fixed for a personal project so adapted their test and reimplemented the check for `_previousSibling`.
=> Fix for concurrent child transactions failing (#2213)

types/index.d.ts
The list method is missing in the Migrator interface - this PR adds it.
=> Add missing Migrator.list typing

bin/cli.js, lib/migrate/Migrator.js, test/integration/migrate/index.js, test/jake/jakelib/migrate-test.js
Add the ability to explicitly define the migration's filename for `up` and `down` commands (#1550).
Run only the next migration:
```bash
migrate:up
```
Undo only the latest migration:
```bash
migrate:down
```
Add the optional `name` parameter for `up` and `down` commands.
Run only the specified or the next migration:
```bash
knex migrate:up <name>
```
Undo only the specified or the latest migration:
```bash
knex migrate:down <name>
```
Let's say we have two new migrations:
```
001_one.js
002_two.js
```
If we want to run only the `002_two.js` then we can use this:
```bash
knex migrate:up 002_two.js
```
Let's say we have two completed migrations:
```
001_one.js
002_two.js
```
If we want to revert only the `001_one.js` then we can use this:
```bash
knex migrate:down 001_one.js
```
=> Migrations up/down commands: filename parameter

test/integration/migrate/index.js
#3286 
Only test codes are modified
=> remove Bluebird.map usage

lib/dialects/sqlite3/schema/ddl.js, test/integration/schema/index.js
1. Fix regex match failure when table has not been created through knex's createTable (Closes #3473)
2. Handle all quote variants supported by SQLite.
3. Fix incorrect handling of foreign keys & constraints
=> Fix bugs in replacement logic used when dropping columns in SQLite.

lib/dialects/oracledb/index.js, test/tape/transactions.js
closes https://github.com/tgriesser/knex/issues/3256
=> remove bluebird.each

bin/cli.js, bin/utils/cli-config-utils.js, lib/migrate/MigrationGenerator.js, lib/seed/Seeder.js, lib/util/template.js, test/cli/cli-test-utils.js, test/cli/migrate-make.spec.js, test/cli/seed-make.spec.js, test/index.js, test/jake-util/knexfile-stubs/knexfile.js, test/jake-util/knexfile-stubs/seed.stub, test/jake-util/knexfile-ts/knexfile.ts, test/jake-util/knexfile/knexfile.js, test/jake-util/knexfile_seeds/seed2.stub
=> Fix some issues around seed and migration generation

types/index.d.ts, types/test.ts
The `seed.run` command returns a array of a single item, and that item contains the array of strings (filepaths of seeds that were run).
This comes from here: 
- https://github.com/tgriesser/knex/blob/master/lib/seed/Seeder.js#L37
- https://github.com/tgriesser/knex/blob/master/lib/seed/Seeder.js#L90
- https://github.com/tgriesser/knex/blob/master/lib/seed/Seeder.js#L162
=> Fixes types for Seeder#run

.travis.yml, lib/dialects/oracledb/index.js, test/unit/dialects/oracledb.js
Idk how to test different oracledb packages
also maybe need to add some tests?
=> impr(oracledb): 4 fix

bin/cli.js, lib/client.js, lib/migrate/MigrationGenerator.js, lib/migrate/sources/fs-migrations.js, lib/seed/Seeder.js, test/knexfile.js
fixes https://github.com/tgriesser/knex/issues/3257
=> Use util.promisify instead of Bluebird.promisify

types/index.d.ts
Add typings to the `list` and `forceFreeMigrationsLock` methods.
=> feat: Add types to the Migrator interface

lib/query/compiler.js, test/unit/query/builder.js, types/index.d.ts, types/test.ts
=> orderBy accepts QueryBuilder

lib/dialects/oracle/utils.js
Updated some of the incorrect Oracle codes (ORA-XXXXX) to correct values.
=> Fix Oracle error codes

lib/formatter.js, lib/query/compiler.js, test/integration/builder/selects.js, test/unit/query/builder.js
=> feat: wrap subQuery with parenthesis when it appears as table name

types/index.d.ts
- Update QueryInterface to proxy to only standard promise methods
- Update QueryInterface type to be explicit about the methods being
proxied
This primarily handles pollution of global Promise (either the type or
the global object at runtime) by other libraries.
Fixes: https://github.com/knex/knex/issues/3422#issuecomment-546930375
=> Gracefully handle global promise pollution

package.json
Fix #3059 
This is a simpler approach using optionalDependencies.
It's already supported by npm, and yarn --pnp is happy with it.
=> Declare drivers as optionalDependencies (Fix #3059)

types/index.d.ts, types/test.ts
Two changes in the typings file:
- Fixed the type of `log` method in PoolConfig interface
- Removed `create`, `destroy` and `validate` methods from PoolConfig interface, because Knex is overriding these methods, and any user provided implementations of these methods are being ignored. Having these methods in the typings file will only confuse users.
=> Fix typing file

lib/dialects/sqlite3/schema/compiler.js, test/integration/schema/index.js
This PR makes the sqlite3 `hasColumn` function case insensitive to respect sqlite3 convention.
Fix #3434.
It might some new tests ? let me know and I'll add the necessary ones.
=> Make sqlite3 hasColumn case insensitive

types/index.d.ts
This is not a change to behavior; it's just an update to the TypeScript types to reflect the actuality of what's in the codebase. Inspecting `lib/seed/Seeder.js` there are five unique references to `this.config.`, but only two were previously represented in the types.
I'm a big fan of generics and how they can help us write more explicit code but if you want to eliminate that for something more broad, like just `variables?: object` or `variables?: any` that's fine; I'm not using it.
I'm submitting this PR because I encountered the following issue:
`knexfile.ts` has the following:
```js
seeds: {
directory: './db/seeds',
stub: './db/seed.stub.ts',
}
```
Using the `.ts` stub file by way of `npx knex seed:make thing` generates a migration with a `.js` extension. Obviously that's not right. I …
=> Expand SeedsConfig types

lib/util/parse-connection.js, test/tape/parse-connection.js
Like mentioned in here https://github.com/knex/knex/issues/2354#issuecomment-555968462 this will allow query string params to be passed to driver used. It already works like this in other libraries, and seems like it be helpful for multiple cases.
Example in MySql https://github.com/mysqljs/mysql/blob/master/lib/ConnectionConfig.js#L186
=> Add connection string qs to connection params

lib/schema/tablebuilder.js, test/integration/schema/index.js, test/unit/schema/mssql.js, test/unit/schema/postgres.js, test/unit/schema/redshift.js, types/index.d.ts
Ref:
- https://github.com/knex/knex/issues/3478#issuecomment-546629137
- https://github.com/knex/knex/issues/3478#issuecomment-546631483
=> Lift up dialect specific methods in the CreateTableBuilder

lib/dialects/postgres/index.js
This pull request is to fix a bug that I have with knex on postgresql (knex version : `0.20.1`, node-pg version : `7.12.1`, postgresql database version : `11`
The bug is on the timeout feature of knex.
When I try to cancel a postgresql request (with the knex.timeout and the cancel option set to true) the request is correctly canceled but if I try to run a request just after the canceled one sometimes I have this error :
```
Error: Connection terminated unexpectedly
at Connection.con.once (xxx/node_modules/pg/lib/client.js:200:9)
at Object.onceWrapper (events.js:286:20)\n    at Connection.emit (events.js:198:13)
at Socket.<anonymous> (xxx/node_modules/pg/lib/connection.js:129:10)
at Socket.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback …
```
=> Knex .timeout(ms, {cancel: boolean}) use cancel instead of terminate for postgresql

lib/dialects/oracledb/index.js, test/unit/dialects/oracledb.js
A variable to hold the Stream data is initialized to a string.  In the case that the type of the stream is not "string", data is concat'ed to a Buffer, which fails.  This changes initializes data to a Buffer in case that it is not a string.
=> Initialize data to buffer instead of string for non-strings

bin/cli.js
by passing and extra property to liftoff. Without this change when using a namespaced knex like `@capaj/knex` CLI won't run
=> make sure CLI works for namespaced knex packages as well

types/index.d.ts, types/test.ts
The `only` option was missing from the type definitions.
So here is it.
=> Support 'only' option in type definitions

types/index.d.ts, types/test.ts
According to the docs, calling `queryContext` with no arguments returns the context object. (ref: https://knexjs.org/#Builder-queryContext)
This PR adds the relevant overload to the function definition for that use case.
=> Fix queryContext function defintion

lib/client.js
=> Fix debug logger messing up queries with %

types/index.d.ts
=> Fix QueryBuilder.extend this type (#3526)

CONTRIBUTING.md, README.md, package.json
This PR fixes some broken links, and since the project has moved, it guess it is better to change old location.
However, there are still some other references with the issues ID, but I am not sure if they also should be changed.
=> The project location has moved to knex/knex

lib/query/compiler.js, lib/raw.js
Running a program that uses knex with node --trace-sync-io results in
warnings such as this one:
(node:10232) WARNING: Detected use of sync API
at randomBytes (internal/crypto/random.js:54:31)
at nodeRNG ([...]/node_modules/uuid/lib/rng.js:7:17)
at v4 ([...]/node_modules/uuid/v4.js:13:52)
at toSQL ([...]/node_modules/knex/lib/query/compiler.js:73:28)
at toSQL ([...]/node_modules/knex/lib/query/builder.js:77:44)
at [...]/node_modules/knex/lib/runner.js:30:36
at [...]/node_modules/knex/lib/runner.js:253:24
at tryCatcher ([...]/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
at [...]/node_modules/knex/node_modules/bluebird/js/release/promise.js:547:31
uuid.v1() provides more than adequate collision guarantees, is 5 times
faster than uuid.v4() and most importantly do not …
=> Fix benign use of sync API (#3595)

lib/logger.js, types/index.d.ts
Resolves https://github.com/knex/knex/issues/3588
=> Fix colors in debug logs

lib/dialects/oracledb/transaction.js, test/unit/dialects/oracledb.js
I took the liberty to use async/await as the code is much cleaner. Let me know if you want a less drastic change. I confirmed this works correctly against a live oracle database.
=> fix #3605 not releasing connection from pool on disconnect

bin/cli.js
closes #3603 
Tweaked the code-base to make use of `commander.js` API that handles the scenario when no arguments were passed in.
=> fix(cli): prevent warning showing up with root command

README.md
The code sample in the README.md uses a deprecated config option. When using `dialect`, one gets the warning: "Using 'this.dialect' to identify the client is deprecated and support for it will be removed in the future. Please use configuration option 'client' instead."
=> Update deprecated `dialect` to `client` in code example

lib/query/string.js, test/index.js, test/unit/query/string.js
Looking at the [code coverage](https://coveralls.io/github/tgriesser/knex) I found some of the core utility functions were not fully covered - I've added tests for some string functions. 
**WIP - I will add few more tests into this PR as listed below.**
**Tests**
Add unit tests for string utility functions:
**Other Changes**
- Make `escapeObject` handle the case for an empty input - previously it would have thrown `TypeError: Cannot read property 'toSQL' of undefined`
=> (WIP) Add tests for some of the string utility functions 

lib/dialects/oracledb/index.js, test/unit/dialects/oracledb.js
=> dispose Oracle connection on connection error

bin/cli.js, package.json, test/cli/help.spec.js, test/index.js
knex cli should print help only when there are no arguments.
current implementation always prints help even when given correct arguments, such as `knex migrate:status`.
the correct way to check argument length is via process.argv.
reference: https://github.com/tj/commander.js/#outputhelpcb
=> Print help only when there are no arguments

bin/cli.js, package.json, test/jake-util/knexfile-esm/.eslintrc.json, test/jake-util/knexfile-esm/knexfile.js, test/jake-util/knexfile-esm/migrations/one.js, test/jake-util/knexfile-esm/seeds/one.js, test/jake/jakelib/migrate-test.js, test/jake/jakelib/seed-test.js
Enable esm interop behind a flag
Enable experimental, optional use
Minimum changes
Tests: migration/seeds/configuration
fix:  eslint error
=> #3751: Esm interop flag

types/index.d.ts
Config object for mssql: see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mssql/index.d.ts is outdated. in tedious https://github.com/tediousjs/tedious/blob/master/src/connection.ts line 154, enableArithAbort: null | boolean is required now.
=> Update index.d.ts, interface MsSqlConnectionConfig enableArithAbort: null | boolean is required now.

lib/client.js, lib/dialects/mysql/index.js, lib/dialects/oracledb/transaction.js, lib/knex.js, lib/runner.js, lib/transaction.js, lib/util/timeout.js, package.json, test/integration/builder/additional.js, test/integration/builder/transaction.js, test/tape/invalid-db-setup.js, types/index.d.ts
Breaking changes: TImeoutError now not extends Bluebird.TimeoutError
also this error exported explicitly
=> replace Bluebird.timeout

bin/cli.js, test/cli/knexfile-test.spec.js, test/jake-util/knexfile-relative/knexfile-with-resolve.js
Addresses the issue outlined here:
https://github.com/knex/knex/issues/3660
Short story: the Knex CLI was opening the Knexfile before calling `process.chdir(...)`.  Unfortunately, the Knexfile in question was resolving some paths relative to `process.cwd()`.  As a result, these paths ended up being relative to the wrong directory.
=> Fix: Knex CLI calls process.chdir() before opening Knexfile

types/index.d.ts
Reflect the type at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pg/index.d.ts
=> include SSL in postgres connection definition

types/index.d.ts
`fn.now` can optionally take a precision argument, so reflect that in the TypeScript definition.
=> `fn.now` takes optionally a precision argument.

lib/transaction.js
Minor cleanup to some of the Transaction logic.  However, it looks like this cleanup might have also inadvertently fixed the race condition that was being investigated here:
https://github.com/knex/knex/pull/3665
cc: @maximelkin + @kibertoad
=> Fix race condition in non-container transactions

lib/transaction.js, lib/util/make-knex.js
This extracts the "operational" logic related to container / non-container Transactions. Saying it another way: it means that the `Transaction` class no longer needs to be aware of "how" it was instantiated.
(Rebase of #3673 )
=> Cleanup and extract Transaction Workflow logic (rebase)

lib/dialects/oracledb/index.js, test/unit/dialects/oracledb.js
As released in [2.3.0](https://github.com/oracle/node-oracledb/blob/master/CHANGELOG.md#node-oracledb-v230-7-jun-2018) of node-oracledb, this adds handling to fetchAsString for the `BUFFER` type, allowing fetchAsString to interpret `RAW` fields.
=> Add OracleDB handling for buffer type in fetchAsString

test/integration/builder/additional.js, test/integration/builder/inserts.js, test/integration/builder/joins.js, test/integration/builder/selects.js, test/integration/datatype/bigint.js, test/integration/schema/index.js, test/tape/pool.js, test/unit/knex.js
Currently, the Knex codebase marks several tests as "passing" even though no test was actually run.  This is then giving us a false sense of how well the codebase has really been tested.  So, this is a quick pass over the code that marks several of these missing test cases as `"pending"` instead of `"passing"`.  From there, we can then decide upon an appropriate way to refactor each of these test cases.
=> Mark missing test cases as "pending" rather than "passed"

lib/util/timeout.js
As noted in #3699 , the `timeout(..)` function wasn't clearing the calls to `setTimeout(..)` once the wrapped Promise had completed.  As a result, this would cause programs to hang for a few seconds if they attempted to exit shortly after resolving a `timeout(..)`.
=> timeout(..) function clears unnecessary timeouts

.gitignore, test/.gitignore
Various testing artifacts get left on disk if you kill the tests while they're still running.  I updated the `.gitignore` files so that it would be less likely for these to get committed by accident.
=> Updated .gitignore files to ignore testing artifacts

test/index.js, test/integration/schema/index.js
Fortunately, these unhandled Promise rejections turned out to be in the test case code!  (Rather than being a deeper problem that had to be tracked down)
=> Fixed a few unhandled Promise rejections in a test case

lib/dialects/mssql/transaction.js, lib/dialects/oracledb/transaction.js, lib/transaction.js
The code should be functionally equivalent before and after this change.  It's mostly a minor cleanup so that the next phase of refactoring will be easier.
=> Rewrote Transaction#acquireConnection() methods to use async

test/chai-setup.js, test/index.js, test/integration/builder/additional.js, test/integration/builder/deletes.js, test/integration/builder/inserts.js, test/integration/builder/selects.js, test/integration/builder/transaction.js, test/integration/builder/updates.js, test/integration/connection-config-provider.js, test/integration/datatype/bigint.js, test/integration/logger.js, test/integration/migrate/index.js, test/integration/schema/index.js, test/integration/seed/index.js, test/integration/suite.js, test/unit/dialects/mssql.js, test/unit/dialects/oracledb.js, test/unit/dialects/sqlite3.js, test/unit/schema/mysql.js, test/unit/schema/oracle.js, test/unit/schema/oracledb.js, test/unit/schema/postgres.js, test/unit/schema/redshift.js, test/unit/schema/sqlite3.js, test/unit/seed/seeder.js
Removed a few of the globals from the test cases.  This partially addresses one of the items mentioned in #3686
=> Removed some globals from tests

lib/dialects/oracledb/transaction.js, test/integration/builder/transaction.js
As noted in #3721 , OracleDB's `Transaction#acquireConnection(..)` implementation was not using `config.connection` when it was passed in.  So, this PR addresses that bug.
=> Fix: Oracle_Transaction#acquireConnection(..) can use config.connection

lib/interface.js, test/unit/interface.js, types/index.d.ts
This PR addresses a problem that is often raised in Typescript as the ChainableInterface does not conform to `Promise<T>`.
It add the missing `Symbol.toStringTag` set to `Promise(Target.name)` (so the Builder would be) `Promise(Builder)`.
I wasn't sure of the signature, for the extend, as `finally` may not be there and it doesn't seem to be polyfilled. 
Was the `Pick<K>` being defensive as `interface.js` does not clone the `Promise` prototype?
=> Typescript: Makes the ChainableInterface conform to Promise<T>

lib/migrate/MigrationGenerator.js, lib/seed/Seeder.js, lib/util/fs.js, package.json, test/cli/migrate-make.spec.js, test/cli/seed-make.spec.js, test/index.js, test/unit/util/fs.js
**Changes**
* Upgrade [`mkdirp`](https://www.npmjs.com/package/mkdirp) to `^1.0.3`. Check issue #3740 for details.
* The new version is already Promise-friendly so update the usage a bit to address that.
* De-duplicate `_ensureFolder` logic by extracting the common logic into util function under `lib/util/fs.js`.
* Added tests for the new util function.
* Added CLI tests on the following files to ensure `seed:make` and `migration:make` commands do create directories (recursively) when they do not exist.
- https://github.com/knex/knex/blob/master/test/cli/migrate-make.spec.js
- https://github.com/knex/knex/blob/master/test/cli/seed-make.spec.js
Resolves #3740
=> Upgrade package mkdirp and improve it's usage

lib/query/string.js, test/unit/query/string.js
Follow up PR from https://github.com/knex/knex/pull/3568.
- Add tests for the main escape creator function `makeEscape` covering various cases both with default and custom config.
- Add tests for `dateToString` utility function to cover various it's logical cases
- Fix a potential issue by adding a default argument - that would show up if just the date is passed:
```
TypeError: Cannot read property 'timeZone' of undefined
```
**Test Cases**
=> Add unit tests for escape utility functions

bin/cli.js, lib/migrate/sources/fs-migrations.js, lib/seed/Seeder.js, lib/util/fs.js, lib/util/template.js, test/unit/util/fs.js
- Move all the promisified declarations of fs functions such as `readFile`, `writeFile` and `readdir` to `util/fs.js` module. This also deduplicates the usage a bit.
- Update usages and import them from the same module. 
- Add few tests - just for a quick validation of the module's exports
=> Minor improvements on the usage of fs utilities - unify all the fs functions into the same util/fs to simplify things

types/index.d.ts
I believe `interface Knex` and `function Knex` should have the same types. (well I don't understand why they should have different types).
This causes some problems with Bookshelf.
Without this PR:
<br>
With this PR:
I've run `dtslint types` and everything is OK
=> Fix Knex interface types

package.json
v2.2.0 of pg-connection-string adds this feature: https://github.com/iceddev/pg-connection-string/pull/34
=> Support more modes to set the host as a Postgres socket

bin/cli.js, bin/utils/cli-config-utils.js, test/cli/migrate-make.spec.js
Current implementation doesn't work when knexfile has multiple env-specific configuration sections.
=> #3807: Fix inference of generated seed/migration extension from knexfile extension

bin/cli.js, lib/migrate/Migrator.js, test/cli/migrate-unlock.spec.js, test/jake/jakelib/migrate-test.js
- Adds new `migrate:unlock` command to CLI which invokes `knex.migrations.forceFreeMigrationsLock()`, to provide for a CLI-based way of forcibly resetting the `knex_migrations_lock` table in the event that it gets into a bad state.
- Adjusts the behavior of `forceFreeMigrationsLock` to truncate the `knex_migrations_lock` table to ensure that there is only 1 row in the event that multiple rows have been inserted into that table, in which case [migrations will fail](https://github.com/knex/knex/blob/master/lib/migrate/Migrator.js#L299-L310)
=> Add migrate:unlock command, truncate on forceFreeMigrationsLock

lib/migrate/sources/fs-migrations.js
This PR should solve the problem which I get after specified `"type": "module"` on the `package.json`. Since `--esm` flag doesn't work on node.js 14.0, the only way to use migration CLI with module packages is to specify all files as `.cjs`. But thay are doesn't supported by default, and there is no documented way to add it to the available list, but I was find one.
=> Add support for .cjs files by default

README.md
There is an example in the README which presents `.map` as exposed with the knex library.
This had previously been valid when bluebird functions were leaked in the library and documentation.
Further described in https://github.com/knex/knex/issues/3704#issuecomment-595782683
=> Update README to reflect correct handling of native map function

types/index.d.ts
bindings for whereRaw/groupByRaw etc should be one object or array, not vararg
=> fix typings for raw querybuilders

lib/migrate/stub/ts.stub, lib/seed/stub/ts.stub
The liberal use of `any` is frowned upon by some default `tslint` configurations. That combined with the fact the these functions, as far as I know, don't _need_ to return anything, makes it reasonable to use `void` over `any` for the return type.
If this change is accepted, I could also update docs to reflect that returning on `up` and `down` functions is not necessary, unless I'm missing something!
=> Prefer `void` as return type on migration generator ts stub

lib/migrate/MigrationGenerator.js, lib/migrate/Migrator.js
This fixes issues with logging that were introduced in this PR (https://github.com/knex/knex/pull/3839).
This fixes the following issue that I logged: https://github.com/knex/knex/issues/3919
=> Fix getMergedConfig calls to include client logger

types/index.d.ts, types/test.ts
This change allows `null` into the bindings parameter of `.raw()` to typecheck properly
@lorefnon could you verify if this is the correct way to fix this
=> Add `null` as valid binding type

lib/migrate/Migrator.js, test/cli/knexfile-test.spec.js
This looks like it's an oversight, probably not caught because of low custom MigrationSource usage. Until this is merged, the temporary workaround is to make sure your custom `migration` objects have a `file` property that matches their `name`.
=> Fix migration source name in rollback all

lib/runner.js, test/integration/builder/additional.js
#3870 
When using `query.stream()` the postProcessResponse method is not called.
Example:
```js
const knex = require('./knex');
const { PassThrough } = require('stream');
async function main() {
const db = knex({
client: 'pg',
connection: 'postgres://localhost:5432/db',
postProcessResponse: (result, queryContext) => {
console.log('postProcessResponse', result, queryContext); // only called once, for the "normal" query
return result;
},
});
// normal promise - works
await db('a_table').select('*').limit(3);
// stream - doesn't work
const stream = db('a_table').select('*').limit(3).stream();
stream.pipe(new PassThrough({ objectMode: true }));
await new Promise(resolve => stream.on("finish", () => resolve()));
}
main()
.then(() => {
console.log('✅');
process.exit(0);
})
.catch((err) => { …
```
=> support postProcessResponse for streams (#3870)

types/index.d.ts
`.timeout(ms)` is [supported for `knex.raw()`](https://github.com/knex/knex/blob/master/lib/raw.js#L46), but it's missing from the TS typings.
=> Add .timeout(ms) to .raw()'s typescript typings

lib/query/builder.js, test/unit/query/builder.js
Today I was confused by the fact that `whereNot('col', 'in', [ values ])` is not valid and does fail silently. I struggled with this for quite some time before finding this part of the documentation:
> CAVEAT: WhereNot is not suitable for "in" and "between" type subqueries. You should use "not in" and "not between" instead.
If I understand correctly, it's never allowed to call `whereNot()` with "in" or "between". This PR logs the warning from the documentation, helping developers to avoid this error.
=> Warn if whereNot is used with 'in' or 'between'

types/index.d.ts
I'm pretty sure you can do this, since I had it working for multiple seeds without the typing.
=> Allow string[] type for directory in SeedsConfig

lib/dialects/mysql/schema/columncompiler.js, lib/dialects/oracle/query/compiler.js, lib/dialects/oracledb/index.js, lib/dialects/oracledb/query/compiler.js, lib/dialects/oracledb/schema/columncompiler.js, lib/dialects/postgres/index.js, lib/dialects/postgres/schema/columncompiler.js, lib/dialects/sqlite3/query/compiler.js, lib/helpers.js, lib/logger.js, lib/migrate/Migrator.js, lib/query/builder.js, lib/query/compiler.js, lib/raw.js, lib/schema/columncompiler.js, lib/schema/helpers.js, lib/schema/tablebuilder.js, lib/util/batchInsert.js, lib/util/is.js, lib/util/isObject.js, test/integration/logger.js, test/integration/schema/index.js, test/unit/dialects/postgres.js
Lodash is quite big project. Even with direct imports it loads [tons](https://github.com/knex/knex/pull/3804) of
code and still bloats node_modules. This is a problem especially since lodash
mostly used as a polyfill for modern js features.
In this diff I attempted to reduce lodash usage by replacing type checks
with `typeof` operator which might be sufficient.
Also replaced lodash/isObject with custom simplified utility which does not
consider functions as objects and allows to simplify code in one place.
=> Avoid lodash typecheks

lib/interface.js, test/unit/schema/oracle.js, test/unit/schema/oracledb.js
This solves #4045:
`toQuery()` & `toSql()` are returning duplicate semicolons for queries that pass through the method `wrapSqlWithCatch()`
Example: 
```
var knex = require('knex')({
client: 'oracledb',
connection: {
host: '127.0.0.1',
user: 'your_database_user',
password: 'your_database_password',
database: 'myapp_test'
}
});
var builder = knex.schema.dropTableIfExists('book');
console.log(builder.toQuery())
```
outputs: 
```
begin execute immediate 'drop table "book"'; exception when others then if sqlcode != -942 then raise; end if; end;;
begin execute immediate 'drop sequence "book_seq"'; exception when others then if sqlcode != -2289 then raise; end if; end;
```
=> Ensure that semicolon is not appended to statements that already end with a semicolon

lib/util/fs.js, package.json
Ref https://nodejs.org/docs/latest/api/fs.html#fs_fs_mkdir_path_options_callback
In node 10 mkdir got new flag to support mkdirp like functionality.
=> Replace mkdirp with recursive flag

lib/dialects/mssql/index.js, test/unit/dialects/mssql.js
@smorey2 [mssql]
We have a column, "NA'ME" that we use for testing to ensure ids are escaped properly.  After upgrading from knex 0.15.2 to 0.21.6, our tests started to fail with an error that the column "NAME" does not exist.  I tracked it down to the mssql dialect is incorrectly stripping out the apostrophe (') character.  This [change](https://github.com/knex/knex/pull/3382/files#diff-4dc449e5e91be857a09660e3069a0f899640116d6b53d30bda039673944cfb3bR214) seems to have included a superfluous apostrophe.  The code should wrap identifiers in [brackets].
If all is good, please kindly tag the PR as "hacktoberfest-accepted" for credit towards [hacktoberfest](https://hacktoberfest.digitalocean.com/faq).
=> Fixes issue where mssql incorrectly strips off apostrophe characters from identifiers

lib/migrate/stub/cjs.stub, test/unit/migrate/migration-list-resolver.js
When using knex in a node package that has `type:module` in its `package.json` I had to save my knexfile with the commonJS extension; `.cjs`. As a result, when running  
```
knex --knexfile knexfile.cjs migrate:make some-migration-name
```
I get this error
```
Error: ENOENT: no such file or directory, open 'node_modules/knex/lib/migrate/stub/cjs.stub'
```
I was able to resolve the issue by adding a stub to the knex package migrations folder locally. 
This PR shows my changes. It is simply a copy of the js stub. 
Let me know if any changes are required.
=> add migration stub for .cjs extension

bin/cli.js, package.json, test/cli/esm-interop.spec.js, test/cli/help.spec.js
When the cli is called without arguments it prints the help text twice. This pull request makes it print it only once. See issue #4072
=> fix help text being printed twice (#4072)

types/test.ts
This fixes the issue that was causing tests to fail although I'm not sure what's the actual cause. Might be a TypeScript error. The `async` in this case was redundant anyway. And it also works if we do
```
await knex.transaction((trx) => {
const result = await trx.insert({ name: 'Old Books' }, 'id').into('articles');
return result
});
```
Anyway, this should fix test errors for now without losing any safety of tests.
=> Remove redundant async in tests

package.json, types/index.d.ts, types/tables.d.ts, types/test.ts
For most use-cases, this would allow to globally define table/record mapping globally once and get all the benefits of static typing without always specifying Records manually.
This is opt-in as it will fall back to old behaviour if Tables interfaces is not extended and it supports all old use-cases.
Opening as a draft for further discussion and improvements.
=> Allow to globally define table/record mapping

types/index.d.ts
Added the following options for MsSqlConnectionConfig TS interface
- isolationLevel
- maxRetriesOnTransientErrors
- multiSubnetFailover
- packetSize
These are documented in the [Tedious driver docs](https://tediousjs.github.io/tedious/api-connection.html)
I personally want to use `multiSubnetFailover` and `packetSize` for a production deployment we recently migrated from Flow
=> Add a few missing types for MSSQL Connection

types/index.d.ts, types/test.ts
Fixes part (2) from https://github.com/knex/knex/issues/4101
=> Types: Make .ignore() and .merge() return QueryBuilder rather than QueryInterface

types/index.d.ts
Add types to index.d.ts for missing `knex.userParams` param and `knex.withUserParams({})` method, as suggested in issue: https://github.com/knex/knex/issues/3962
The types are pretty open as looking at the source there don't seem to be any restrictions on what the user can pass, so long as it's a literal object, the values can be anything.
=> Add types for userParams and withUserParams

lib/dialects/mysql/query/compiler.js, lib/dialects/postgres/query/compiler.js, lib/dialects/sqlite3/query/compiler.js, test/integration/builder/inserts.js, test/unit/query/builder.js
This is a follow-up to #3763, which adds support for WHERE clauses to "upsert" queries for the DB engines that support this functionality.
Based on my research on the DB engines that support "upsert" queries, it seems like PostgreSQL and SQLite support WHERE clauses for them, but MySQL does not:
https://www.postgresql.org/docs/10/sql-insert.html
https://sqlite.org/lang_upsert.html
https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html
To do:
Closes #4145
=> Add support for WHERE clauses to "upsert" queries

types/index.d.ts
Adds support for application_name as a valid type.
This option is already supported in `pg`, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pg/index.d.ts
Also confirmed that it passes through correctly. Let me know if I should also be adding a test for this typing change.
=> Add support for application_name in PG connection types

lib/util/fs.js, test/unit/seed/seeder.js, test/unit/util/fs.js
- Run `knex seed:run` with `seeds: { sortDirsSeparately: true }` option
- Run seed files with irregular order (unsorted)
- Change order every time you run
See https://github.com/progfay/knex-irregular-file-order-poc
- In `getFilepathsInFolder` function, push file path to array asynchronously
- To avoid async pushing
=> Fix(seed:run): irregular seed file execution order

lib/interface.js, lib/util/save-async-stack.js, test/db-less-test-suite.js, test/unit/interface.js, test/unit/util/save-async-stack.js
Reading stack trace with '--enable-source-maps' flag on node can be very costly, 
in our case when using knex it takes 100-200ms for every query what in case of multiple queries gives huge delays.
Instead of reading stack trace at saveAsyncStack function better to read it when needed at catch error.
=> Fix performance of asyncStackTraces with enable-source-maps node flag

lib/runner.js
The docs said that these events contain both __knexUid and __knexTxId but I found that it were lacking __knexTxId
=> Make sure query-response and query-error events contain _knexTxId

UPGRADING.md, bin/cli.js, bin/utils/cli-config-utils.js, lib/util/fs.js, package.json
Liftoff has very poor support and a lot of legacy dependencies.
The package takes half of knex size.
https://packagephobia.com/result?p=liftoff
https://packagephobia.com/result?p=knex
The package is not abandoned though there are no clear deadlines.
https://github.com/js-cli/js-liftoff/pull/114
I also found most liftoff features are not used by knex and in some
cases the usage is wrong.
For example I found `--knexpath` is not used at all. It's consumed
from liftoff's env.knexpath which is always undefined.
I reimplemented all resolutions with a few small utilities like escalade
and resolve-from.
v8flags and flagged-respawn looks like black magic so I suggest to
recommend using `NODE_OPTIONS="...flags..." npm run knex` instead.
For config transpilation still used interpret and rechoir …
=> Drop liftoff

lib/client.js, lib/interface.js, lib/internal/query-executioner.js, lib/query/builder.js, test/integration/builder/additional.js, test/integration/builder/inserts.js, test/integration2/insert/on-conflict-merge.spec.js, test/util/db-helpers.js
=> Extract query execution-related code from client

lib/dialects/mssql/transaction.js, lib/dialects/oracledb/transaction.js, lib/dialects/postgres/index.js, lib/dialects/postgres/transaction.js, lib/dialects/redshift/transaction.js, lib/dialects/sqlite3/index.js, lib/dialects/sqlite3/transaction.js, lib/execution/transaction.js, lib/knex-builder/make-knex.js, scripts/docker-compose.yml, test/integration2/transaction/set-isolation-level.spec.js, test/unit/knex.js, test/util/db-helpers.js, types/index.d.ts
Attempt to solve #581 
Probably needs some extra tests, not sure where the best place to put them is.
Also probably needs to implement for all drivers rather than just half of them
Syntax is `knex.transaction(...).setIsolationLevel('string')`
=> Add transaction isolation support

lib/dialects/sqlite3/schema/ddl.js, lib/dialects/sqlite3/schema/sqlite-tablecompiler.js, test/integration/query/additional.js, test/integration/schema/index.js
Since SQLite version 3.25.0 renaming columns is supported natively.
Knex depends on `sqlite3@5.0.0` which bundles SQLite version 3.32.3, so this should be safe unless someone manually builds `sqlite3` with an older version.
=> Use SQLite rename column instead of ddl helper

ECOSYSTEM.md
Just adds [pg-mem](https://github.com/oguimbal/pg-mem) to documentation, which now supports Knex.
FYI, `pg-mem`is a small full-js library emulating an in-memory Postgres instance, which is bindable to virtually every library aiming postgres (see [supported bindings](https://github.com/oguimbal/pg-mem#-libraries-adapters) here)
=> Add pg-mem to documentation

lib/dialects/mssql/query/mssql-querycompiler.js, lib/query/querybuilder.js, lib/query/querycompiler.js, test/integration/query/selects.js, test/unit/query/builder.js, types/index.d.ts
Implements #4199
Optimizer hints using comment `/*+` syntax support in dialects:
- MySQL: Supported and working.
- Postgres: Not supported in vanilla Postgres. Supported in some extensions like in EDB Postgres Advanced Server, where the [syntax is the same](https://www.enterprisedb.com/edb-docs/d/edb-postgres-advanced-server/user-guides/database-compatibility-for-oracle-developers-guide/11/Database_Compatibility_for_Oracle_Developers_Guide.1.038.html
) as in MySQL. Not tested as I don't have access to EDB Postgres Advanced Server.
- Oracle: Supported. The [syntax is the same](https://docs.oracle.com/cd/B13789_01/server.101/b10752/hintsref.htm) as in MySQL. Not tested as I don't have access to Oracle DB.
- MSSQL: Not supported.
- Sqlite3: Not supported.
It is still good to keep the hints …
=> Allow optimizer hints

lib/dialects/mssql/query/compiler.js, lib/query/builder.js, lib/query/compiler.js, test/integration/builder/selects.js, test/unit/query/builder.js, types/index.d.ts
=> Allow optimizer hints - Backport to 0.21

types/index.d.ts
Added typedefinitions for `havingNotIn`, `andHavingNotIn` and `orHavingNotIn` as they were missing per this [issue](https://github.com/knex/knex/issues/3854)
=> Add typedefinitions for havingNotIn

lib/query/querybuilder.js, test/unit/query/builder.js
Fixes issue: #2607 
**Case 1**:
`.withSchema` usage with join on a subquery (as a `Builder`) using a function as the join condition
```javascript
qb()
.withSchema('schema')
.select()
.from('foo')
.join(qb()
.select(['f_id'])
.from('baz')
.as('bar'), j => j.on('bar.f_id', 'foo.id')
```
Expected result:
```sql
select * from "schema"."foo" inner join (select "f_id" from "baz") as "bar" on "bar"."f_id" = "foo"."id"
```
Actual result:
```sql
select * from "schema"."foo" inner join "schema"."select ""f_id"" from ""baz""" on "bar"."f_id" = "foo"."id"
```
**Case 2**:
`.withSchema` usage with join on a subquery (as a `function`)
```javascript
qb()
.withSchema('schema')
.select()
.from('foo')
.join(q => q
.select(['f_id'])
.from('baz')
.as('bar'), 'bar.f_id', 'foo.id')
```
Expected result:
```sql …
```
=> Fix issue with schema usage with joins on a subquery

lib/dialects/mssql/schema/mssql-columncompiler.js, lib/dialects/mysql/schema/mysql-columncompiler.js, lib/dialects/mysql/schema/mysql-tablecompiler.js, lib/dialects/oracle/schema/oracle-columncompiler.js, lib/dialects/postgres/schema/pg-columncompiler.js, lib/dialects/redshift/schema/redshift-columncompiler.js, lib/schema/columncompiler.js, test/integration/query/trigger-inserts.js, test/integration/schema/index.js, test/unit/schema-builder/mssql.js, test/unit/schema-builder/mysql.js, test/unit/schema-builder/oracle.js, test/unit/schema-builder/oracledb.js, test/unit/schema-builder/postgres.js, test/unit/schema-builder/sqlite3.js
Including changes for:
Auto increment is removed when column is renamed in mySQL.
It has to be specified again so it is kept.
Fixed issue knex#2767
Usage:
```js
t.increments('id', { primaryKey: false }) => Not primary key
t.increments('id') => Primary key as currently
```
Rebasing of knex#2011
=> Primary keys improvements

lib/query/querycompiler.js, test/unit/query/builder.js
Fixes issue: #1368
Related issues: #2054, #3654
Prevent adding a `schema` (specified by `.withSchema`) to a `.from` caluse containing a `QueryBuilder`, `Raw` or `function`.
=> Fix issue with schema usage with FROM clause

lib/dialects/sqlite3/schema/ddl.js, lib/dialects/sqlite3/schema/internal/sqlite-ddl-operations.js, test/integration/schema/index.js, test/integration2/schema/foreign-keys.spec.js
This is the procedure recommended by the [SQLite Docs](https://sqlite.org/lang_altertable.html#otheralter). It saves a few SQL statements, most importantly copying the data twice.
Unfortunately, SQLite's `RENAME TABLE` adds double quotes around the table name, so I had to alter some of the tests.
=> Simplify reinsert logic when altering a table in SQLite

lib/dialects/sqlite3/schema/ddl.js, lib/dialects/sqlite3/schema/internal/compiler.js, lib/dialects/sqlite3/schema/internal/parser.js, lib/dialects/sqlite3/schema/internal/sqlite-ddl-operations.js, test/integration2/schema/index.spec.js, test/unit/schema-builder/sqlite3.js
I tried to separate the parsing and the altering logic as much as possible.
When querying `sqlite_master` for create index statements, it seems like only the first part of those statements is in uppercase. It would be nice if the casing was consistent but when I tried to uppercase the index creation statements in the SQLite TableCompiler, nearly all tests failed with cryptic errors.
=> Recreate indices when altering a table in SQLite

lib/dialects/mssql/schema/mssql-columncompiler.js, test/integration/schema/index.js
This patch changes the `json` column type in the MSSQL dialect from `text` to `nvarchar(max)` to bring it in-line with JSON requirements for storage.
* According to [MSDN](https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15) the `text` and `ntext` types are deprecated and will be removed in future versions of SQL Server.
* As `text` types are unconditionally stored in LOB storage there may be performance implications for small JSON data.
* The JSON spec [RFC4627](https://www.ietf.org/rfc/rfc4627.txt) requires a UTF-8 strings but `text` stores non-unicode data, which will corrupt otherwise spec-conforming documents with unicode characters in it.
Tests have been updated to acknowledge the new type.
=> mssql: column: json from text to nvarchar(max)

lib/dialects/mssql/transaction.js
Restore hotfix from #4128
It's unclear if it's still needed, but it'd be better to drop it later to avoid additional potential breakages for people updating to the next major.
=> MSSQL hotfix for error handling in cloud

lib/dialects/mssql/index.js, test-tsd/mssql-config.test-d.ts, types/index.d.ts
This patch introduces typings for all the available connection options in `mssql` with the tedious driver.
It includes tsd tests to assert type overloading of the `MsSqlConnectionConfig` union type.
=> mssql: add all mssql options to Knex.ConnectionConfig

lib/dialects/mysql/query/mysql-querycompiler.js, lib/dialects/postgres/query/pg-querycompiler.js, lib/dialects/sqlite3/query/sqlite-querycompiler.js, package.json, test-tsd/types.test-d.ts, test/integration/query/inserts.js, types/index.d.ts
Fixes #4209 
Maybe fixes #4106
New syntax on merge:
```
knex('upsert_tests')
.insert(
{ email: 'mergedest@example.com', name: 'SHOULD BE USED', age: 12 },
)
.onConflict('email')
.merge(['name', 'age'])
```
Will update only the name and age fields.
Also works for multi-inserts.
=> Added merge strategy to allow selecting columns to upsert.

UPGRADING.md, lib/dialects/mssql/index.js, lib/dialects/mysql/index.js, lib/dialects/oracle/index.js, lib/dialects/postgres/index.js, lib/dialects/sqlite3/index.js, test/integration/query/inserts.js
Not sure if it would be better to throw an error, but at least the behavior should be consistent.
=> Throw error if the array passed to insert is empty

types/index.d.ts
PR #3416 added the ability to specify a filename for the up and down commands, but that parameter was left out of the MigratorConfig interface, causing compilation errors for those using that property and typescript.
=> Include 'name' property in MigratorConfig

lib/execution/runner.js, test/unit/knex.js
This patch introduces support for submitting the `queryContext` on `query-error` events.  
Because of the async nature of some drivers, the root callsite of responses is usually `TCP._onRead`.  Query builders created in the context of an Express request or another mechanism get lost in error events attached to the query builders.  Being able to access the `queryContext` in case of an error is a low-overhead way of relating a query error back to something more high level, enabling meaningful error reporting.
The patch is covered by a unit test.
=> events: introduce queryContext on query-error

test/integration2/transaction/set-isolation-level.spec.js, test/integration2/util/knex-instance-provider.js, test/unit/knex.js
This PR contains several changes that simplify getting a green test run in a fresh checkout by eliminating some unexpected behavior around KNEX_TEST and DB config.
Before, if DB omitted sqlite3, several of the CLI tests would fail, because only some of them conditionally skipped when sqlite3 config was not available. Now, all of those tests skip when sqlite3 tests are not selected.
Before, some of the DB integration tests did not use the config supplied in KNEX_TEST. Now, all run by test:db do.
Before, the mssql transaction isolation tests required, not just a test DB, but also a test DB with snapshot isolation already enabled. This led to test failures due to having a test DB without that config already set up. Now, that test suite ensures snapshot isolation is enabled upfront before …
=> Respect KNEX_TEST, support omitting sqlite3 from DB, and reduce outside mssql test db config

lib/dialects/mssql/index.js, lib/execution/runner.js
This patch slightly reworks how the query context gets passed from the runner into the dialects.  The query object now has a `context` parameter with the query context to be raised on `query-error` events, this avoids having to re-bubble `query-error` events from the builder instance in the `mssql` dialect.  Test surface has not changed as it gets the same outcome.
=> mssql: don't raise query-error twice

lib/dialects/mssql/schema/mssql-tablecompiler.js, test/unit/schema-builder/mssql.js
fixes #4316
As a side effect of my change, the `alter column` casing now respects the `lowerCase` flag on all alter commands
=> fix mssql alter column must have its own query

lib/dialects/sqlite3/schema/ddl.js, lib/dialects/sqlite3/schema/internal/compiler.js, lib/dialects/sqlite3/schema/internal/parser-combinator.js, lib/dialects/sqlite3/schema/internal/parser.js, lib/dialects/sqlite3/schema/internal/tokenizer.js, lib/dialects/sqlite3/schema/sqlite-tablecompiler.js, lib/formatter/formatterUtils.js, lib/schema/columncompiler.js, test/integration2/schema/alter.spec.js, test/integration2/schema/index.spec.js, test/unit/schema-builder/sqlite3.js
The approach I took to parse `CREATE INDEX` statements using regexes was unfortunately not flexible and robust enough to properly parse `CREATE TABLE` statements. I replaced it with a tokenizer and parser combinators. The grammar is based on the SQLite documentation.
Any idea where the `formatDefault()` function would fit? It is currently directly inside the `ColumnCompiler` class which doesn't feel right.
=> Add support for altering columns to SQLite

lib/execution/runner.js
This is for consistency with how queries are passed to `queryArray()` without the statements producer.
=> Convert produced statements to objects before querying

lib/dialects/mssql/schema/mssql-columncompiler.js, test/integration/schema/index.js, test/integration2/dialects/mssql.js, test/unit/schema-builder/mssql.js, types/index.d.ts
In SQL server, default values are stored as `CONSTRAINTS` against the table. if no constraint name is provided and just the short syntax of `DEFAULT xxx` is used, then SQL server creates a "random" constraint name. This makes writing predictable schema migrations tricky as the `DEFAULT` constraint needs to be dropped before it can be updated/changed.
The constraint names follow the format `${tableName}_${columnName}_${default}` (lowercased) which follows the convention of other constraints like default index names.
Usage:
```js
knex.schema.alterTable('table', (table) => {
// new behaviour - will produce a default constraint named table_myint_default
table.integer('myInt').defaultTo(1);
// create a custom named constraint
table.integer('myInt').defaultTo(1, 'DF_table_myInt');
// no …
```
=> mssql: schema builder - add predictable constraint names for default values

lib/dialects/mssql/schema/mssql-columncompiler.js, lib/dialects/mssql/schema/mssql-tablecompiler.js, test/integration2/dialects/mssql.js, test/unit/schema-builder/mssql.js
Depends on #4319 
When changing a default value on a column in mssql, the previous default constraint needs to be dropped before a new one can be assigned. This PR attempts to drop the constraint and then adds the constraint via a separate query:
```tsql
DROP CONSTRAINT [constraint_name]; //does some look up to find the constraint name
ALTER TABLE [table] ALTER COLUMN ...; // other altering of column
ALTER TABLE [table] ADD CONSTRAINT [constraint_name] DEFAULT [defaultVal] FOR [column_name]; // applies default constraint
```
Help required:
I've tried to get a grasp of how the internals of the builder work for this and  implemented this in a way that I think makes the most sense.
Under some circumstances this change can result in a needless alter query being run when the only change to a …
=> mssql: schema builder - attempt to drop default constraints when changing default value on columns

lib/dialects/sqlite3/schema/ddl.js, test/integration2/schema/foreign-keys.spec.js
Hey @kibertoad 👋  I'm Thibaut from [Ghost](https://github.com/TryGhost/), we're working on releasing Ghost 4.0 very soon but found a bug in knex that is blocking us, here is the fix for it! The best case scenario for us would be if this fix would land in knex `0.21` ❤️ 
The problem comes when using the `foreign` feature on SQLite.
The limitations of SQLite requires the creation of a temporary table, and the constraints are uppercased due to [this code](https://github.com/knex/knex/blob/0.21/lib/dialects/sqlite3/schema/ddl.js#L478-L489). This means it introduces constraints definitions in uppercase format (like `FOREIGN KEY`).
However the constraint detection is using `startsWith` or `includes` which are both case-sensitive.
This PR fixes this issue by lowercasing the definitions before …
=> SQLite: made the constraint detection case-insensitive

lib/dialects/sqlite3/schema/ddl.js, lib/dialects/sqlite3/schema/sqlite-tablecompiler.js, test/integration2/schema/alter.spec.js
The statements produced by the statements producer are currently not executed inside a transaction, which means that the changes are not rolled back if an error occurs. This will be fixed by #4189, but I won't find the time to finish that PR before the `0.95.0` release. Once it's done, this change can be reverted.
=> Fix SQLite not doing rollback when altering columns fails

lib/constants.js, test/integration/datatype/bigint.js, test/integration/datatype/decimal.js, test/integration/datatype/double.js, test/integration/execution/transaction.js, test/integration/logger.js, test/integration/migrate/migration-integration-tests.js, test/integration/query/additional.js, test/integration/query/aggregate.js, test/integration/query/inserts.js, test/integration/query/joins.js, test/integration/query/selects.js, test/integration/query/trigger-deletes.js, test/integration/query/trigger-inserts.js, test/integration/query/trigger-updates.js, test/integration/query/unions.js, test/integration/schema/foreign-keys.js, test/integration/schema/index.js, test/integration/suite.js, test/integration2/schema/primary-keys.spec.js, test/tape/crossdb-compatibility.js, test/tape/stream.js, test/tape/transactions.js, test/util/constants.js, test/util/db-helpers.js
Refactoring tests to use the functions in db-helpers rather than checking for the type of driver in `n` different ways (feedback on #4327).
This PR seemed large enough to break out into its own and do it in a standalone fashion before moving on with #4327. 
Also adding constants for driver names
When testing against the `driverName` there seems to be a number of
locations where the value being checked against may not be the actual
`driverName`. This may result in tests passing or failing incorrectly.
Adding a constant that has all current `driverName`s defined so that
matching can be done confidently and with tooling support. It's
effectively an enum.
Updating the tests to use the db-helpers, and having the db-helpers
utilize the drivers for correct naming should ensure all tests fire as …
=> [WIP] Unify db test helpers

lib/knex-builder/Knex.js, test-tsd/querybuilder.test-d.ts, test-tsd/types.test-d.ts, types/index.d.ts
=> Move QueryBuilder and KnexTimeoutError into knex namespace so that they are accessible at a runtime

lib/migrations/migrate/stub/ts.stub, lib/migrations/seed/stub/ts.stub, test/jake-util/knexfile-ts/knexfile_migrations/20200131112749_one.ts, test/jake-util/knexfile-ts/knexfile_migrations/20200131112753_two.ts, test/jake-util/knexfile-ts/knexfile_migrations/20200131112757_three.ts, test/jake-util/knexfile-ts/knexfile_migrations/20200131112801_four.ts
Changed `ts.stub` files for migrations and seeds to reflect changes in 0.95, also documented in https://github.com/knex/knex/blob/master/UPGRADING.md#upgrading-to-version-0950
> `import { Knex } from 'knex' // this is a namespace, and a type of a knex object`
---
Also changed `test/jake-util/knexfile-ts/knexfile_migrations` files for the same reason, including an import path change from `<root>/knex.js` to `<root>`, as the node will automatically resolve the `<root>` import to what's in the `package.json#main` field, allowing TypeScript to do similar for `package.json#types` field.
=> fix: update ts.stub files to new TypeScript namespace

lib/migrations/migrate/stub/ts.stub, test-tsd/types.test-d.ts
Release 0.95.0 changed how types have to be imported when using TypeScript. This PR fixes the migration stub so new migrations are created correctly.
=> fix TypeScript migration stub after 0.95.0 changes

lib/knex-builder/internal/config-resolver.js
TypeScript makes it very hard to get typescript to correctly check the `instanceof Client` part of the statement.
See: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work
=> [TypeScript] Allow config.client to be non-client instance

lib/dialects/sqlite3/schema/ddl.js
Fix dropForeign not working as expected in SQLite.  Uses the new setup introduced by @nickrum .
Fixes #4369, fixes https://github.com/directus/directus/issues/4489
=> Rework dropForeign to use new tokenized structure

lib/dialects/mysql/index.js, lib/dialects/postgres/index.js, test/integration/query/additional.js
Based on PR https://github.com/knex/knex/pull/2527 - rebased and added the fix for postgres too:
> KILL commands have to be sent on a seprate connection, and transaction Clients override acquireConnection to always return the same connection.
>
> Furthermore, it is plausible that some applications may never be able to Acquire a pooled connection for cancellation becuase a query which is Exceeding the timeout may coincidentally exhaust the connection pool.
>
> For example, if a DDL operation is blocking writes, a connection pool May be quickly exhaused by write operations.
Timeout cancellation during transaction is fixed by using `acquireRawConnection` and `_query` to bypass the transaction connection and cancel the query from a separate connection.
fixes #2211
=> Fix timeout method

lib/query/querybuilder.js, test/integration/query/selects.js
HI. I started working on this. I faced some challenges I need advice on.
- First of all, I'm only familiar with `mysql`. Is negative offset invalid for all kind of databases? Should I consider database type?
- Then I found `offset` function in `querybuilder.js` file, and extended an existing condition:
- The problem with above solution was that negative offset values resulted in a warn log (orange in my case) and were automatically omitted (or converted to `zero`). I thought this automatic omitting makes bad logic/behavior is user's code hidden or hard-to-debug.
-  Later I  thought maybe it's not a bad idea if we threw an error in case of negative offset
- The above solution can be and not be a breaking change. It can be a breaking change, because it did not use to throw an error, but can …
=> [wip] fixes #4335: warn if negative offset was provided

types/index.d.ts
Fix types of `TableBuilder['increments']` and `TableBuilder['bigIncrements']` to allow the optional options object after the column name.
=> Fix typing for increments and bigIncrements

lib/dialects/sqlite3/index.js, test/tape/knex.js, types/index.d.ts
With this pull request it should be possible to open a shared memory database without recompiling sqlite, which has quite a lot of use cases, especially in testing. It should for example allow [this](https://github.com/knex/knex/issues/1871#issuecomment-452342526) solution work even if sqlite3 is not compiled with the SQLITE_USE_URI=1 flag.
I set the default mode selection to the default of node-sqlite3 so all existing code should still work.
Link to documentation PR: https://github.com/knex/documentation/pull/320
=> Add support for file open flags for sqlite3 

types/index.d.ts
Related #2746
Closes #4435
I wasn't sure exactly which arguments it really supports, I confirmed that these 2 versions work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/knex/knex/4436)
=> Add typings for on JoinClause for `onVal`

types/index.d.ts, types/test.ts
Fixes https://github.com/knex/knex/issues/4475
=>  fix: export client class from knex namespace

README.md
Remove the extra ")" in TypeScript example.
=> fix: mistyping in TypeScript example

lib/migrations/seed/Seeder.js
Added '.cjs' to the list of supported extensions for seed files in the Seeder.js setConfig(config) {} function. 
This will allow users to run seeds with Knex in CommonJS mode within a Node project that has has ESM support.
=> Add .cjs extension to Seeder.js to support Node ESM (#4381)

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
Node 16 was released short time ago, and became the "current" version. Knex readme states that all Node versions 10+ are supported, but CI is not currently run for Node 16.
Adds Node 16 to version matrixes. Everything seems to pass just fine, as seen [here](https://github.com/stscoundrel/knex/pull/1)
=> CI: add Node 16 to version matrix

package.json
=> Remove peerDependencies to avoid auto-install on npm 7

lib/dialects/postgres/query/pg-querycompiler.js, lib/dialects/sqlite3/query/sqlite-querycompiler.js, test/integration/query/inserts.js
pull request to handle #4552. Adds the ability to omit the column list for onConflict in postgres and sqlite3 (mysql currently only supports omitting the columns).
the column list is used as a proxy for whether an onConflict exists, so that's why it's true if there are no columns, we could try making it something more explicit like a symbol if we think there could be a problem.
=> add ability to omit columns on an onConflict().ignore()

bin/utils/cli-config-utils.js
When `stack` and `detail` properties are not available, only `undefined` is printed in the console which makes it extremely difficult to diagnose the issue. This change logs `messsage` property if set
Can be replicated when using `envvar` lib  and  [UnsetVariableError](https://github.com/plaid/envvar/blob/master/index.js#L17  ) is [thrown](https://github.com/plaid/envvar/blob/master/index.js#L39)
=> log error message

lib/dialects/oracle/utils.js
Add DPI-1010 and DPI-1080 error codes required for oracledb >=5.2.0
=> Add DPI error codes for Oracle

lib/dialects/mssql/query/mssql-querycompiler.js, lib/query/querycompiler.js, test/integration/query/deletes.js, test/integration/query/trigger-deletes.js, test/unit/query/builder.js
Fix for the issue https://github.com/knex/knex/issues/873
The issue is that joins are not included in delete queries.
Examples can be found in tests: https://github.com/knex/knex/compare/master...Egor-Koldasov:fix/873-delete-join?expand=1#diff-9a54bb8c91fbb672179c076a18af9db40b73bc5c4a3e3ea7cc89c48ea8ebeadfR9944
Notes on the solution:
1. Solution does not include the ability to delete multiple tables. To me, it is not clear, how the interface should be expanded to include this option. It would be great to have a recommendation from collaborators: https://github.com/knex/knex/issues/873#issuecomment-877761010
It does solve other issues, allowing to delete values from a table by filtering values from another joined table.
It also helps with unexpected queries and potential data loss …
=> #873 | implement delete with join

lib/dialects/postgres/schema/pg-columncompiler.js, test/unit/schema-builder/postgres.js
- Why:
See issue #4577 
- How: 
1. Change default useTz option of datetime and timezone to true in pg column compiler. 
2. Adding additional test to check when empty option object or option object wihout timezone is passed.
=> Fixing posgres datetime and timestamp column created with wrong format

lib/dialects/mssql/index.js, types/index.d.ts
Description:
This is a back-port of the change already integrated in the 0.95 developer stream. The PR for that stream can be [found here](https://github.com/knex/knex/pull/4500).
Tests:
There do not appear to be any tests that cover the connection config options schema for mssql that has been changed in my PR. If I missed the place where such a test should go, please feel free to point this out to me and I will be happy to re-submit. The PR for the 0.95 stream also does not appear to include tests.
Documentation
Still needs to be updated. That will be a separate PR if this PR is accepted.
=> 0.21 mssql trust certificate

test-tsd/tables.test-d.ts, types/index.d.ts
I came across this PR: https://github.com/knex/knex/pull/3556. since it hasn't been actived for a long time so i want to conttinue it and also to fix my last Pull Request where i also put ```deferrable``` inside ```ColumnBuilder```
=> fix typing deferrable and withkeyName should not be in ColumnBuilder

lib/dialects/postgres/query/pg-querycompiler.js, test/integration/query/additional.js
There is an edge case when getting proxied by for example PgBouncer that could result in client connection not being the same as the current database.
Using current_database() seems like a safer approach.
=> fix: use sys info function instead of connection db name

lib/dialects/mssql/query/mssql-querycompiler.js, test/integration/query/additional.js, test/integration/schema/index.js
Before, the SQL used to implement `columnInfo()` for the mssql driver referenced `information_schema.columns`.
But in a database with a case-sensitive collation, both of those parts must be capitalized, as `INFORMATION_SCHEMA.COLUMNS`, or you just get an error [#4573]. (It doesn't seem sensitive to how you capitalize the column names, though. 🤷 )
Now, that capitalized form is used when interacting with mssql.
In order to test this change, I needed to create a new database with a case-sensitive collation, then tear it down. This required digging around to grab the database config used in the integration test suite.
It would be cleaner to change the default test database for MSSQL to be created with a case-sensitive collation, in which case, every test would be a test of case-sensitive …
=> fix(mssql): columnInfo() now works with case-sensitive database [fixes #4573]

lib/dialects/mssql/mssql-formatter.js, lib/dialects/mssql/schema/mssql-columncompiler.js, lib/dialects/mssql/schema/mssql-tablecompiler.js, test/integration/schema/index.js, test/integration2/dialects/mssql.spec.js
Table and column comments are now compiled into MS_Description
extended properties.
[fixes #4204]
=> feat(mssql): Support comments as MS_Description properties [fixes #4204]

lib/dialects/mssql/query/mssql-querycompiler.js, test/integration/query/selects.js, test/unit/query/builder.js
mssql forbids use of the RECURSIVE keyword required by some other
dialects.
The approach taken here maximizes subclass reuse and leaking
changes to the query outside `with` generation. If we skipped
restoring the recursive labels using `undoList`, the SQL would
generate fine here, but the test suite fails:
The next-tested driver fails its test, because clone() preserves the
top-level statement's `recursive = false` change, so it's shy one
`RECURSIVE` in the generated SQL.
This addresses the mssql portion of [#4514], but not the oracledb issues.
If this approach to omitting RECURSIVE looks good, I can apply the same to the
oracledb dialect. (Supporting a column alias list as separate argument, as Oracle
requires for recursive CTEs, would require deeper changes.)
=> fix(mssql): Generate valid SQL for withRecursive() [#4514]

lib/dialects/postgres/schema/pg-tablecompiler.js, lib/dialects/sqlite3/schema/sqlite-tablecompiler.js, lib/schema/tablebuilder.js, lib/schema/tablecompiler.js, test/integration2/schema/set-nullable.spec.js
Refreshed version of #1327 by @wubzz 
fixes #1218
Note that old solution of `table.string('checksum').nullable().alter();` is not particularly flexible, because it attempts to switch type from itself to itself, which works by a happy accident in majority databases, but breaks for the others (such as CockroachDB). It was also quite different from how other schema operations worked.
=> Implement nullability modification via schema builder

lib/query/analytic.js, lib/query/querybuilder.js, lib/query/querycompiler.js, test/unit/query/builder.js, types/index.d.ts
This is a little annoyance I found while writing query calls using `rowNumber` as the typescript types shows you are allowed to do this but if you try to use an array of objects the SQL request fail with `column ?? does not exist` where ?? is the array of objects columnized.
=> Fix Analytic orderBy and partitionBy to follow the SQL documentation

lib/dialects/oracledb/index.js, lib/dialects/oracledb/schema/oracledb-tablecompiler.js, test/integration2/schema/set-nullable.spec.js
Before, these functions would fail when run, as indicated by test suite failures when testing against oracledb.
Now, they work.
The existing tests were also not checking the error message as intended, so I have corrected that. (I originally thought to include a "make sure errorMessage is a string" check, but since only a fraction of the drivers had spec'd error messages, I backed that out.)
=> fix(oracledb): Support setNullable, dropNullable

lib/dialects/oracledb/query/oracledb-querycompiler.js, lib/query/querybuilder.js, lib/query/querycompiler.js, package.json, test-tsd/types.test-d.ts, test/integration/query/selects.js, test/unit/query/builder.js, types/index.d.ts
Before, the Oracle query compiler included an erroneous RECURSIVE keyword, and you could not include a column list, as required in Oracle SQL when writing an rCTE.
Now, both are fixed.
=> fix(oracledb): withRecursive: omit invalid RECURSIVE keyword, include column list [#4514]

lib/execution/transaction.js
This is a pull request to fix the issue concerning the use of filtered catch after a transaction (see [issue](https://github.com/knex/knex/issues/4665))
=> Passing all arguments to _promise.catch function #4665

lib/dialects/sqlite3/schema/ddl.js, lib/dialects/sqlite3/schema/sqlite-tablecompiler.js, test/integration2/schema/set-nullable.spec.js
As discussed in #4681 I've added support for `setNullable` and `dropNullable` to the SQLite dialect.
Hopefully I didn't miss anything!
=> Added setNullable support to SQLite

lib/migrations/migrate/table-creator.js
There is currently a race in ensureTable function that could result in multiple rows being insert into the locks table. Multiple locks in the lock table is a non-recoverable state where no lock can later
be acquired.
The reason for the race is that the number of locks are first retrieved from the lock table, and a new lock is then inserted if that number
is zero. It is possible that a lock is inserted into the locks table right after the number of locks were first retrived, resulting in another lock being inserted.
This is fixed by using an insert into select where no row is inserted if
there is already a row in table, which is the desired end state.
=> Avoid inserting multiple locks if a lock already exists

lib/query/method-constants.js, lib/query/querybuilder.js, test/unit/query/builder.js, types/index.d.ts
- Finish https://github.com/knex/knex/pull/4429 to add 'fromRaw' (@elhigu).
- Closes https://github.com/knex/knex/issues/1767
=> Support fromRaw

lib/dialects/postgres/schema/pg-columncompiler.js, test/unit/schema-builder/postgres.js
- Fixes https://github.com/knex/knex/issues/4784
- Remove duplicate (actually timestamp == datetime implementation in PG) and so correct datetime precision = 0 too.
=> Zero precision in timestamp/datetime #4784

lib/query/querybuilder.js, test/unit/query/builder.js
I ran into this with a `whereNot('id', 'in')` clause producing a warning despite it only intending to occur when 'in' is an operator, not a value.
Please let me know if the test format isn't right, I'd be happy to change it!
=> Fix overzealous warning on use of whereNot with "in" or "between"

types/index.d.ts
- Fix issue commented here : https://github.com/knex/knex/pull/4768#discussion_r740819424
=> Allow string indexType in index creation

lib/query/querycompiler.js, test/unit/query/builder.js
- Fix a syntax bug with union all and first because the (old) onlyUnion function is always false (we have a columns array with empty array for values).
- Fixes #4364
=> Fix Union all + first syntax error (#4364)

lib/migrations/migrate/stub/js.stub, lib/migrations/migrate/stub/knexfile-js.stub, lib/migrations/seed/stub/js.stub
Documents the types of the cli-generated files for init, migrate:make and seed:make. Uses the TS-specific flavor of JSDoc described in the [TypeScript](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) Handbook. This enables code hinting. Typescript users can use the [checkJs](https://www.typescriptlang.org/tsconfig/#checkJs) in their project to raise a compilation error e.g. if they forget to return a Promise from the migration function. So this provides an alternative to making the cli generate TS directly with the `-x ts` option. Being JSDoc, it does not assume any specific module system on the user's machine to import the Knex.
Some screenshots with IntelliSense in Visual Studio Code
Seed, current
Seed, PR
Knexfile, current
Knexfile, PR
Migrations, current …
=> Resolves #4583 Add JSDoc (TS flavor) to stub files

lib/dialects/postgres/index.js, lib/dialects/postgres/query/pg-querybuilder.js, lib/dialects/postgres/query/pg-querycompiler.js, lib/query/querybuilder.js, lib/query/querycompiler.js, test/integration/query/deletes.js, test/unit/query/builder.js, types/index.d.ts
- PostgreSQL dont support Join in Delete (https://www.postgresqltutorial.com/postgresql-delete-join/) so I implements the support of using to do the same thing in two king : implicit and explicit methods.
So implicit method, with usual join methods work: 
```javascript
qb()
.del()
.from('users')
.join('photos', 'photos.id', 'users.id')
.where({ 'user.email': 'mock@example.com' })
```
and will generate the query with 'using' and 'where' to work in PostgreSQL.
It will general the same query that explicit form:
```javascript
qb()
.del()
.from('users')
.using('photos')
.whereRaw('photos.id = users.id')
.where({ 'user.email': 'mock@example.com'})
```
- ~~I dont want to go in intrusive and complex implementation (no new kind of joins...) so I just add small using method in querybuilder and make …
=> Support Joins and Using syntax for PostgreSQL Delete Statement (#4591)

lib/dialects/mssql/query/mssql-querycompiler.js, lib/dialects/mysql/query/mysql-querycompiler.js, lib/dialects/oracle/query/oracle-querycompiler.js, lib/dialects/sqlite3/query/sqlite-querycompiler.js, lib/query/querybuilder.js, lib/query/querycompiler.js, test/unit/query/builder.js, types/index.d.ts
- Allowing raw limit and offset by setting a skipBinding parameter.
- Add cockroachDb client in builder.js file.
- Closes #4805
=> Allow skip binding in limit and offset #4805

lib/dialects/mssql/schema/mssql-tablecompiler.js, lib/dialects/mysql/schema/mysql-tablecompiler.js, lib/dialects/oracle/schema/oracle-tablecompiler.js, lib/dialects/postgres/schema/pg-tablecompiler.js, lib/dialects/redshift/schema/redshift-tablecompiler.js, lib/dialects/sqlite3/schema/sqlite-tablecompiler.js, test/integration2/schema/misc.spec.js, test/unit/schema-builder/mssql.js, test/unit/schema-builder/mysql.js, test/unit/schema-builder/oracledb.js, test/unit/schema-builder/postgres.js, test/unit/schema-builder/redshift.js, test/unit/schema-builder/sqlite3.js
- Closes https://github.com/knex/knex/issues/4820
- Callback for create table like is in index.d.ts Typescript but not implemented.
- Now, callback add columns in the new created table (add columns in the query or generate alter table queries).
=> Add columns in create table like #4820

lib/query/querycompiler.js, test/unit/query/builder.js, types/index.d.ts
- Accept Raw value in onIn join clauses.
- Close #4285
=> Accept Raw on onIn joins #4285

lib/dialects/mssql/schema/mssql-viewcompiler.js, lib/schema/viewcompiler.js, test/integration2/schema/views.spec.js, test/unit/schema-builder/mssql.js, test/unit/schema-builder/mysql.js, test/unit/schema-builder/oracledb.js, test/unit/schema-builder/postgres.js, test/unit/schema-builder/redshift.js, test/unit/schema-builder/sqlite3.js
- Closes #4827 
- Now, `view.columns()` is optional when creating views
=> Make view columns optional in create view like #4827

lib/migrations/migrate/Migrator.js, lib/migrations/migrate/migration-list-resolver.js, lib/migrations/migrate/table-creator.js, test/integration2/migrate/migration-integration.spec.js
- Problem : During migration, the _insertLockRowIfNeeded function try to make select statement without FROM clause. That works in some db but no in Oracle and MariaDB (you need to use DUAL).
- I rewrite the _insertLockRowIfNeeded  to make it works in any db (no database specific logic)
- Closes #4864 #4844 #4835
=> Insert lock row fix during migration

lib/dialects/mysql/schema/mysql-tablecompiler.js, test/unit/schema-builder/mysql.js
- Set comment limit size from 60 to 1024.
- Closes #4863
=> Set comment size warning limit to 1024 in MySQL

lib/dialects/mssql/schema/mssql-columncompiler.js, lib/dialects/redshift/schema/redshift-columncompiler.js, lib/knex-builder/FunctionHelper.js, lib/schema/columncompiler.js, package.json, test/integration2/query/misc/additional.spec.js, test/unit/schema-builder/mssql.js, test/unit/schema-builder/mysql.js, test/unit/schema-builder/oracledb.js, test/unit/schema-builder/postgres.js, test/unit/schema-builder/redshift.js, test/unit/schema-builder/sqlite3.js, types/index.d.ts
- Add useBinaryUuid option in 'uuid' function.
- If this option is 'true' use 'binary(16)' type (other than PG).
- Closes #1778
=> Add binary uuid option #1778

test-tsd/transaction.test-d.ts, types/index.d.ts
- Fix returning method types
- Closes #4879
=> Returning method types

test-tsd/tables.test-d.ts, types/index.d.ts, types/test.ts
This fixes the typing of `.columnInfo` as mentioned in #4228 
According to [docs](https://knexjs.org/#Builder-columnInfo) It should return either an object with `ColumnInfo` for all properties or  a single `ColumnInfo` if a `column` is provided
* Added function overload typing with and without `column`
* Use `keyof Resolve<TRecord>` to resolve available keys if there are typings within the `Tables`
* Fixed `dtslint` type test and added new tests in `test-tsd`
=> Fix #4228 Improved columnInfo type

lib/schema/tablebuilder.js, test/integration/logger.js, test/integration2/schema/misc.spec.js, test/unit/schema-builder/postgres.js, types/index.d.ts
- I remake a PR to finish previous work of @Vilkas67 (I make bad rebase on https://github.com/knex/knex/pull/4553, sry for inconvenance).
- Doc : https://github.com/knex/documentation/pull/358
=> Add camel case to timestamps method

lib/dialects/mssql/schema/mssql-tablecompiler.js, test/integration2/dialects/mssql.spec.js, test/unit/schema-builder/mssql.js, types/index.d.ts
MSSQL supports both unique indexes and unique constraints. One of the issues we found was unique index (current implementation) cannot be used with foreign key relationships. We must use unique constraints instead.
This is all based on issue #4825
I thought I'd give it a go and update the way MSSQL handles `table.unique`. This is my first PR here so please let me know if there's anything missing, which I'm sure there is.
I created a new test which seems to work fine 🤞
=> Added support for MSSQL unique constraint

lib/dialects/sqlite3/schema/ddl.js, lib/dialects/sqlite3/schema/internal/sqlite-ddl-operations.js, lib/dialects/sqlite3/schema/sqlite-compiler.js, lib/execution/runner.js, lib/schema/compiler.js, test/integration2/schema/foreign-keys.spec.js, types/index.d.ts
Some notes/questions:
- Is it safe to execute raw queries directly on the client?
- What was the reasoning behind doing `disableProcessing()` / `enableProcessing()` in `getTableSql()`? It seems like this does not work when using the client directly instead of through a transaction.
- Unless I am missing something, with this change `reinsertMapped()` should be treated like a critical section, so another invocation of the function can't interfere with the procedure of querying, disabling and reenabling foreign key constraint enforcement.
- When using indices, the manual foreign key check will likely fail as they are not recreated for the new table. (According to the [SQLite Docs for ALTER TABLE](https://sqlite.org/lang_altertable.html) this also applies to triggers and views, but I'm not …
=> Fix SQLite foreign key constraints when altering a table

lib/dialects/cockroachdb/crdb-tablecompiler.js, lib/dialects/postgres/schema/pg-tablecompiler.js, scripts/docker-compose.yml, test/integration2/schema/checks.spec.js
Related: [4874](https://github.com/knex/knex/pull/4874)
=> feat: Checks Constraints Support for CockroachDB

lib/dialects/mssql/schema/mssql-columncompiler.js, lib/dialects/mysql/schema/mysql-columncompiler.js, lib/dialects/mysql/schema/mysql-tablecompiler.js, lib/dialects/oracle/schema/internal/trigger.js, lib/dialects/oracle/schema/oracle-columncompiler.js, lib/dialects/oracle/schema/oracle-tablecompiler.js, lib/dialects/postgres/schema/pg-columncompiler.js, lib/dialects/sqlite3/schema/sqlite-columncompiler.js, lib/dialects/sqlite3/schema/sqlite-tablecompiler.js, lib/schema/columncompiler.js, lib/schema/tablecompiler.js, test/integration2/schema/primary-keys.spec.js, test/unit/schema-builder/mysql.js, test/unit/schema-builder/oracle.js, test/unit/schema-builder/sqlite3.js
- Resolve the case when a increments column is created in same time that primary keys. Now you can specify a increments columns with or without primary keys: 
* If a primary key is specified, the increment column is added to composite key,
* If a primary key is not specified, the increment column is set to primary key.
This two cases works :
```js
knex.schema.createTable('table_multiple_keys', function (t) {
t.primary(['id', 'second_id', 'other_col']);
t.increments('id');
t.string('second_id', 16).notNullable();
t.integer('other_col').notNullable();
});
```
```js
knex.schema.createTable('table_multiple_keys', function (t) {
t.primary(['second_id', 'other_col']);
t.increments('id');
t.string('second_id', 16).notNullable();
t.integer('other_col').notNullable();
});
```
- Solve tricky cases …
=> Create multiple PKs with increments

lib/dialects/sqlite3/schema/ddl.js, lib/dialects/sqlite3/schema/internal/sqlite-ddl-operations.js, test/integration2/schema/alter.spec.js, test/integration2/schema/foreign-keys.spec.js, test/integration2/schema/misc.spec.js, test/integration2/schema/set-nullable.spec.js
This bug was reported at directus/directus#10878.
=> Fix executing sqlite ddl comands when the table name is a substring of "CREATE TABLE"

lib/dialects/sqlite3/schema/sqlite-compiler.js, lib/execution/internal/query-executioner.js, test/integration2/schema/misc.spec.js
Currently, the `wrapIdentifier` option does not apply for SQLite `db.schema.hasTable`.
For example, even if we set `wrapIdentifier` to parse identifiers to snake case, we'd get the following:
```js
db.schema.hasTable('infoBoxes').toString()
> select * from sqlite_master where type = 'table' and name = 'infoBoxes'
```
This PR fixes this by enabling the wrap for SQLite Compiler:
```js
db.schema.hasTable('infoBoxes').toString()
> select * from sqlite_master where type = 'table' and name = 'info_boxes'
```
Fix #4898
=> Enable wrapIdentifier for SQLite .hasTable

lib/dialects/sqlite3/query/sqlite-querycompiler.js, test/unit/query/builder.js
Returning is supported by sqlite3 in the current version.
Reference: https://sqlite.org/lang_returning.html
Discussion: https://stackoverflow.com/a/67644622/3156509
=> remove outdated warning message

lib/migrations/migrate/Migrator.js
This was caused by this change 1.0
> Changed Migrator to return list of migrations as objects consistently.
I'm not sure how / if I should add tests for this. Let me know if you'd like them :)
This fixes the following error:
```
$ (createdb luma-test &> /dev/null || true) && knex migrate:latest --env test && node -r esbuild-register ./node_modules/knex/bin/cli.js seed:run --env test --specific=seed_db.ts && NODE_ENV=test jest --runInBand
Using environment: test
The migration directory is corrupt, the following files are missing: [object Object]
Error: The migration directory is corrupt, the following files are missing: [object Object]
at validateMigrationList (/Users/victor/Code/luma/node_modules/.pnpm/knex@1.0.1_pg@8.7.1/node_modules/knex/lib/migrations/migrate/Migrator.js:566:11)
at …
```
=> Fix error message for missing migration files

types/index.d.ts
Fixing typo:  `whereIlike` to `whereILike` in types.
Changes introduced in https://github.com/knex/knex/pull/4779
=> WhereILike - Fix typo in types

lib/dialects/sqlite3/index.js, lib/dialects/sqlite3/query/sqlite-querybuilder.js, lib/query/querybuilder.js, lib/query/querycompiler.js, test/integration2/query/select/selects.spec.js, test/unit/knex.js, test/unit/query/builder.js, types/index.d.ts
- Add withMaterialized and withNotMaterialized functions for PG and SQLite to add 'materialized' and 'not materialized' keywords with WITH/CTE (see https://www.postgresql.org/docs/12/queries-with.html).
- Close https://github.com/knex/knex/issues/4470
=> Support of MATERIALIZED and NOT MATERIALIZED with WITH/CTE

lib/dialects/postgres/query/pg-querycompiler.js, lib/dialects/sqlite3/query/sqlite-querycompiler.js, lib/query/querycompiler.js, test/integration2/query/insert/inserts.spec.js, test/unit/query/builder.js, types/index.d.ts
- Add support of "raw" in onConflict clause (support of onConflict where conditions, for partial indexes)
- Closes https://github.com/knex/knex/issues/4590
=> Add raw support in onConflict clause

lib/dialects/postgres/schema/pg-tablecompiler.js, lib/schema/columnbuilder.js, test/integration2/schema/set-nullable.spec.js, test/unit/schema-builder/postgres.js, types/index.d.ts
- Fix https://github.com/knex/knex/pull/4730/files#r791157891
- And I think we are good for an 1.0.2 (doc here : https://github.com/knex/documentation/pull/385)
=> Add alterType and update index.d.ts for alter function

lib/schema/tablecompiler.js, test/integration2/query/insert/on-conflict-deferred.spec.js
Postgresql requires that deferrable appear after on update/on delete, the current order fails with:
```
error: alter table "smtp_servers" add constraint "smtp_servers_email_channel_foreign" foreign key ("email_channel") references "email_channels" ("id") deferrable initially deferred  on update cascade on delete cascade - syntax error at or near "on"
```
Moving the deferred clause to the end works as intended.
=> move deferrable to after on update/on delete

lib/dialects/better-sqlite3/index.js, test/integration2/schema/misc.spec.js
This is an extremely small pull request in accordance with issue #4955; if there is a design reason that that issue is misguided, feel free to squash it. The existing tests for better-sqlite3 still pass; maintainers should feel free to let me know if I should add anything to the tests to check this thing (presumably to test\unit\schema-builder\better-sqlite3.js?)
=> Same boolean handling in better-sqlite3 as in sqlite3

lib/query/querycompiler.js, test/integration2/query/select/where.spec.js, test/unit/query/builder.js
- Json values for Json functions now support Json in string format (not only json object).
- `await knex('table_name').whereJsonSupersetOf('path', "hello")` is always not supported (regarding @> Postgres documentation, this notation doesn't make sense, `whereJsonSupersetOf` checks two valid json objects).
- Closes https://github.com/knex/knex/issues/4979
=> Support string json in json values

lib/dialects/cockroachdb/crdb-querycompiler.js, lib/dialects/oracledb/query/oracledb-querycompiler.js, lib/dialects/postgres/query/pg-querycompiler.js, lib/query/querycompiler.js, test/integration2/query/select/selects.spec.js, test/unit/query/builder.js
- Fix order nulls in PostgreSQL (mutualize with OracleDB syntax)
- Closes #4837
=> Fix Order nulls in PostgreSQL

ECOSYSTEM.md
Mention (knex-firebird-dialect)[https://github.com/Tomas2D/knex-firebird-dialect] library in ECOSYSTEM.md
Related to following issues: #691, #2766, #3511
=> docs: Add Firebird dialect to ECOSYSTEM.md

lib/dialects/cockroachdb/crdb-querycompiler.js, lib/dialects/postgres/query/pg-querycompiler.js, test/integration2/query/select/where.spec.js, test/util/dataInsertHelper.js
This PR fixes 2 bugs I've found working with where clauses build with 'whereJsonPath' for postgres database:
1.  If a passed value is a number, it is casted to integer or float on postgres side. However, is casted also if value only starts with a number but contains also letters or other characters. This is because **parseInt** and **parseFloat** are used for value check and they just ignore all non-numeric characters.
2. Queries using 'orWhereJsonPath' don't have proper binding for value. 
For 1st I've added additional check if value is not a NaN and for 2nd I've fixed arguments passed in query builder method.
=> Fix whereJsonPath queries for postgres and cockroachdb

lib/query/querybuilder.js, test/integration2/query/select/where.spec.js
- Closes https://github.com/knex/knex/issues/5020
=> Fix orWhereJsonPath clause

test-tsd/types.test-d.ts, types/index.d.ts, types/test.ts
Closes #4942
With the release of v1, the methods for `returning` changed a bit. However, the type definitions were not updated.
Reviewing the rest of the types I found that the `onConflict` clause was setting the Result type with the passed conflicting columns. This looked very strange and at least when using postgres as the backend, this is not the case.
Also, (this is another issue) when not using the "returning", the types specify that the result is `number[]`. However (at least using pg) a Result object is returned instead.
```ts
const users = await knex
.from<Contact>("contact").insert([{
email: "xxxx@gmail.com",
first_name: "jeff"
}])
// users is suposed to be a number[];
console.log(users)
// Result {
//   command: 'INSERT',
//   rowCount: 2,
//   oid: 0,
//   rows: [],
// …
```
=> Fix types for "returning" methods

types/index.d.ts
As per the documentation the callback is supposed to be optional. Leaving the callback as undefined works fine functionally but TypeScript marks it as invalid.
This update is to correct the types file.
=> createTableLike callback should be optional

lib/query/querybuilder.js, test/integration2/query/update/updates.spec.js
- Stringify a json value in update query to avoid exploit.
- Closes #5059
=> Stringify json value in update

test-tsd/types.test-d.ts, types/index.d.ts, types/test.ts
The default generic parameters of `Knex` didn't match the generic parameter types of `knex`. This becomes relevant with TypeScript 4.6 for `k: Knex = knex()` to work.
We can't change `knex`'s declaration from `TResult = unknown[]` to `TResult = Record<string, any>[]` because other types like `DeferredKeySelection.ReplaceBase` specifically look for `unknown`. Instead, this commit changes `Knex` to use `TResult = any[]`.
This works with TypeScript 4.6. Added both tsd and dtslint tests (tsd doesn't support TS 4.6 yet). Also tested this change in a larger codebase and confirmed that nearly all TS 4.6 errors were addressed.
Follow-up to https://github.com/knex/knex/pull/4933.
=> [types] Make Knex's default generic parameter types be assignable to knex's (TypeScript 4.6)

test/integration2/query/select/selects.spec.js
- All .then functions are replaced by async / await syntax.
- First PR for switch all tests with async / await syntax (#3170)
=> Async/await in tests : selects.spec.js

lib/query/querycompiler.js, test/integration2/query/select/unions.spec.js, test/unit/query/builder.js
- Fix errors with wrapped unions.
- Closes #5061
- Related #1630
=> Wrapped Unions Fixes

lib/client.js, lib/dialects/sqlite3/index.js, test/unit/knex.js
- Fix the error message when sqlite3 driver don't exist.
- Relates #5002
- If I remove my vscode/sqlite3 install, I have the error. If I reinstall it via "npm install @vscode/sqlite3 --save" it's ok for me. I miss something ?
=> Fix @vscode-sqlite3 error message

.github/workflows/coverage.yml
- Active existing coveralls Github Action on pull requests to have code coverage control (avoid no covered code)
=> Active Coveralls on Pull Requests

bin/cli.js, bin/utils/cli-config-utils.js, test/cli/migrate-make.spec.js
- During migrate:make client is set to 'sqlite3' only if client
is not setted in options and configuration.
- Closes #5102
=> No client override during migrate:make

bin/cli.js, bin/utils/cli-config-utils.js, test/cli/migrate-make.spec.js, test/cli/seed-make.spec.js
This is a proposed fix for #5102 .
Recent changes to how command line options are prioritized relative to configured options in the CLI exposed a bug in `migrate:make`. If a command line `client` option was not supplied, the CLI would use `sqlite3` instead of whatever is configured in the configuration file. This causes an error in environments where the optional sqlite3 peer dependency is not installed.
This PR alters the CLI initialization for commands that don't care about the client (`migrate:make` and `seed:make`) to skip an early check for the presence of a `client` option, and supply a default value of `sqlite3` later in the initialization process where it won't override a configured value.
=> Fix cli migrate:make sqlite dependency

test-tsd/tables.test-d.ts, types/index.d.ts
When using the `useNative` and `existingType` options, the value isn't utilized.
The documentation uses `null` as an example, this commit allows said example
to pass in typescript
close #5114
=> FIX 5114: Allow `null` as a valid value for `.enu`/`.enum`

.github/workflows/coverage.yml, .github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
Replace Node 17 in CI with Node 18, which was released today.
=> CI: Add Node 18, drop Node 17

lib/dialects/index.js, lib/knex-builder/internal/config-resolver.js
Previous this repo has imported Dialect objects via dynamically generating a string to require. This does not work well with compilers like ncc. To solve this and make for a better development experience we add the function `getDialectByNameOrAlias` to safely import Dialects while making requirement paths static for better compiler and bundler experiences.
=> Added getDialectByNameOrAlias and converted repo to use it.

lib/dialects/mysql/schema/mysql-compiler.js, test/integration2/schema/misc.spec.js
I find this problem when i use strapi who will try to create column `a_id` although i already have a column `a_Id` on mysql.
This is my first pull request, if there are any error, please  give me a change to correct it.
=> fix: mysql hasColumn Error.(hasColumn `a_id` but hasColumn('a_Id') is false)

lib/dialects/postgres/schema/pg-compiler.js, test/unit/schema-builder/postgres.js, types/index.d.ts
PostgreSQL has a support to refresh the materialized view concurrently: [Documentation](https://www.postgresql.org/docs/current/sql-refreshmaterializedview.html)
This PR adds an optional boolean argument to the `refreshMaterializedView` method to refresh the view concurrently for PostgreSQL
=> Refresh materialized view concurrently for PostgreSQL

lib/dialects/oracledb/index.js, test/integration2/dialects/oracledb.spec.js
1. #4869
1. Fixes `parameter` function for Oracledb dialect to properly handle Blobs instead of replacing them with `EMPTY_BLOB()` in `lib/dialects/oracledb/index.js`.
2. Created new test file to verify new behavior in `test/integration2/dialects/oracledb.spec.js`.
=> Fix #4869, oracledb correctly INSERTS Buffer

package.json
The seeder entry is the only one really required to easily build knex for
the browser without shimming `fs`, but I updated the migrations path to
match.
However, there's also `lib/migrations/seed/seed-stub.js`, which actually
seems to provide errors when attempting to use the seed functionality in
a browser, but isn't actually used anywhere
I'm not exactly sure which way is intended.
If the seed stub is intended, then I'll change it to use that, otherwise it should probably be removed.
=> Use correct paths in package.json browser field

lib/dialects/mysql/query/mysql-querycompiler.js, test/integration2/query/misc/additional.spec.js
Fixes: #5154
---
If we look at https://jira.mariadb.org/browse/MDEV-13132, a bug was fixed to properly quote default value to be able to determine expressions vs null. This meant due to the strict typing that `'NULL'` was not detected as null and thus attempted to be included as a default value even against a not-nullable table here - https://github.com/knex/knex/blob/master/lib/schema/tablecompiler.js#L333
I've never worked with this project, but my Ghost blog stopped working and while Ghost is dropping Maria and I'm sad about that. I cannot complain seeing how I paid $0, so I'm attempting to fix to resolve this issue.
I added a test which I believe resolves issue, but to truly replicate you need Maria 10.2.6+ and I don't even see that in the integration suite (the docker). So while I …
=> Fixes Maria issue with 'NULL' returned instead of NULL on MariaDB 10.2.6+

lib/dialects/mssql/schema/mssql-compiler.js, test/integration2/schema/misc.spec.js, test/unit/schema-builder/mssql.js
This PR fixes an issue where `hasTable` would return false if used on `withSchema`. This happens only on MSSQL.
I added a new test to ensure the behavior and also cleaned the test file a bit.
Closes #5170
=> MSSQL: Fix .hasTable result when using .withSchema

lib/knex-builder/internal/parse-connection.js, test/tape/parse-connection.js
The existing parser implementation does not parse the nested properties from the connection string for MSSQL ([Tedious](https://tediousjs.github.io/tedious/api-connection.html) supports properties like `InstanceName`, `TDS Packet size`, `readOnlyIntent` under `options` key, which can not be passed to knex over connection string at the moment). 
**Example Connection string :** 
`mssql://user:password@host/database?domain=testDomain&options={"instanceName": "TestInstance001", "readOnlyIntent": true}'`
**Actual Config**
```
{
user: 'user',
password: 'password',
database: 'database',
server: 'host',
domain: 'testDomain',
options:'{"instanceName": "TestInstance001", "readOnlyIntent": true}'
}
```
**Expected Config**
```
{
user: 'user',
password: 'password',
database: 'database',
server: …
```
=> feature  - Support for JSON parameter in MSSQL connection string

lib/dialects/sqlite3/index.js, lib/dialects/sqlite3/query/sqlite-querycompiler.js
Update an out-of-date documentation reference inside warning logged when `useNullAsDefault` configuration property is undefined for SQLite3 client.
=> chore: update docs reference in sqlite3 warning

types/index.d.ts
Allowing custom object type in bind parameter for raw query. For example when calling oracle stored procedure like 
```
Person.knex().raw('CALL TEST_PACKAGE.TEST(?, ?)', [
{ type: OracleDB.CURSOR, dir: OracleDB.BIND_OUT },
{ type: OracleDB.NUMBER, dir: OracleDB.BIND_OUT },
]).then(res => {
console.log(res)
})
```
=> Updating raw query bind parameter type

lib/dialects/postgres/schema/pg-tablecompiler.js, test/integration2/schema/misc.spec.js, test/unit/schema-builder/postgres.js
This is a continuation of my work in #5212. It's aimed at really fixing #5211
* #5212
* #5211
#5212 implemented `uuid(<id>, { primaryKey: true })` for allowing to use `PRIMARY KEY` on the field type in the column declaration. This aims at adding support for a distinct `PRIMARY KEY` constraint during table creating.
Both of these solutions want to make life easier for folx using CockroachDB which autogenerates a `rowid` primary if none is specified during initial table creating.
I'm creating this as a draft PR, I'll finalize it once the accompanying docs pr is also done and CI is green.
Please let me know if this is a feasible way to go forward and if there is some special consideration needed for any non-postgresql postgres flavours (i don't know them well).
=> feat: inline primary key creation for postgres flavours

types/index.d.ts
Typescript 4.8 assumes that unconstrained types extend `unknown`, not `{}` (which is `unknown` minus `null` and `undefined`). However, many uses still need to extend `{}`. This PR does that explicitly for knex types.
See https://devblogs.microsoft.com/typescript/announcing-typescript-4-8-beta/#unconstrained-generics-no-longer-assignable-to
=> Update types for TS 4.8

lib/dialects/sqlite3/index.js, lib/dialects/sqlite3/query/sqlite-querycompiler.js, test/integration2/query/insert/inserts.spec.js, test/integration2/query/misc/additional.spec.js, test/integration2/query/update/updates.spec.js
The `RETURNING` SQL statement is now supported for insert and update queries.
Fixes #4370.
=> Support returning with sqlite3 and better-sqlite3

types/index.d.ts
Fix `AnalyticFunction` type affecting `rowNumber`, `rank` and `DenseRank`. 
I discovered during development, where TypeScript complains:
```
Argument of type '{ column: string; order: "desc"; }' is not assignable to parameter of type '"oid" | "oid"[] | { columnName: "oid"; order?: "asc" | "desc" | undefined; nulls?: "first" | "last" | undefined; }'.
Object literal may only specify known properties, and 'column' does not exist in type '"oid"[] | { columnName: "oid"; order?: "asc" | "desc" | undefined; nulls?: "first" | "last" | undefined; }'.
```
However, they are clearly using `column` in the code:
https://github.com/knex/knex/blob/4c79ac1fe64618ed0d1bd63dcae3f9b812827f69/lib/query/analytic.js#L21-L49
Also, this can verify that using `columnName` is apparently incorrect:
=> Fix type for AnalyticFunction

types/index.d.ts, types/test.ts
👋 Hi folks, thanks for a great library! I came across what looks like a typing bug to me:
---
The first overload of TypePreservingAggregation (taking columnName and options) used `Readonly<TKey>` for the columnName type. In this context, `TKey` is supposed to be a single column name, but `Readonly<TKey>` maps over the full constraint of `keyof ResolveTableType<TRecord>`.
This results in `TKey` being a union of all keys in the table, rather than a single key. Because of this, the result type ends up being a union of all values in the table.
The fix is to remove the `Readonly` type, which is fine since `TKey` is a string and not an object like in the other overloads.
=> Infer specific column value type in aggregations

lib/formatter/wrappingFormatter.js
I've been perusing [lgtm](https://lgtm.com/projects/g/knex/knex/?mode=list) and this one might be in the "makes sense" + 'is minimal" category.
let's see if CI/CD agrees
=> chore: remove bindingHolder for proper scoping

lib/dialects/postgres/schema/pg-columncompiler.js, test/integration2/util/knex-instance-provider.js, test/unit/schema-builder/postgres.js, types/index.d.ts
I ran into an issue where my `jsonb` columns are created as `text` when using `pg-mem` in tests and aurora friendly clients like `knex-data-api-client`
It resulted in a lot of `cast blah as jsonb` workarounds, but really, the issue is that under the hood, knex just falls back to `text` data type when it cannot resolve a valid pg version.
This change lets custom clients like `knex-data-api` explicitly state they support `jsonb` instead of passing in a potentially wrong postgres version (think serverless setup)
=> Explicit jsonb support for custom pg clients

lib/dialects/sqlite3/schema/sqlite-tablecompiler.js, test/integration2/schema/alter.spec.js
The `formatDefault()` function expects the type parameter to be a Knex internal type instead of a SQL type.
=> Fix changing the default value of a boolean column in SQLite

lib/dialects/mssql/schema/mssql-tablecompiler.js, lib/dialects/postgres/schema/pg-tablecompiler.js, lib/dialects/sqlite3/schema/sqlite-tablecompiler.js, test/integration2/schema/misc.spec.js, test/unit/schema-builder/mssql.js, test/unit/schema-builder/postgres.js, test/unit/schema-builder/sqlite3.js, types/index.d.ts
Adds MSSQL, PostgreSQL, and SQLite support for partial unique indexes, heavily based on #4768.
The Postgres driver defaults to creating a unique constraint instead of an index, so Postgres support for `useConstraint` was added, defaulting to `true` without predicate and `false` with predicate. The alternative would be to always default to `useConstraint: true`, but then `predicate` would error by default unless `useConstraint: false` is explicitly specified. Dunno which is better.
Docs: knex/documentation#449
Fixes #4870
=> feat: support partial unique indexes

test-tsd/pg-config.test-d.ts, types/index.d.ts
expirationChecker currently works with PgConnectionConfig if you ignore the type error.
=> fix: add missing type for 'expirationChecker' on PgConnectionConfig

lib/client.js
Important for applications where high pool contention is expected, and completion is favored over latency.
=> Fixes unexpected max acquire-timeout

lib/.gitignore, lib/query/querybuilder.js, test/integration2/query/select/where.spec.js, test/unit/query/builder.js
Fixed `orWhereJson...` functions like `orWhereJsonSupersetOf`, `orWhereJsonNotSupersetOf`, `orWhereJsonSubsetOf` and `orWhereJsonNotSubsetOf`,
I found a issues about `orWhereJsonSupersetOf` and `orWhereJsonSubsetOf` which behaved the same as `whereJsonSupersetOf` and `whereJsonSubsetOf`
=> Fix: orWhereJson Functions

lib/migrations/migrate/stub/mjs.stub
In a similar style to #4809, this adds TS flavour JSDoc to the mjs migration stub.
=> Add JSDoc (TS Flavour) to mjs stub file

lib/client.js, test/integration2/query/insert/inserts.spec.js
Reverts https://github.com/knex/knex/pull/5321
Fix https://github.com/knex/knex/issues/5365
Fix https://github.com/knex/knex/issues/5430
Adds new test, which I confirmed fails without the changes to `lib/client.js`
=> Fix Postgres Malformed array literal 2.4.0 Regression

test/integration2/query/insert/inserts.spec.js
TLDR: add various tests case for the PR https://github.com/knex/knex/pull/5431 (rollback of https://github.com/knex/knex/pull/5321)
- insert tests for array of object into `text array` column #5430
- insert tests for array of integer into `integer array` column #5365
- insert tests for array of string into `text array` column #5365
- insert tests for json object into `jsonb` column
the PR https://github.com/knex/knex/pull/5431 by @caseywebdev should be merged first
A little bit more explanation: 
#5365 : user want to insert array of string into `text array` column, or array of integer into `integer array` column, which is valid and should be inserted, but the PR https://github.com/knex/knex/pull/5321 merged sometime ago break it (it will always stringify the array to json string) …
=> tests(insert): add insert tests for json, text array and integer array

CHANGELOG.md
The newest dates in `CHANGELOG.md` reference 2022, but I believe it should be 2023.
=> Update dates in Changelog for 2023

types/index.d.ts
These are just changes to the type definitions, the documentation is already correct, especially in the case of `unique`.
- These TableBuilder methods return the SchemaBuilder.
- `unique` accepts `string`, `string[]`, or `Raw[]`.
=> Update typescript definitions to return builders

.github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/integration-tests.yml, .github/workflows/linting.yml, .github/workflows/unit-tests.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows. 
GitHub Actions workflows have a GITHUB_TOKEN with `write` access to multiple scopes. 
Here is an example of the permissions in one of the workflows:
https://github.com/knex/knex/runs/8121315545?check_suite_focus=true#step:1:19
After this change, the scopes will be reduced to the minimum needed for each workflow. 
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced. 
- GitHub recommends defining minimum GITHUB_TOKEN permissions. 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_tok …
=> Add minimum GitHub token permissions for workflows

lib/dialects/oracledb/schema/oracledb-columncompiler.js, test/unit/schema-builder/oracledb.js
The `is json` check on json fields for OracleDB should be implicitly added after the default values and not with the field type.
The issue was found when running tests in https://github.com/directus/directus/pull/15889.
=> Use implicit check on json fields for OracleDB

lib/dialects/sqlite3/schema/internal/sqlite-ddl-operations.js, package.json, test/integration2/migrate/alter-table-ignore-case-sensitive/01_create.js, test/integration2/migrate/alter-table-ignore-case-sensitive/02_add_column.js, test/integration2/migrate/migration-integration.spec.js
Here is an example how to reproduce the issue.
https://github.com/zydmayday/learn-knex/blob/main/knex/knex.test.ts#L34-L44
Use sqlite3 as database for testing, and has some migration scripts for setting up tables.
If we have one script create a table called "some_table(https://github.com/zydmayday/learn-knex/blob/main/knex/migrations/1_create_table.ts)",
and another script alter table but using table name "Some_Table(https://github.com/zydmayday/learn-knex/blob/main/knex/migrations/2_add_columns.ts)".
Then after running jest, we will have the following error logs.
```
TypeError: Cannot read properties of undefined (reading 'sql')
at client.transaction.connection (node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:56:13)
```
Because the related SQL script is case sensitive, change it to …
=> [Sqlite3] Fix can not get table sql because of case sensitive

lib/dialects/mssql/query/mssql-querycompiler.js, lib/dialects/oracle/query/oracle-querycompiler.js, lib/query/querybuilder.js, lib/query/querycompiler.js, test/integration2/query/select/selects.spec.js, test/unit/query/builder.js, types/index.d.ts
This is a rebased and updated version of #2815 that fixes #1982.
About parameter binding, I did tried to escape them, but I doesn't works for mysql. So I forbidden any ?.
=> Add ability to prepend query comments

types/index.d.ts
Hello. This PR is similar to https://github.com/knex/knex/pull/5512, but updates the `decrement` method.
=> Add object syntax overload to decrement method

.github/workflows/unit-tests.yml, lib/dialects/mysql2/index.js
- With Mysql2 > 3.2.0 require('mysql2') breaks with Node 12.
- Add an error during mysql2 driver initialization
- Install mysql2@3.2.0 during unit test with Node12.
Close #5578
=> Mysql2 require breaks with Node 12

lib/dialects/better-sqlite3/index.js, test/db-less-test-suite.js, test/unit/dialects/better-sqlite3.js, types/index.d.ts
Better-SQLite3 [supports a `readonly` option](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#new-databasepath-options) on initialization. This PR lets Knex users set that option.
(The automatic code formatter wanted to reflow some lines unrelated to the new code. I've split those automated changes out into a separate commit for clarity and to preserve author attribution on the changed lines.)
Docs PR is in knex/documentation#505.
=> Add readonly option to Better-SQLite3

test/unit/dialects/better-sqlite3.js
Follow-up to #5530. Better-SQLite3 tests weren't passing on all platforms due to a path / sequencing issue. This PR addresses the issue by using `path.resolve()` instead of constructing paths by string addition, and by ensuring that an empty database exists no matter what order the tests run in.
=> Ensure test DB exists at correct path in better-sqlite3 tests

lib/client.js, lib/dialects/mssql/index.js, lib/knex-builder/make-knex.js, lib/util/security.js, test/db-less-test-suite.js, test/integration/connection-config-provider.js, test/integration2/query/misc/additional.spec.js, test/unit/util/security.js
We detected that under certain conditions, passwords could be leaked through logs, when executing code such as:
```typescript
const query = knex('myTable').select('*');
logger.debug({ query }) // passwords are leaked here
```
In our case, the logger was `Pino`, this problem doesn't necessarily happen with other loggers (as they might use different
serialisation methods).
- password fields are not leaked anymore. Fixes #5560 .
- accepts configuration objects where the password field exists but it is non-enumerable (this might happen when lib users are trying to prevent the same previous problem, but at a higher level).
- marks the password field as non-enumerable when possible, to avoid potential leaks through logs.
- adapts tests
- add new regression test
=> fix(security): avoid password leaks on query logs

lib/dialects/postgres/schema/pg-tablecompiler.js, test/unit/schema-builder/postgres.js
This is a fix for the issue described here: https://github.com/knex/knex/issues/5217
The `indexType` option was being used for the storage type instead of `storageEngineIndexType` as in the [documentation](https://knexjs.org/guide/schema-builder.html#index).
I've change the method to follow the options as in the documentation. There also appeared to be to option to pass in a string as instead of an options object. I've left this as the `storageEngineIndexType` as it was previously, although this is not mentioned in the documentation.
I've also updated the tests and added a new one for this scenario.
=> fix: creating a unique index in postgres using the index method

bin/cli.js
ES Modules are supported as migrations and seed file types (thanks to [prior PR](https://github.com/knex/knex/pull/4631)) but it didn't show up in the supported file types on the command-line.
=> fix: add mjs extension type

types/index.d.ts
All details are in https://github.com/knex/knex/issues/5593.
I reviewed other commits that fixed typings, and it seems like only `types/index.d.ts` gets changed for those, but let me know if I'm missing something.
=> SchemaBuilder toSql() returns Sql[], not Sql.

lib/dialects/oracledb/index.js, test/integration2/query/update/updates.spec.js
Should fix #3837 so that using update with returning * actually returns an object instead of the number of rows.
Also fixes the bug introduced within https://github.com/knex/knex/pull/3668 that causes the returning * to fail when run within a transaction
=> oracle db returning * fixes

lib/dialects/postgres/index.js
Fixes #5454.
Just needed to attach the error handler _before_ calling `connection.connect()`, in case an error event happens before that finishes. 
The manual test in the linked bug report now works fine. Not sure if it's worth adding a unit test for this specific issue (or how I would even do so). 
This probably isn't a complete solution to the overall problem described there, since AFAIK `terminating connection due to conflict with recovery` shouldn't be possible here—but one thing at a time.
=> fix: prevent uncaught errors

package.json
I assume that `knex.mjs` is missing from published files simply because it is not listed in "files" field of package.json.
Fixes #5354.
=> Add knex.mjs to files in package.json

lib/dialects/postgres/query/pg-querybuilder.js, lib/dialects/postgres/query/pg-querycompiler.js, test/integration2/query/update/updates.spec.js, test/unit/query/builder.js, types/index.d.ts
Documentation PR: https://github.com/knex/documentation/pull/476
Introduces the `updateFrom` querybuilder method for PostgreSQL. This allows the creation of `UPDATE <table> SET <data> FROM <name>` queries, which may reference relations or CTEs outside of the target table.
I opted for creating a new QB method (`updateFrom`) to avoid conflict or weird interactions or unexpected changes to behaviour with the target table already being inferred from `knex(table)`, `knex.table(table)`, etc.
=> feat(pg): implement QueryBuilder#updateFrom

lib/knex-builder/FunctionHelper.js, test/integration2/query/misc/additional.spec.js, test/unit/schema-builder/oracledb.js, test/unit/schema-builder/redshift.js, types/index.d.ts
Meant to be used in the schema creation:
```javascript
await knex.schema
.createTable('users', table => {
table.uuid('id').defaultTo(knex.fn.uuid());
table.string('user_name');
})
```
Can someone confirm that there is no uuid function in Redshift?
=> Add uuid helper function

types/index.d.ts
As per the [documentation](https://knexjs.org/guide/raw.html#raw-parameter-binding), the `bindings` param can be a single value, an array of values, or a dictionary of named binding values.
The type was incorrect, as it implied that one could bind multiple values by passing multiple parameters, rather than using an array:
```ts
// This was OK before, because TS expects (sql: string, ...bindings: RawBinding[])
// Expectation was bindings ['value for a', 'value for 'b']
// Actual was bindings ['value for a'] and the second binding was ignored
knex().raw('select * from table where a = ? and b = ?', 'value for a', 'value for b');
```
With the correct typing, the above code will now throw a type error "Expected 1-2 arguments, but got 3".
=> [TypeScript] Fix raw bindings typing

types/index.d.ts
Currently, the knex type declarations use `export default` as if it were an ES module. This has not mattered up until recently with Node's increased ESM support and TypeScript's `node16` module setting, which is the TypeScript's team [recommended setting](https://github.com/microsoft/TypeScript/issues/52529#issuecomment-1672036026) for Node users.
Bear with me - this is a bit convoluted. Node's [behavior when importing CJS from an ES module](https://nodejs.org/api/esm.html#import-statements) is to make `module.exports` the default export. TypeScript adheres to this, which leads to some weird quirks when we look at knex's type declarations. TS properly detects knex as a CJS module, and when it sees a default export in the declarations, it assumes that the `knex` function is set to …
=> Fix knex d.ts to work with Node16 module mode

CHANGELOG.md
Was reading changelog when `await knex.transaction()` introduced when I found this minor ignorable change 😅
=> Fix Lexical error from "Instaed" to "Instead"

types/index.d.ts
Compiling the file `types/index.d.ts` with version 5.4 of TypeScript (currently nightly) produces the following errors:
```
knex/types/index.d.ts(1241,50): error TS2344: Type 'ResolveTableType<TRecord, "base">' does not satisfy the constraint '{}'.
Type 'unknown' is not assignable to type '{}'.
knex/types/index.d.ts(1256,50): error TS2344: Type 'ResolveTableType<TRecord, "base">' does not satisfy the constraint '{}'.
```
This was caused by [this change](https://github.com/microsoft/TypeScript/pull/56004).
This PR fixes these errors.
=> Fix types for TypeScript 5.4

lib/migrations/migrate/stub/ts.stub
To match `@typescript-eslint/consistent-type-imports` eslint rule.
=> Import knex as type in TS migration template

lib/dialects/mysql/schema/mysql-tablecompiler.js, lib/schema/tablecompiler.js, test/unit/schema-builder/mysql.js
Fixes issue with bigincrements not working when having a composite keys since the alter table is not present for bigincrements as descriped in #5341 .
Also fixes issue when using bigincrements and the field was not added as a primary key. The below currently fails since logic to handle bigincrements in the primary key function is missing.
```
knex.schema.createTable("test_table", table => {
table.primary(['name']);
table.bigincrements('userId');
table.string('name');
}
```
=> Fixed issue with bigincrements not working with composite key in MySQL - #5341

lib/execution/transaction.js, test/integration/execution/transaction.js, types/index.d.ts
Recently our app has had the need to know when the base transaction has committed, regardless of nested transaction levels. This works with `executionPromise` when you're one transaction deep, but if you have nested transactions the `executionPromise` only refers to the inner-most transaction. This change adds a `baseExecutionPromise` property on the transactor that will always reference the outer-most `executionPromise`.
Our specific use case is that we have functions that receive transactions and may open up nested transactions which can open up more nested transactions. Sometimes in those transactions, offline work records are inserted into a queue table to be processed out-of-band of the current transaction. We want to start that work as soon as the transaction is committed, but if we …
=> Add transactor.parentTransaction

lib/dialects/postgres/index.js
This should fix the unhandled error when using Postgres stream with query_timeout.
After the fix, you can use: pipeline API and catch the error on query timeout as expected.
=> fix error on postgres when setting query_timeout

.github/workflows/docs-deploy.yml
so for some reason, `publish_dir` is not using the cwd and need an absolute path
=> update publish directory

lib/formatter/wrappingFormatter.js
When trying to join using the null-safe operator, I'm getting `TypeError: The operator "<=>" is not permitted` despite being a valid value in MySQL 
See https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html#operator_equal-to
=> fix: Fix The operator "<=>" is not permitted in MySQL

lib/migrations/seed/stub/ts.stub
Relates #5741
Saves fixing `@typescript-eslint/consistent-type-imports` eslint rule every time.
=> Import knex as type in TS seed template

docs/src/guide/query-builder.md
Fixed section title `Extending Query Builder`.
Made the section the same level as `Common` and `Where Clauses in the document`
Before it was like this:
=> query-builder.md fix section title
