- index.html
A simple, but useful adjustment.
> Changed absolute path into relative for offline usage

- lib/dialects/sqlite3/schema/ddl.js
Closes #544
Don't know where place test case.
> Fix SQLite dropColumn doesn't work for last column

- CONTRIBUTING.md
- gulpfile.js
- knex.js
- lib/dialects/fdbsql/formatter.js
- lib/dialects/fdbsql/functionhelper.js
- lib/dialects/fdbsql/index.js
- lib/dialects/fdbsql/migrator.js
- lib/dialects/fdbsql/pool.js
- lib/dialects/fdbsql/query.js
- lib/dialects/fdbsql/raw.js
- lib/dialects/fdbsql/runner.js
- lib/dialects/fdbsql/schema/column.js
- lib/dialects/fdbsql/schema/index.js
- lib/dialects/fdbsql/schema/schema.js
- lib/dialects/fdbsql/schema/table.js
- lib/dialects/fdbsql/seeder.js
- lib/dialects/fdbsql/transaction.js
- lib/dialects/fdbsql/utils.js
- test/index.js
- test/integration/builder/additional.js
- test/integration/builder/aggregate.js
- test/integration/builder/deletes.js
- test/integration/builder/inserts.js
- test/integration/builder/joins.js
- test/integration/builder/selects.js
- test/integration/builder/updates.js
- test/integration/schema/index.js
- test/knexfile.js
- test/unit/query/builder.js
- test/unit/schema/fdbsql.js
I've added support for a FoundationDB SQL Layer knex adapter. I tried my best to follow the style of code throughout the project. The FDB SQL layer code was adapted from the PostgreSQL code. I also updated the test directory to include both unit tests and integration tests for the fdbsql adapter.
For more information about the newly supported database, see here: https://foundationdb.com/
Pleas don't hesitate to contact me for questions and comments.
Thanks!
> FoundationDB SQL Layer Adapter

- lib/bin/cli.js
- package.json
> [Knex CLI] Support V8 Flags such as --harmony, etc

- lib/dialects/mysql/index.js
- lib/dialects/oracle/pool.js
- lib/dialects/postgres/pool.js
- lib/dialects/sqlite3/pool.js
- lib/pool.js
- package.json
Passes sqlite and postgres integration tests, leaving it to Travis for the others
> Use Pool2 instead of Generic-pool-redux

- lib/query/compiler.js
- test/unit/query/builder.js
> Fix for out-of-order parameters when using a subquery in 'from'

- lib/dialects/oracle/schema/column.js
- test/unit/schema/oracle.js
> fix float for oracle dialect

- lib/migrate/index.js
- test/integration/migrate/index.js
- test/integration/migrate/test/20150109002832_invalid_migration.js
- test/integration/migrate/test/20150109095253_migration_after_invalid.js
Moved from #622, merging against the "pool" branch which now has savepoint/nested transactions.
> Wraps migrations in transations

- lib/dialects/mysql/schema/tablecompiler.js
- src/dialects/mysql/schema/tablecompiler.js
- test/integration/schema/index.js
link to issue tgriesser/knex/issues/889
> Fixed migration issue renameColumn is failed when there is foreign key reference in another table

- .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
> Use container-based Travis CI to speed-up builds

- lib/dialects/mysql/schema/tablecompiler.js
- src/dialects/mysql/schema/tablecompiler.js
It's my fault that I missed one change in tgriesser/knex#889.
> re-create fk with ref.CONSTRAINT_NAME instead of ref.COLUMN_NAME

- index.html
- lib/query/builder.js
- src/query/builder.js
- test/unit/query/builder.js
As discussed in https://github.com/tgriesser/knex/pull/881#issuecomment-121974392
> Add builder as first parameter to `queryBuilder.modify`

- index.html
I don't know why this wasn't immediately obvious to me, but it wasn't.
EDIT: actually, looks like there is a command line flag that isn't documented. I've added a short sentence on it.
> Specify how migration cli chooses environment

- lib/connection/index.js
- lib/migrate/index.js
- lib/query/compiler.js
- lib/util/parse-connection.js
- src/query/compiler.js
- test/unit/query/builder.js
Hi,
Took the liberty to look into #953 and found the problem as well. Please let me know if there's any issues with this fix.
> Allow zero in join clause, fixes #953

- index.html
This handles https://github.com/tgriesser/knex/issues/1004
> documentation for using JSON array values

- index.html
Adding example on how to execute some code only when all migration files finished their execution
> how to chain migrate sample

- .travis.yml
Ref: https://github.com/nodejs/node/blob/v5.0.0/CHANGELOG.md
> Add Travis testing for Node v5.x

- build/knex.js
- index.html
- lib/connection/index.js
- lib/migrate/index.js
- lib/raw.js
- lib/util/parse-connection.js
- src/raw.js
- test/tape/raw.js
Mainly fixed issue #1003 and added documentation. Also accidentally found bug from named parameter replacement regexp  and wrote tests + fixed that too.
> Fix knex raw indentifier escaping and named parameter regexp and add documentation

- CONTRIBUTING.md
Added some more info the the CONTRIBUTING.md document about Postgres. I got stuck because I didn't have the default user setup.
> Update docs to add details about creating a new postgres user for the tests

- .jshintrc
- lib/connection/index.js
- lib/dialects/postgres/schema/columncompiler.js
- lib/migrate/index.js
- lib/schema/tablebuilder.js
- lib/util/parse-connection.js
- src/migrate/index.js
- test/integration/migrate/index.js
Returns 0 if all migrations are run and DB is up to date. Return negative number if DB is missing migrations. Return positive number if DB is ahead (rare case, e.g. if migrations were run then code is reverted).
> Add migration status method

- index.html
> Add missing `=` in documentation

- index.html
Couldn't find this anywhere in the documentation.
> Add migrate:rollback to CLI section

- index.html
> Add docs for table foreign key modification functions, foreign/dropForeign

- src/transaction.js
@elhigu In regards to #1163 that was merged yesterday, I forgot to take this into consideration. I fixed the same bug for the normal 'query' event back in Sept 2015, so that reminded me..
> Proxy query-error event in transaction

- index.html
- src/util/make-knex.js
> Default batch size 1000 for batchInsert and validate batch size parameter to be > 0

- src/migrate/index.js
- test/integration/migrate/index.js
> Fixed regression running migrations through cli

- index.html
dropForeign in side navbar was dropForeignx
> Fixing typo in documentation

- index.html
deleted 'specifies' from ...object, which may specify specifies the... on line 2616
> 2616: removed double words

- index.html
Added a use case and an example for .returning
> Update docs for returning to include multiple columns

- src/dialects/mssql/query/compiler.js
- src/dialects/mysql/query/compiler.js
- src/promise.js
- src/transaction.js
Minor code cleanup collected while working on the knex code-base and extracted here so it would not unnecessarily pollute other pull requests.
> Code cleanup

- src/dialects/mssql/schema/tablecompiler.js
- src/dialects/mysql/schema/tablecompiler.js
- src/dialects/postgres/schema/tablecompiler.js
- src/dialects/sqlite3/schema/tablecompiler.js
- src/schema/tablecompiler.js
- test/integration/schema/index.js
- test/unit/schema/mssql.js
- test/unit/schema/mysql.js
- test/unit/schema/postgres.js
- test/unit/schema/sqlite3.js
Pull request already described in this previous one #899.
The only difference of this one is that I have rebased the branch with the master.
And already included wrap index in the new mssql dialect.
I hope is good now for merge.
Thanks
> Wrap index names

- src/migrate/index.js
- src/query/string.js
Not a global change - only affects a couple of modules I looked at while tracking down some migration problems.
> Minor stylistic code & comment touch up + typo fixes

- index.html
Broken link found while browsing through the docs.
> Fix broken "browser builds" link

- src/dialects/mssql/schema/tablecompiler.js
- test/unit/schema/mssql.js
This is my first pull request so apologies if something isn't right.
It includes changes to MSSQL for adding and dropping columns.  Previously single column changes worked but multiple columns didn't.
https://github.com/tgriesser/knex/issues/1348
> #1348 MSSQL adding and dropping multiple columns fix

- index.html
> Add documentation for .dropTimestamps

- README.md
- index.html
Add MSSQL as a supported database in the intro paragraph to be consistent with the other MSSQL related changes to index.html. :smile:
> Update to include MSSQL as a supported DB

- src/transaction.js
@teh-botol noticed more places where warning is displayed.
Issue: #1388
Original PR: #1460
> Fixes warning "a promise was created but was not returned" in more places

- src/seed/stub/coffee.stub
- src/seed/stub/eg.stub
- src/seed/stub/js.stub
- src/seed/stub/ls.stub
I don't know the other 3 languages very well, so I did my best guess at what their equivalents would be.
I was also unable to run tests because I couldn't get some of the db drivers to install on Windows.
This is a fix for #1470
> :bug: Update seed stubs to run serially.

- package.json
- src/dialects/mysql/index.js
- src/query/compiler.js
- src/raw.js
Missed this [here](https://github.com/tgriesser/knex/commit/c292fd591760302a705fd3f3e1c6d5ad18647954).
> Lint before tests in CI

- docs/assets/style.css
> Fix code blocks.

- index.html
Please find the related issues: #491, #1608
> Updated docs to note schema builder is getter.

- package.json
- scripts/build.js
Support using knex as a dependency from git without having to perform extra `npm install & npm run build` configuration.
Using build.js from Bookshelf https://github.com/tgriesser/bookshelf/blob/8ae37faeecfb73bc6a55672e4487202061421c74/scripts/build.js
Closes #1180
> Support using dependency straight from git repository

- src/migrate/index.js
> Return reject

- package.json
> include scripts in npm package

- src/seed/stub/coffee.stub
- src/seed/stub/eg.stub
- src/seed/stub/js.stub
- src/seed/stub/ls.stub
Per discussion in https://github.com/tgriesser/knex/pull/1769.
> Update stub examples to not use Promise.all

- bin/cli.js
> Align CLI description

- .travis.yml
- src/dialects/mssql/schema/tablecompiler.js
- src/dialects/mysql/schema/tablecompiler.js
- src/dialects/oracle/schema/tablecompiler.js
- src/dialects/postgres/schema/tablecompiler.js
- src/dialects/sqlite3/schema/tablecompiler.js
- src/schema/columnbuilder.js
- src/schema/tablecompiler.js
- test/integration/schema/index.js
- test/unit/schema/mssql.js
- test/unit/schema/mysql.js
- test/unit/schema/oracle.js
- test/unit/schema/postgres.js
- test/unit/schema/sqlite3.js
Finished version for of pull request #1759
> Alter column syntax for table, implements changing type, nullability and default

- src/util/batchInsert.js
- src/util/make-knex.js
- test/integration/builder/inserts.js
Not my finest work, but batchInsert needs a complete rewrite down the line anyways. Consider this a temporary fix and/or improvement to an otherwise broken class.
> Ensure errors in batchInsert do not end up 'unhandled'. Fixes #1880

- test/unit/query/builder.js
I found out that there is no unit test for right/rightOuterJoin so here is one that combines them both.
I do not include test for sqlite3 because it currently does not support right join.
> Add unit test for right/rightOuterJoin combination

- README.md
IMHO objection deserves it's spot right there beside bookshelf
> add link to objection ORM

- src/client.js
- src/dialects/mysql2/index.js
- test/tape/invalid-db-setup.js
- test/tape/pool.js
> More pool tests and test on borrow default

- .travis.yml
- package.json
Testing different travis configurations
> Disable oracledb tests from non LTS nodes

- src/query/compiler.js
> Set toNative() to be not enumerable

- src/schema/builder.js
Related documentation fixes https://github.com/knex/documentation/pull/83
> Fixes #1303

- src/query/compiler.js
- test/unit/query/builder.js
> Throw an error if .update() results in an empty sql

- test/integration/builder/additional.js
Fixes #2485 
Docs: https://github.com/knex/documentation/pull/89
> Added test for Event 'start'

- CONTRIBUTING.md
- package.json
- scripts/mssql-docker-compose.yml
- test/knexfile.js
Currently mssql tests are failing. This will enable easy debugging of them for everyone.
> Runnin mssql tests in docker

- src/client.js
- src/ref.js
- src/util/make-knex.js
- test/integration/builder/selects.js
- test/unit/query/builder.js
This a dead simple implementation of #2507 which could definitely be improved upon. *(Which I'm more than open for)*
Can write more tests and write docs once design and featureset has been finalized.
> Added 'ref' function

- src/dialects/maria/index.js
- src/dialects/mssql/index.js
- src/dialects/mysql/index.js
- src/dialects/oracle/index.js
- src/dialects/oracledb/index.js
- src/dialects/sqlite3/index.js
- src/helpers.js
> Testing removal of 'skim'

- package.json
> Revert "Added build step to test script"

- src/query/builder.js
- test/unit/query/builder.js
Fixes #2658.
I looked through other builders to find similar cases but couldn't find any at first glance.
> Fix issue with select(0)

- test/integration/builder/unions.js
- test/unit/query/builder.js
I've [been sending pull requests the TypeScript DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27818) when I've found things like this, but I thought it might be nice to also upstream some test changes as I run across cases that aren't being covered already and are ambiguous in the documentation. I'll also open a documentation PR that disambiguates this, too.
Most of these tests are superfluous once/if knex moves to TypeScript, since it is more or less just type assertions.
> Add tests for multiple union arguments with callbacks and builders

- src/dialects/mssql/query/compiler.js
- src/dialects/postgres/query/compiler.js
- src/query/compiler.js
- test/unit/query/builder.js
> Compile with before update so that bindings are put in correct order

- src/query/compiler.js
- test/integration/builder/joins.js
- test/unit/query/builder.js
This is an attempt to fix #2136. Also added an integration test, couldn't find any existing.
> Use columnize instead of wrap in using().

- src/dialects/sqlite3/schema/ddl.js
- test/index.js
- test/unit/dialects/sqlite3.js
> Added support for `renameColumn` and double slashes

- README.md
As suggested by @Siilwyn [here](https://github.com/tgriesser/knex/issues/2731). Keep up the good work!
(full disclosure: I'm on the team that's responsible for LGTM.com)
> Introduce LGTM.com badge

- CONTRIBUTING.md
- package.json
- types/knex.d.ts
Copying the knex [type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/knex/index.d.ts) from DefinitelyTyped into the project. 
Putting these here will be useful since we can update them as new API's are merged.
> Manage types internally

- CONTRIBUTING.md
- README.md
1) We don't support Maria or WebSQL anymore;
2) Use ES6 syntax consistently;
3) Typo fix.
> Minor documentation fixes and updates

- README.md
- UPGRADING.md
I've tried to include cases that are plausible to be found in real production environments. If someone have their favourite breaking change not mentioned, please let me know.
> Version upgrade guide

- types/knex.d.ts
> Add queryContext to type declarations

- CHANGELOG.md
- bin/cli.js
- test/jake-util/knexfile-relative/knexfile.js
- test/jake/jakelib/knexfile-test.js
> Resolve migrations and seeds relatively to knexfile directory

- package.json
- src/seed/Seeder.js
- src/util/make-knex.js
- test/jake-util/seeds-error-knexfile.js
- test/jake-util/seeds-error/seeds.js
- test/jake/Jakefile
- test/jake/jakelib/seed-test.js
- test/tape/seed.js
fixes https://github.com/tgriesser/knex/issues/2972
> Display name of a failed seed

- test/integration/migrate/async-await-drop-and-recreate-with-schema/01_create.js
- test/integration/migrate/async-await-drop-and-recreate-with-schema/02_drop_and_recreate.js
- test/integration/migrate/async-await-drop-and-recreate/01_create.js
- test/integration/migrate/async-await-drop-and-recreate/02_drop_and_recreate.js
- test/integration/migrate/drop-and-recreate-with-schema/01_create.js
- test/integration/migrate/drop-and-recreate-with-schema/02_drop_and_recreate.js
- test/integration/migrate/drop-and-recreate/01_create.js
- test/integration/migrate/drop-and-recreate/02_drop_and_recreate.js
- test/integration/migrate/index.js
> Tests for drop-and-recreate with async/await

- src/dialects/mysql/schema/columncompiler.js
- src/dialects/mysql/schema/tablecompiler.js
- test/integration/migrate/index.js
- test/integration/migrate/null_timestamp_default/01_create.js
> Support nullable timestamps on MySQL

- types/knex.d.ts
for `havingBetween` `orHavingBetween` `havingNotBetween` `orHavingNotBetween`
> adding types 

- test/knexfile.js
- test/unit/knex.js
> Try using much smaller timeouts

- types/index.d.ts
- types/test.ts
> Fix incorrect type definitions for single row queries

- types/index.d.ts
- types/test.ts
> Include undefined in type of single row results

- types/index.d.ts
- types/test.ts
Fixes: https://github.com/tgriesser/knex/issues/3229#issuecomment-497560577
> Update type of aggregation results to not be arrays when first has been invoked before

- types/index.d.ts
> Add decimalNumbers to MySqlConnectionConfig interface

- types/index.d.ts
- types/test.ts
Fixes: https://github.com/tgriesser/knex/issues/3229#issuecomment-497970046
> Improve typings for aggregations

- package.json
- types/index.d.ts
> [Typings] Add workarounds for degraded inference when strictNullChecks is set to false

- bin/cli.js
- bin/utils/cli-config-utils.js
- test/cli/migrate-make.spec.js
- test/jake-util/knexfile-ts/knexfile.ts
> Use extension from knexfile filename for generating migrations unless overriden

- bin/cli.js
- test/cli/migrate-make.spec.js
> Fix extension resolution from env configs

- src/transaction.js
Fixes second issue from #3309.
> Fix remove duplicate transaction promise

- lib/dialects/mysql/schema/columncompiler.js
- test/unit/schema/mysql.js
> Fallback to JSON when using JSONB in MySQL

- .travis.yml
- lib/transaction.js
- test/index.js
- test/integration/index.js
- test/integration/schema/index.js
- test/unit/knex.js
> More consistent handling of nested transactions

- bin/cli.js
- bin/utils/cli-config-utils.js
- bin/utils/migrationsLister.js
- lib/migrate/Migrator.js
- test/jake/jakelib/migrate-test.js
Add's `list` or `status` command to knex cli to show both completed and pending migrations.
> knex cli list all migrations with status (#3390)

- types/index.d.ts
- types/test.ts
- Add missing typedefs for or and timeout (Closes #3422)
- Move clone from QueryInterface to QueryBuilder
> Fix some issues with QueryBuilder types

- types/index.d.ts
- types/test.ts
> Fix Typescript type inference for  to better support wildcard (*) calls 

- types/index.d.ts
This fixes the test failure in https://github.com/knex/knex/pull/3528
> Add client property to QueryBuilder type

- lib/logger.js
- types/index.d.ts
> Make logger methods mutually consistent

- lib/query/compiler.js
- test/unit/query/builder.js
> Return more information about empty updates

- lib/schema/compiler.js
- test/integration/schema/index.js
> Throw better error when trying to modify schema while using unsupported dialect

- types/index.d.ts
- types/test.ts
> Fix incorrect type of QueryBuilder.first('*') result

- package.json
- scripts/stress-test/knex-stress-test.js
- scripts/stress-test/mysql2-random-hanging-every-now-and-then.js
- scripts/stress-test/mysql2-sudden-exit-without-error.js
- scripts/stress-test/reconnect-test-mysql-based-drivers.js
- test/chai-setup.js
- test/index.js
- test/integration/builder/additional.js
- test/integration/builder/inserts.js
- test/integration/builder/transaction.js
- test/integration/migrate/index.js
- test/tape/crossdb-compatibility.js
- test/tape/harness.js
- test/tape/index.js
- test/tape/invalid-db-setup.js
- test/tape/pool.js
- test/tape/transactions.js
- test/unit/knex.js
- test/unit/migrate/migration-list-resolver.js
check https://github.com/knex/knex/pull/3650 for older discussions
> remove dependency on bluebird methods from tests

- lib/client.js
- lib/dialects/mssql/index.js
- lib/dialects/mssql/transaction.js
- lib/dialects/mysql/index.js
- lib/dialects/oracle/index.js
- lib/dialects/oracle/transaction.js
- lib/dialects/oracledb/index.js
- lib/dialects/oracledb/transaction.js
- lib/dialects/postgres/index.js
- lib/dialects/sqlite3/index.js
- lib/interface.js
- lib/migrate/migration-list-resolver.js
- lib/runner.js
- lib/transaction.js
- lib/util/finally-mixin.js
- lib/util/promises.js
- lib/util/timeout.js
- package.json
- scripts/build.js
- types/index.d.ts
see https://github.com/knex/knex/pull/3650
wait for https://github.com/knex/knex/pull/3682
> remove dependency on bluebird methods from sources

- lib/util/parse-connection.js
> Make protocol length check more defensive

- types/index.d.ts
- types/test.ts
Closes https://github.com/knex/knex/issues/3652
> typings: support Raw types for insert, where, update

- package.json
> Revert "coverage calculation fix"

- lib/query/builder.js
- lib/query/methods.js
- package.json
- test/unit/query/builder.js
- types/index.d.ts
Documentation PR: knex/documentation#261
> Add clearGroup method

- types/index.d.ts
- Issue reported in https://github.com/knex/knex/issues/3755 is not reproducible in master due to incorrect matching of update signature.
- Workaround for https://github.com/microsoft/TypeScript/issues/37524
> Fix minor issues around typings

- types/index.d.ts
Interface as provided by #3513.
There's a separate PR for docs at https://github.com/knex/documentation/pull/257
> Add types for `.distinctOn`

- bin/cli.js
- bin/utils/cli-config-utils.js
- lib/migrate/Migrator.js
- lib/migrate/migration-list-resolver.js
- test/cli/migrate-unlock.spec.js
- test/integration/migrate/migration-integration-tests.js
- test/integration/suite.js
> Refactor migration logic to use async/await. Add test case for using classes with custom migration sources

- bin/cli.js
- lib/logger.js
- lib/migrate/Migrator.js
- lib/migrate/configuration-merger.js
- test/cli/knexfile-test.spec.js
- test/integration/migrate/migration-integration-tests.js
- test/jake-util/knexfile-custom-migration-source/knexfile-with-directory.js
- test/jake-util/knexfile-custom-migration-source/knexfile.js
> Warn user if custom migration source is being reset

- lib/dialects/mssql/schema/tablecompiler.js
- test/integration/builder/additional.js
- test/integration/migrate/drop-with-default-constraint/01_create.js
- test/integration/migrate/drop-with-default-constraint/02_drop_column.js
- test/integration/migrate/migration-integration-tests.js
- test/unit/schema/mssql.js
Basically the same as #2493, just with integration tests added (and some code formatting).
Fixes #2492.
> Added the removal of a columns default constraint, before dropping the column (MSSQL), with integration tests

- README.md
I'm taking care of a few chores and feature ideas for the query lab and https was one of them. Thanks!
> Change query lab link to https

- lib/seed/Seeder.js
- lib/util/fs.js
- test/cli/seed.spec.js
- test/jake-util/seeds-knexfile-directories.js
- test/jake-util/seeds-recursive/first/third/first.js
- test/jake-util/seeds-recursive/second/before-second.js
- test/jake-util/seeds-recursive/second/second.js
- test/unit/seed/seeder.js
Work in progress for the #3786 issue.
@kibertoad could you tell me if this WIP look good for you ?
I need some advice to add tests on the codebase. 
Could you give me some directions ?
> 3786 seed data subfolders

- bin/cli.js
- test/cli/seed.spec.js
- test/jake-util/knexfile-esm-module/.eslintrc.json
- test/jake-util/knexfile-esm-module/knexfile.js
- test/jake-util/knexfile-esm-module/migrations/one.js
- test/jake-util/knexfile-esm-module/package.json
- test/jake-util/knexfile-esm-module/seeds/one.js
- test/jake-util/knexfile-esm/knexfile.js
- test/jake-util/knexfile-esm/migrations/one.js
- test/jake-util/knexfile-esm/seeds/one.js
- test/jake/jakelib/migrate-test.js
Provide a require extension to avoid Node's resolution 'error' .
>  ESM module interop fails if calling module/package is of type 'module' #3937 

- lib/seed/Seeder.js
- lib/util/fs.js
- test/cli/seed.spec.js
- test/jake-util/seeds-knexfile-directories-recursive.js
- test/unit/seed/seeder.js
- types/index.d.ts
* make the seed file finding process not recursive by default
* related to https://github.com/knex/knex/issues/3786#issuecomment-671209814
> Add new option for seed : recursive

- lib/seed/Seeder.js
- test/cli/seed.spec.js
fix(seed): throw error when specific seed file cannot be found
fixes #4005
> Throw error when specific seed file cannot be found

- lib/migrate/Migrator.js
- lib/migrate/configuration-merger.js
- test/integration/migrate/migration-integration-tests.js
> Fix double merging of config for migrator

- types/index.d.ts
These two types seems to describe the same thing while being out of sync.
> Unify SeedsConfig and SeederConfig

- test/cli/esm-interop.spec.js
The error message change from node v14.13.0 to v14.14.0, breaking a number of unit tests.
If all is good, please kindly tag the PR as "hacktoberfest-accepted" for credit towards [hacktoberfest](https://hacktoberfest.digitalocean.com/faq).
> Fixes build issue related to Node.js 14

- lib/dialects/mysql/schema/columncompiler.js
- lib/dialects/postgres/schema/columncompiler.js
- test/unit/schema/mysql.js
- test/unit/schema/postgres.js
> Fix comment escaping for MySQL and PostgreSQL

- lib/interface.js
- test/unit/migrate/schemaBuilder.js
Accept empty schema builder.
fixes https://github.com/mikro-orm/mikro-orm/issues/961
> Make toQuery behavior consistent with pre-0.21.7

- lib/query/builder.js
- test/unit/query/builder.js
- types/index.d.ts
Add method `clear(statement)` in `QueryBuilder` for https://github.com/knex/knex/issues/1476
> feat(QueryBuilder): add method clear(statement)

- lib/transaction.js
- test/unit/knex.js
fixes #4085
Also revises knex unit tests to ensure that tests close cleanly.
> Add missing event propagation

- lib/query/compiler.js
- lib/raw.js
- lib/util/nanoid.js
- package.json
- test/integration/builder/inserts.js
- test/unit/util/nanoid.js
Makes ids more easily mockable.
fixes #3774
> Replace uuid with copied nanoid logic

- lib/dialects/mssql/query/compiler.js
- lib/dialects/mysql/query/compiler.js
- lib/dialects/oracle/query/compiler.js
- lib/dialects/postgres/query/compiler.js
- lib/dialects/sqlite3/query/compiler.js
- lib/query/builder.js
- test/integration/builder/inserts.js
- test/unit/query/builder.js
- types/index.d.ts
- types/test.ts
CC: #3186
^ I'll write it up there.
Documentation PR: https://github.com/knex/documentation/pull/260
> Implement "UPSERT" (Postgres/MySQL/Sqlite)

- package.json
- types/index.d.ts
- types/tables.d.ts
- types/test.ts
This reverts commit c347408a
fixes #4097
> Revert "Allow to globally define table/record mapping (#4071)"

- package.json
- types/index.d.ts
- types/tables.d.ts
- types/test.ts
Fixed the Typescript issues in the first PR.
Had to change imports a bit since there are issues with mixing modern and commonjs exports. Will update docs as well.
> Global table definitions v2

- types/index.d.ts
use tarn configs instead of generic-pool
> use tarn configs instead of generic-pool

- types/index.d.ts
- types/test.ts
Looks like I broke array insert type. This adds tests for it and fix as well.
> Fix types for insert to allow array

- types/index.d.ts
> Added type for withKeyName

- test-tsd/batchInsert.test-d.ts
- types/index.d.ts
> fix/4068 batchInsert correct definitions

- types/index.d.ts
Update type definition for WhereIn for mixed value and query builder
> Update type definition for WhereIn

- types/index.d.ts
This pull request adds types for connection config of mysql2 driver.
> Add types for connection config of mysql2 driver

- lib/dialects/oracledb/index.js
fixes #4146
Unfortunately, no integration test for this, as we'd need a separate instance of Oracle for this :-/
> Support non-standard Oracle port

- lib/dialects/mssql/transaction.js
> Avoid connection getting stuck on socket hangup

- lib/util/import-file.js
Fixes https://github.com/knex/knex/issues/4159
> Bugfix: Uses esm import if package.json type is module

- types/index.d.ts
add after to columnbuilder definition
> Update index.d.ts fixes #3549

- lib/util/parse-connection.js
- test/tape/parse-connection.js
tldr: stop using legacy url.parse api and use new URL() instead
Changes:
https://nodejs.org/api/url.html#url_percent_encoding_in_urls
> whatwg url connection string parsing

- UPGRADING.md
> add to upgrading note for url format migration

- test-tsd/types.test-d.ts
- types/index.d.ts
> Add missing onConflict overrides

- lib/dialects/sqlite3/schema/ddl.js
- lib/dialects/sqlite3/schema/internal/sqlite-ddl-operations.js
- lib/dialects/sqlite3/schema/sqlite-compiler.js
- lib/dialects/sqlite3/schema/sqlite-tablecompiler.js
- lib/execution/runner.js
- lib/schema/builder.js
- lib/schema/compiler.js
- lib/util/nanoid.js
- test/integration2/schema/foreign-keys.spec.js
- types/index.d.ts
> Return complete list of DDL commands for creating foreign keys in SQLite

- lib/dialects/sqlite3/schema/ddl.js
- test/integration/schema/foreign-keys.js
Closes https://github.com/knex/knex/issues/4201
> Sqlite drop composite foreign keys

- lib/dialects/sqlite3/schema/ddl.js
- test/integration2/schema/foreign-keys.spec.js
It's just a typo fix for #4162.
> Fix SQLite foreign on delete when altering a table

- lib/formatter/wrappingFormatter.js
- test/integration2/query/select/fts.spec.js
> Allow 'match' operator

- test/integration2/dialects/mysql2.js
- test/integration2/util/knex-instance-provider.js
> Add test for MySQL port resolution

- lib/dialects/mssql/index.js
> 0.21 fix mssql remove unused pool config option

- lib/dialects/mssql/index.js
- lib/dialects/mysql/index.js
- lib/dialects/oracledb/index.js
- lib/dialects/sqlite3/index.js
- lib/query/querybuilder.js
- test/db-less-test-suite.js
- test/integration2/query/select/pluck.spec.js
- test/tape/index.js
- test/unit/query/builder.js
> Make "first" and "pluck" mutually exclusive

- types/index.d.ts
as per https://github.com/knex/knex/pull/4172#discussion_r552149801
> Fix ArrayIfAlready type

- lib/dialects/sqlite3/schema/ddl.js
- test/integration2/schema/foreign-keys.spec.js
backport of https://github.com/knex/knex/pull/4330
> SQLite: Made the constraint detection case-insensitive

- test/integration/query/inserts.js
- test/unit/migrations/util/fs.js
I noticed there are two more asynchronous tests not awaited on.
> Await asynchronous expect assertions

- bin/cli.js
> fix knex init not finding default knexfile

- package.json
Hi. First time contributing. I just did an `npm i` and I had a diff in `package.json`. So instead of discarding it, or keeping a dirty working tree, I decided to do a PR, so `npm i`s from now on would be cleaner. my `npm` version is `7.6.1`
> package.json changes (order/sort) made by npm@7.6.1

- README.md
- knex.mjs
- package.json
> Improve ESM import support

- lib/formatter/wrappingFormatter.js
> Add same as operator for postgres

- types/index.d.ts
Attempt to fix #4397 by adding type definition to types/index.d.ts . That's my first PR, if I should do it in another way, let me know.
> Adding Type Definition for isTransaction

- lib/query/analytic.js
- types/index.d.ts
- types/test.ts
Add typing for new analytic functions i.e rowNumber, rank, denseRank
> [Typing] Add types for analytic functions

- types/index.d.ts
- types/test.ts
> Include options object in count(Distinct) typings

- test-tsd/transaction.test-d.ts
- types/index.d.ts
export `Knex.TransactionConfig`
> let types export Knex.TransactionConfig

- ECOSYSTEM.md
A brief description of the knemm tool.
> Update ECOSYSTEM.md - knemm

- types/index.d.ts
also addressing missing datetime missing in 
close #3944
> Improve Typing: add typescript support for deferrable, new Primary/Unique syntax

- lib/migrations/migrate/stub/mjs.stub
- lib/migrations/seed/stub/mjs.stub
- used the github.dev tool to create a PR... not sure if there's a PR template this ignored
- I believe this fixes #4404
> adding .mjs migration and seed stubs

- .github/workflows/coverage.yml
- .github/workflows/integration-tests.yml
- .github/workflows/linting.yml
- package.json
- scripts/docker-compose.yml
pg-native is a pain to install on Windows system. Let's not install it by default.
> Do not install pg-native by default

- lib/dialects/postgres/schema/pg-columncompiler.js
- test/integration/query/selects.js
- test/integration/query/unions.js
- test/integration2/query/insert/inserts.spec.js
- test/integration2/schema/misc.spec.js
- test/util/assertHelper.js
Also fix a bunch of other tests
> Fix JSON support for CockroachDB

- lib/dialects/postgres/schema/pg-columncompiler.js
- test/unit/schema-builder/postgres.js
(cherry picked from commit a431485aa6308aa2e9046f89b9216e7057caaa29)
> Zero precision in timestamp/datetime #4784 (#4786)

- types/index.d.ts
(cherry picked from commit f200e668c7bedbbf20ad75366276d5127de0b2de)
> Allow string indexType in index creation (#4791)

- lib/dialects/mysql/index.js
- lib/dialects/mysql2/index.js
- test/tape/pool.js
- Fix mysql2 validate connection.
- Closes https://github.com/knex/knex/issues/4794#issuecomment-963568255
> Mysql2 validate connection fix #4794

- lib/dialects/cockroachdb/crdb-querycompiler.js
- lib/dialects/mssql/query/mssql-querycompiler.js
- lib/dialects/postgres/query/pg-querycompiler.js
- lib/dialects/redshift/query/redshift-querycompiler.js
- lib/query/querycompiler.js
- Remove duplicate in upsert and insert.
- Remove duplicate in multiHavingIn, it's multiOnIn.
- Remove duplicate when building insert values in mssql and querycompiler.
- Remove duplicate in PG and Redshift with ColumnInfo
> [CLEAN] Remove duplicate code

- test/integration2/schema/misc.spec.js
- types/index.d.ts
- Add 3 missings typings for ints : mediumint, bigint and smallint.
- Closes #1173
> Add missing ints typings #1173

- lib/migrations/migrate/Migrator.js
- lib/migrations/migrate/table-creator.js
- test/integration2/migrate/migration-integration.spec.js
(cherry picked from commit 540ab8c020e572581b1db9898b1e21ba1da32923)
> Insert lock row fix during migration (#4865)

- lib/query/querybuilder.js
- test/unit/query/builder.js
- ForUpdate add 'as' when using array. Properly handling array notation.
- Closes #4878
> ForUpdate array parameter

- lib/dialects/sqlite3/schema/ddl.js
- lib/dialects/sqlite3/schema/sqlite-tablecompiler.js
- test/integration2/schema/alter.spec.js
Reverts #4336.
Now that #4189 has been merged, we can safely revert this PR.
> Revert "Fix SQLite not doing rollback when altering columns fails (#4336)"

- lib/knex-builder/FunctionHelper.js
- test/integration2/query/misc/additional.spec.js
- types/index.d.ts
I pull request for adding type and add the order param by the way
> feat: add order and type for uuidtobin and binToUuid

- types/index.d.ts
Fixes #4995. Let me know if I need to add anything more to the PR
> Fix argument type of `alter` method

- lib/query/method-constants.js
> Add withMaterialized and withNotMaterialized to method-constants

- lib/dialects/postgres/query/pg-querycompiler.js
- test/unit/query/builder.js
- Fix missing parts during "where" clauses construction with del + joins in PostgreSQL
- Closes https://github.com/knex/knex/issues/5015
> Fix delete joins with PostgreSQL

- lib/query/querycompiler.js
- test/integration2/query/select/joins.spec.js
- Syntax error with "on clause" + subquery.
- Closes #5046
> Subquery in on clause missing parenthesis #5046

- bin/utils/migrationsLister.js
- test/jake/jakelib/migrate-test.js
> Fix completed migration listing

- .eslintrc.js
- package.json
- Add an eslint mocha no only rule that thrown an error during linting.
- Suggested by https://github.com/knex/knex/commit/9d62cbfdb154950e868ca6fb59fd3ab785b20252#commitcomment-69103257
> Add eslint mocha no only rule

- test/integration2/query/insert/inserts.spec.js
- test/integration2/query/misc/additional.spec.js
- test/integration2/query/select/joins.spec.js
- test/integration2/query/select/unions.spec.js
- test/integration2/query/select/where.spec.js
- test/integration2/query/update/updates.spec.js
- Convert all query integration test files to async / await notation.
- https://github.com/knex/knex/issues/3170
> Async/await in tests : all query integration files

- README.md
- Since DavidDM is offline, I add another dependencies status badge.
> Remove DavidDM obsolete badge and add Libraries.io

- .husky/pre-commit
- package.json
- Close https://github.com/knex/knex/pull/4758
> Migrate Husky from 4 to 7

- types/index.d.ts
> Update type definitions for pg connection

- types/index.d.ts
Issue: https://github.com/knex/knex/issues/5305
> types: fix WhereJsonObject&CompositeTableType

- lib/client.js
Issue: https://github.com/knex/knex/issues/5320
> fix: insert array into json column

- lib/dialects/postgres/execution/pg-transaction.js
- lib/dialects/redshift/transaction.js
- lib/dialects/sqlite3/execution/sqlite-transaction.js
- lib/execution/transaction.js
- test/integration2/transaction/set-readonly.spec.js
- types/index.d.ts
Attempt to add the ability to make read only transactions in MySQL, Postgres, and Redshift
Documentation PR: https://github.com/knex/documentation/pull/489
> Add readonly transaction access mode

- types/index.d.ts
add fetchAsString props to Knex.Config interface
> add fetchAsString props to Knex.Config interface

- types/index.d.ts
I think this was forgotten in #1147. This is my first contribution, so let me know if there's anything missing.
btw, thank you for the nice work on knex, you rock 🥳
> add collate to the columnbuilder interface

- types/index.d.ts
Regression of #4246
Fixes #4246
> fix: add ResolveTableType for `.merge()`

- lib/query/querybuilder.js
- test/unit/query/builder.js
> fix: handle numeric array elements in .orderBy()

- lib/dialects/mysql/index.js
- lib/dialects/mysql/query/mysql-querybuilder.js
- lib/dialects/mysql/query/mysql-querycompiler.js
- test/integration2/dialects/mysql.spec.js
- test/unit/query/builder.js
Closes: https://github.com/knex/knex/issues/4769
Knex documentation update: https://github.com/knex/documentation/pull/556
Done:
- added `upsert` implementation for MySQL
- added unit tests
- added integration tests
MySQL docs: https://dev.mysql.com/doc/refman/8.0/en/replace.html
> MySQL dialect: added implementation for upsert 

- types/index.d.ts
see 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/49fc830743fd476b63adfb766655e24e0aa871ec/types/pg/index.d.ts#L24
for updated type
> Fix pg typing to reflect pg typing change

- .github/workflows/docs-deploy.yml
fix after the prev PR:
- https://github.com/knex/knex/pull/5792
> fix docs deployment

- docs/src/guide/query-builder.md
Docs for this PR: https://github.com/knex/knex/pull/5743
change migrated from: https://github.com/knex/documentation/pull/556
> update upsert documentation with support in MySQL
